import type { Parziale } from '../tipi';

// Sezione «bancaDati»: italiano di riferimento, poi tedesco svizzero («Sie», «ss») e francese («vous»).
// Banca dati (C2), risultati (C3), legge (C4, C6) e documento (C5). Dove il testo c'è già su
// lexum.ch (avv_banca_dati, comp_aggiungi_etichetta) è ripreso da lì.

const it = {
  intro: 'Cerca per parole o sfoglia le fonti. È gratis e non usa crediti.',
  segnaposto: 'Parole, articolo o numero…',
  cerca: 'Cerca nella banca dati',
  sfoglia: 'Sfoglia',
  recenti: 'Cercate di recente',
  filtri: { tutto: 'Tutto', norme: 'Norme', sentenze: 'Sentenze', prassi: 'Prassi', ue: 'UE' },
  // il tipo di un risultato o di un documento, come si legge nel badge
  tipi: { Norma: 'Norma', Sentenza: 'Sentenza', Prassi: 'Prassi', UE: 'UE' },
  ordinati: 'Ordinati per pertinenza',
  annoOrgano: 'Anno, organo',
  offlineTitolo: 'Senza connessione',
  offlineTesto: 'La ricerca nella Banca dati torna appena sei online.',
  vuotoTitolo: 'Nessun risultato',
  vuotoTesto: 'Prova con altre parole o togli il filtro.',
  norma: 'Norma',
  notaRicerca: 'Evidenziato il passaggio più vicino alla tua ricerca.',
  documento: {
    titolo: 'Documento',
    assente: 'Questo documento non è nei dati di prova.',
    gratuita: 'Gratuita',
    principio: 'Principio di diritto',
    norme: 'Norme richiamate',
    normaRichiamata: 'Norma richiamata',
    testoIntegrale: 'Testo integrale',
    chiedi: 'Chiedi a Lex',
    aggiungi: 'Aggiungi a etichetta',
  },
  legge: {
    titolo: 'Legge',
    assente: 'Questa legge non è nei dati di prova.',
    tornaChat: 'Torna alla chat',
    salvaEtichetta: "Salva la legge in un'etichetta",
    salva: 'Salva la legge',
    apertaDa: 'Aperta dalla chat «{titolo}»',
    cerca: 'Cerca nella legge',
    segnaposto: 'Cerca per articolo, rubrica o testo…',
    apri: '{titolo}, apri',
    chiudi: '{titolo}, chiudi',
    citatoQui: 'Citato da Lex in questa chat',
    citatoUltima: 'Citato da Lex nella tua ultima chat',
    articolo: 'Articolo {numero}: {rubrica}',
    restaAperta: "La chat resta aperta dove l'hai lasciata.",
  },
};

const de: Parziale<typeof it> = {
  intro:
    'Suchen Sie mit Stichwörtern oder durchsuchen Sie die Quellen. Das ist kostenlos und braucht keine Credits.',
  segnaposto: 'Stichwörter, Artikel oder Nummer…',
  cerca: 'In der Datenbank suchen',
  sfoglia: 'Durchsuchen',
  recenti: 'Kürzlich gesucht',
  filtri: { tutto: 'Alle', norme: 'Normen', sentenze: 'Urteile', prassi: 'Praxis', ue: 'EU' },
  tipi: { Norma: 'Norm', Sentenza: 'Urteil', Prassi: 'Praxis', UE: 'EU' },
  ordinati: 'Nach Relevanz sortiert',
  annoOrgano: 'Jahr, Instanz',
  offlineTitolo: 'Keine Verbindung',
  offlineTesto: 'Die Suche in der Datenbank ist wieder da, sobald Sie online sind.',
  vuotoTitolo: 'Keine Ergebnisse',
  vuotoTesto: 'Versuchen Sie es mit anderen Wörtern oder entfernen Sie den Filter.',
  norma: 'Norm',
  notaRicerca: 'Hervorgehoben ist die Stelle, die Ihrer Suche am nächsten kommt.',
  documento: {
    titolo: 'Dokument',
    assente: 'Dieses Dokument ist nicht in den Testdaten.',
    gratuita: 'Kostenlos',
    principio: 'Rechtsgrundsatz',
    norme: 'Erwähnte Normen',
    normaRichiamata: 'Erwähnte Norm',
    testoIntegrale: 'Volltext',
    chiedi: 'Lex fragen',
    aggiungi: 'Zu Etikett hinzufügen',
  },
  legge: {
    titolo: 'Gesetz',
    assente: 'Dieses Gesetz ist nicht in den Testdaten.',
    tornaChat: 'Zurück zum Chat',
    salvaEtichetta: 'Gesetz mit einem Etikett speichern',
    salva: 'Gesetz speichern',
    apertaDa: 'Geöffnet aus dem Chat «{titolo}»',
    cerca: 'Im Gesetz suchen',
    segnaposto: 'Nach Artikel, Sachüberschrift oder Text suchen…',
    apri: '{titolo}, öffnen',
    chiudi: '{titolo}, schliessen',
    citatoQui: 'Von Lex in diesem Chat zitiert',
    citatoUltima: 'Von Lex in Ihrem letzten Chat zitiert',
    articolo: 'Artikel {numero}: {rubrica}',
    restaAperta: 'Der Chat bleibt offen, wo Sie ihn verlassen haben.',
  },
};

const fr: Parziale<typeof it> = {
  intro: "Cherchez par mots-clés ou parcourez les sources. C'est gratuit et n'utilise pas de crédits.",
  segnaposto: 'Mots, article ou numéro…',
  cerca: 'Rechercher dans la base de données',
  sfoglia: 'Parcourir',
  recenti: 'Recherches récentes',
  filtri: { tutto: 'Tout', norme: 'Normes', sentenze: 'Arrêts', prassi: 'Pratique', ue: 'UE' },
  tipi: { Norma: 'Norme', Sentenza: 'Arrêt', Prassi: 'Pratique', UE: 'UE' },
  ordinati: 'Triés par pertinence',
  annoOrgano: 'Année, instance',
  offlineTitolo: 'Hors ligne',
  offlineTesto: 'La recherche dans la base de données revient dès que vous êtes en ligne.',
  vuotoTitolo: 'Aucun résultat',
  vuotoTesto: "Essayez d'autres mots ou retirez le filtre.",
  norma: 'Norme',
  notaRicerca: 'Le passage le plus proche de votre recherche est surligné.',
  documento: {
    titolo: 'Document',
    assente: 'Ce document ne figure pas dans les données de test.',
    gratuita: 'Gratuit',
    principio: 'Principe de droit',
    norme: 'Normes mentionnées',
    normaRichiamata: 'Norme mentionnée',
    testoIntegrale: 'Texte intégral',
    chiedi: 'Demander à Lex',
    aggiungi: 'Ajouter à une étiquette',
  },
  legge: {
    titolo: 'Loi',
    assente: 'Cette loi ne figure pas dans les données de test.',
    tornaChat: 'Retour au chat',
    salvaEtichetta: 'Enregistrer la loi avec une étiquette',
    salva: 'Enregistrer la loi',
    apertaDa: 'Ouverte depuis le chat « {titolo} »',
    cerca: 'Rechercher dans la loi',
    segnaposto: 'Rechercher par article, note marginale ou texte…',
    apri: '{titolo}, ouvrir',
    chiudi: '{titolo}, fermer',
    citatoQui: 'Cité par Lex dans ce chat',
    citatoUltima: 'Cité par Lex dans votre dernier chat',
    articolo: 'Article {numero} : {rubrica}',
    restaAperta: "Le chat reste ouvert là où vous l'avez laissé.",
  },
};

export const bancaDati = { it, de, fr };
