import type { Parziale } from '../tipi';

// Sezione «chat»: italiano di riferimento, poi tedesco svizzero («Sie», «ss») e francese («vous»).
// La home con Lex, l'attesa, le risposte e i fogli della chat (nuova chat, salva, crediti finiti,
// fonte citata, allega). Dove il testo c'è già su lexum.ch (avv_banca_dati, comp_pacchetto_lampo,
// comp_aggiungi_etichetta) è ripreso da lì.

const it = {
  home: {
    ciao: 'Ciao',
    creditoBenvenutoUno: '1 credito di benvenuto',
    creditoBenvenutoMolti: '{n} crediti di benvenuto',
    primaGratis: 'La tua prima domanda a Lex è gratuita. La Banca dati è sempre libera.',
    seiNella: { IT: 'Sei nella banca dati italiana', CH: 'Sei nella banca dati svizzera' },
    pianoFino: '{piano} fino al {data}',
    appIn: 'app in {lingua}',
    lingue: { it: 'italiano', de: 'tedesco', fr: 'francese' },
    perIniziare: 'Per iniziare, prova con:',
  },
  nonSalvata: {
    testo: "Chat non salvata: con un'etichetta la ritrovi anche dal computer.",
    azione: 'Salva',
  },
  attesa: {
    consulta: 'Lex sta consultando le fonti',
    puoiChiudere: "Puoi chiudere l'app: ti avvisiamo quando la risposta è pronta.",
  },
  errore: {
    titolo: 'Lex non è riuscito a rispondere',
    credito: 'Il credito non è stato scalato.',
    riprova: 'Riprova',
  },
  risposta: {
    copia: 'Copia la risposta',
    salva: 'Salva',
    salvata: 'Salvata',
    condividi: 'Condividi',
  },
  lex: {
    apriFonte: 'Apri la fonte: {fonte}',
    lavora: 'Lex sta lavorando: {passo}. Tocca per vedere subito la risposta.',
    inCorso: 'in corso',
  },
  // Le fasi che lex-lead manda in diretta (src/backend/sse.ts) e i nomi leggibili delle fonti consultate.
  fasi: {
    analisi: 'Analizzo la domanda',
    ricerca: 'Consulto le fonti',
    sintesi: 'Compongo la risposta',
    materiale: 'Ragiono sul materiale fornito',
    scrive: 'Lex sta scrivendo la risposta. Tocca per vederla tutta.',
    attesa: 'Lex sta lavorando: {fase}. Tocca per vedere subito la risposta.',
  },
  fontiLex: {
    norme_core: 'Codici e leggi',
    norme_archivio: 'Norme storiche',
    norme_ue: 'Diritto UE',
    giurisprudenza: 'Giurisprudenza',
    prassi: 'Prassi',
    bdgt_mef: 'Giurisprudenza tributaria',
    deontologia: 'Deontologia',
    norme_federali: 'Diritto federale',
    norme_cantonali: 'Diritto cantonale',
    eu: 'Diritto UE',
    documento: 'Il tuo documento',
  },
  elementi: {
    paese: 'Paese: {nome}',
    pagina: 'Pagina {n} di {totale}',
  },
  nuova: {
    titolo: 'Questa chat non è salvata',
    titoloApre: 'La chat in corso non è salvata',
    testo: "Se apri {cosa}, {chat} si perde. Salvala in un'etichetta per ritrovarla qui e sul sito.",
    unaNuova: 'una nuova chat',
    inCorso: 'la chat in corso',
    titoloChat: '«{titolo}»',
    salva: "Salva in un'etichetta",
    senzaSalvare: 'Nuova chat senza salvare',
    apriSenzaSalvare: 'Apri senza salvare',
  },
  salva: {
    titolo: 'Salva in Ricerche',
    testo: "Scegli un'etichetta: la chat resta salvata e la ritrovi anche sul sito, con lo stesso account.",
    cerca: "Cerca o crea un'etichetta",
    segnaposto: 'Cerca o crea etichetta…',
    gruppo: 'Etichetta',
    elementoUno: '1 elemento',
    elementiMolti: '{n} elementi',
    crea: 'Crea «{nome}»',
    nuova: 'Nuova etichetta',
    salvaIn: 'Salva in «{nome}»',
    scegli: "Scegli un'etichetta",
    nota: 'Una chat che non salvi non resta in memoria: funziona così anche sul sito.',
  },
  esauriti: {
    titolo: 'Continua la tua ricerca',
    ultima: "Hai usato l'ultima ricerca disponibile.",
    offerta:
      'Con il Pacchetto Lampo continui subito con Lex: {n} ricerche a {prezzo}. I crediti non scadono.',
    pacchetto: 'Pacchetto Lampo',
    ricerche: '{n} ricerche con Lex',
    continuaSu: 'Continua su {sito}',
    nota: 'Paghi sul sito con lo stesso account. Poi torni qui e riprendi la ricerca da dove eri.',
    tuoiCrediti: 'I tuoi crediti',
    nonOra: 'Non ora',
  },
  norma: {
    citata: 'Norma citata',
    nota: 'Evidenziato il passaggio usato da Lex.',
    nonDisponibile: "Testo dell'articolo non disponibile nei dati di prova: arriva con la Banca dati vera.",
    apriLegge: 'Apri la legge',
    salva: 'Salva',
  },
  allega: {
    titolo: 'Allega un documento',
    testo: 'Lex lo legge, lo confronta con la legge e risponde alla tua domanda.',
    scansiona: 'Scansiona con la fotocamera',
    scansionaSotto: 'Lettere, multe, contratti su carta: diventano un PDF',
    dispositivo: 'Dal tuo dispositivo',
    dispositivoSotto: 'PDF, Word o testo',
    archivio: 'Dal tuo archivio',
    archivioSotto: 'I documenti che hai già salvato su Lexum',
    nota: "Se non lo salvi nell'archivio, il documento si cancella da solo dopo 4 ore.",
  },
};

const de: Parziale<typeof it> = {
  home: {
    ciao: 'Hallo',
    creditoBenvenutoUno: '1 Willkommens-Credit',
    creditoBenvenutoMolti: '{n} Willkommens-Credits',
    primaGratis: 'Ihre erste Frage an Lex ist kostenlos. Die Datenbank ist immer frei zugänglich.',
    seiNella: {
      IT: 'Sie sind in der italienischen Datenbank',
      CH: 'Sie sind in der Schweizer Datenbank',
    },
    pianoFino: '{piano} bis {data}',
    appIn: 'App auf {lingua}',
    lingue: { it: 'Italienisch', de: 'Deutsch', fr: 'Französisch' },
    perIniziare: 'Probieren Sie zum Einstieg:',
  },
  nonSalvata: {
    testo: 'Chat nicht gespeichert: Mit einem Etikett finden Sie ihn auch am Computer wieder.',
    azione: 'Speichern',
  },
  attesa: {
    consulta: 'Lex konsultiert die Quellen',
    puoiChiudere: 'Sie können die App schliessen: Wir benachrichtigen Sie, sobald die Antwort bereit ist.',
  },
  errore: {
    titolo: 'Lex konnte nicht antworten',
    credito: 'Der Credit wurde nicht abgezogen.',
    riprova: 'Erneut versuchen',
  },
  risposta: {
    copia: 'Antwort kopieren',
    salva: 'Speichern',
    salvata: 'Gespeichert',
    condividi: 'Teilen',
  },
  lex: {
    apriFonte: 'Quelle öffnen: {fonte}',
    lavora: 'Lex arbeitet: {passo}. Tippen Sie, um die Antwort sofort zu sehen.',
    inCorso: 'läuft',
  },
  fasi: {
    analisi: 'Ich analysiere die Frage',
    ricerca: 'Ich konsultiere die Quellen',
    sintesi: 'Die Antwort wird verfasst',
    materiale: 'Ich arbeite mit dem vorgelegten Material',
    scrive: 'Lex schreibt die Antwort. Tippen Sie, um sie ganz zu sehen.',
    attesa: 'Lex arbeitet: {fase}. Tippen Sie, um die Antwort sofort zu sehen.',
  },
  fontiLex: {
    norme_core: 'Gesetze und Kodizes',
    norme_archivio: 'Historische Normen',
    norme_ue: 'EU-Recht',
    giurisprudenza: 'Rechtsprechung',
    prassi: 'Praxis',
    bdgt_mef: 'Steuerrechtsprechung',
    deontologia: 'Standesrecht',
    norme_federali: 'Bundesrecht',
    norme_cantonali: 'Kantonales Recht',
    eu: 'EU-Recht',
    documento: 'Ihr Dokument',
  },
  elementi: {
    paese: 'Land: {nome}',
    pagina: 'Seite {n} von {totale}',
  },
  nuova: {
    titolo: 'Dieser Chat ist nicht gespeichert',
    titoloApre: 'Der laufende Chat ist nicht gespeichert',
    testo:
      'Wenn Sie {cosa} öffnen, geht {chat} verloren. Speichern Sie ihn mit einem Etikett, um ihn hier und auf der Website wiederzufinden.',
    unaNuova: 'einen neuen Chat',
    inCorso: 'der laufende Chat',
    titoloChat: '«{titolo}»',
    salva: 'Mit einem Etikett speichern',
    senzaSalvare: 'Neuer Chat ohne Speichern',
    apriSenzaSalvare: 'Ohne Speichern öffnen',
  },
  salva: {
    titolo: 'In Recherchen speichern',
    testo:
      'Wählen Sie ein Etikett: Der Chat bleibt gespeichert, und Sie finden ihn auch auf der Website, mit demselben Konto.',
    cerca: 'Etikett suchen oder erstellen',
    segnaposto: 'Etikett suchen oder erstellen…',
    gruppo: 'Etikett',
    elementoUno: '1 Element',
    elementiMolti: '{n} Elemente',
    crea: '«{nome}» erstellen',
    nuova: 'Neues Etikett',
    salvaIn: 'In «{nome}» speichern',
    scegli: 'Etikett wählen',
    nota: 'Ein Chat, den Sie nicht speichern, wird nicht aufbewahrt: So ist es auch auf der Website.',
  },
  esauriti: {
    titolo: 'Setzen Sie Ihre Recherche fort',
    ultima: 'Sie haben Ihre letzte verfügbare Recherche genutzt.',
    offerta:
      'Mit dem Blitzpaket machen Sie sofort mit Lex weiter: {n} Recherchen für {prezzo}. Das Guthaben verfällt nicht.',
    pacchetto: 'Blitzpaket',
    ricerche: '{n} Recherchen mit Lex',
    continuaSu: 'Weiter auf {sito}',
    nota: 'Sie bezahlen auf der Website mit demselben Konto. Danach kehren Sie hierher zurück und setzen die Recherche dort fort, wo Sie aufgehört haben.',
    tuoiCrediti: 'Ihre Credits',
    nonOra: 'Nicht jetzt',
  },
  norma: {
    citata: 'Zitierte Norm',
    nota: 'Hervorgehoben ist die Stelle, die Lex verwendet hat.',
    nonDisponibile:
      'Der Text des Artikels ist in den Testdaten nicht verfügbar: Er kommt mit der echten Datenbank.',
    apriLegge: 'Gesetz öffnen',
    salva: 'Speichern',
  },
  allega: {
    titolo: 'Dokument anhängen',
    testo: 'Lex liest es, vergleicht es mit dem Gesetz und beantwortet Ihre Frage.',
    scansiona: 'Mit der Kamera scannen',
    scansionaSotto: 'Briefe, Bussen, Verträge auf Papier: Sie werden zu einem PDF',
    dispositivo: 'Von Ihrem Gerät',
    dispositivoSotto: 'PDF, Word oder Text',
    archivio: 'Aus Ihrem Archiv',
    archivioSotto: 'Die Dokumente, die Sie bereits auf Lexum gespeichert haben',
    nota: 'Wenn Sie das Dokument nicht im Archiv speichern, wird es nach 4 Stunden automatisch gelöscht.',
  },
};

const fr: Parziale<typeof it> = {
  home: {
    ciao: 'Bonjour',
    creditoBenvenutoUno: '1 crédit de bienvenue',
    creditoBenvenutoMolti: '{n} crédits de bienvenue',
    primaGratis: 'Votre première question à Lex est gratuite. La base de données est toujours libre.',
    seiNella: {
      IT: 'Vous êtes dans la base de données italienne',
      CH: 'Vous êtes dans la base de données suisse',
    },
    pianoFino: "{piano} jusqu'au {data}",
    appIn: 'app en {lingua}',
    lingue: { it: 'italien', de: 'allemand', fr: 'français' },
    perIniziare: 'Pour commencer, essayez :',
  },
  nonSalvata: {
    testo: "Chat non enregistré : avec une étiquette, vous le retrouvez aussi sur l'ordinateur.",
    azione: 'Enregistrer',
  },
  attesa: {
    consulta: 'Lex consulte les sources',
    puoiChiudere: "Vous pouvez fermer l'app : nous vous avertissons dès que la réponse est prête.",
  },
  errore: {
    titolo: "Lex n'a pas pu répondre",
    credito: "Le crédit n'a pas été débité.",
    riprova: 'Réessayer',
  },
  risposta: {
    copia: 'Copier la réponse',
    salva: 'Enregistrer',
    salvata: 'Enregistrée',
    condividi: 'Partager',
  },
  lex: {
    apriFonte: 'Ouvrir la source : {fonte}',
    lavora: 'Lex travaille : {passo}. Touchez pour voir la réponse tout de suite.',
    inCorso: 'en cours',
  },
  fasi: {
    analisi: "J'analyse la question",
    ricerca: 'Je consulte les sources',
    sintesi: 'Rédaction de la réponse',
    materiale: 'Je raisonne sur les éléments fournis',
    scrive: 'Lex rédige la réponse. Touchez pour la voir en entier.',
    attesa: 'Lex travaille : {fase}. Touchez pour voir la réponse tout de suite.',
  },
  fontiLex: {
    norme_core: 'Codes et lois',
    norme_archivio: 'Normes historiques',
    norme_ue: "Droit de l'UE",
    giurisprudenza: 'Jurisprudence',
    prassi: 'Pratique',
    bdgt_mef: 'Jurisprudence fiscale',
    deontologia: 'Déontologie',
    norme_federali: 'Droit fédéral',
    norme_cantonali: 'Droit cantonal',
    eu: "Droit de l'UE",
    documento: 'Votre document',
  },
  elementi: {
    paese: 'Pays : {nome}',
    pagina: 'Page {n} sur {totale}',
  },
  nuova: {
    titolo: "Ce chat n'est pas enregistré",
    titoloApre: "Le chat en cours n'est pas enregistré",
    testo:
      'Si vous ouvrez {cosa}, {chat} sera perdu. Enregistrez-le avec une étiquette pour le retrouver ici et sur le site.',
    unaNuova: 'un nouveau chat',
    inCorso: 'le chat en cours',
    titoloChat: '« {titolo} »',
    salva: 'Enregistrer avec une étiquette',
    senzaSalvare: 'Nouveau chat sans enregistrer',
    apriSenzaSalvare: 'Ouvrir sans enregistrer',
  },
  salva: {
    titolo: 'Enregistrer dans Recherches',
    testo:
      'Choisissez une étiquette : le chat reste enregistré et vous le retrouvez aussi sur le site, avec le même compte.',
    cerca: 'Rechercher ou créer une étiquette',
    segnaposto: 'Rechercher ou créer une étiquette…',
    gruppo: 'Étiquette',
    elementoUno: '1 élément',
    elementiMolti: '{n} éléments',
    crea: 'Créer « {nome} »',
    nuova: 'Nouvelle étiquette',
    salvaIn: 'Enregistrer dans « {nome} »',
    scegli: 'Choisir une étiquette',
    nota: "Un chat que vous n'enregistrez pas n'est pas conservé : c'est pareil sur le site.",
  },
  esauriti: {
    titolo: 'Poursuivez votre recherche',
    ultima: 'Vous avez utilisé votre dernière recherche disponible.',
    offerta:
      "Avec le Pack Éclair, vous continuez tout de suite avec Lex : {n} recherches pour {prezzo}. Les crédits n'expirent pas.",
    pacchetto: 'Pack Éclair',
    ricerche: '{n} recherches avec Lex',
    continuaSu: 'Continuer sur {sito}',
    nota: "Vous payez sur le site avec le même compte. Ensuite, vous revenez ici et reprenez votre recherche là où vous l'aviez laissée.",
    tuoiCrediti: 'Vos crédits',
    nonOra: 'Pas maintenant',
  },
  norma: {
    citata: 'Norme citée',
    nota: 'Le passage utilisé par Lex est surligné.',
    nonDisponibile:
      "Le texte de l'article n'est pas disponible dans les données de test : il arrive avec la vraie base de données.",
    apriLegge: 'Ouvrir la loi',
    salva: 'Enregistrer',
  },
  allega: {
    titolo: 'Joindre un document',
    testo: 'Lex le lit, le compare à la loi et répond à votre question.',
    scansiona: "Scanner avec l'appareil photo",
    scansionaSotto: 'Lettres, amendes, contrats papier : ils deviennent un PDF',
    dispositivo: 'Depuis votre appareil',
    dispositivoSotto: 'PDF, Word ou texte',
    archivio: 'Depuis vos archives',
    archivioSotto: 'Les documents que vous avez déjà enregistrés sur Lexum',
    nota: "Si vous ne l'enregistrez pas dans les archives, le document est supprimé automatiquement après 4 heures.",
  },
};

export const chat = { it, de, fr };
