import type { Parziale } from '../tipi';

// Sezione «clienti»: elenco, modulo, scheda del cliente, accesso al portale, note, messaggi.
// Italiano di riferimento, poi tedesco svizzero («Sie», «ss») e francese («vous»).
// I termini svizzeri vengono dal sito (public/locales/*/avv_clienti_*.json, comp_documenti_portale):
// Mandant / client, Dossier / dossier, AHV-Nummer / numéro AVS, UID-Nummer / numéro IDE, PLZ / NPA.
// Le parti solo italiane (codice fiscale, partita IVA, PEC, provincia) si vedono sempre in italiano:
// de e fr servono solo a tenere complete le lingue.

const it = {
  tipo: { fisica: 'Persona fisica', giuridica: 'Persona giuridica' },
  elenco: {
    titolo: 'Clienti',
    nuovo: 'Nuovo cliente',
    cerca: 'Cerca un cliente',
    cercaSegnaposto: 'Nome o email…',
    chiediLex: 'Chiedi a Lex sui tuoi clienti',
    chiediLexTesto: 'Fatture, pratiche, udienze. Lex non legge le note interne.',
    tutti: 'Tutti · {n}',
    persone: 'Persone fisiche · {n}',
    societa: 'Persone giuridiche · {n}',
    limite: '{n} clienti su {totale} del piano',
    limiteAvviso: 'Ti restano {n} posti clienti.',
    limitePieno:
      'Hai raggiunto il limite di clienti del piano. Aggiungi posti dal sito, in Studio → Acquista.',
    pratiche: '{n} pratiche aperte',
    unaPratica: '1 pratica aperta',
    nessunaPratica: 'Nessuna pratica aperta',
    portale: 'Portale',
    vuotoTitolo: 'Nessun cliente',
    vuotoTesto: 'Crea il primo con «+» in alto.',
    vuotoCercaTitolo: 'Nessun cliente con queste parole',
    vuotoCercaTesto: "Prova con il nome, il cognome o l'email.",
  },
  lex: {
    titolo: 'Chiedi a Lex sui clienti',
    testo:
      'Lex conosce anagrafiche, pratiche, udienze e fatture dei tuoi clienti. Non legge le note interne.',
    campo: 'La tua domanda',
    segnaposto: 'Per esempio: chi ha fatture da incassare?',
    esempi: {
      fatture: 'Chi ha fatture da incassare?',
      udienze: "Chi ha un'udienza nei prossimi 15 giorni?",
      portale: 'Chi non ha ancora il portale?',
    },
    chiedi: 'Chiedi a Lex',
    pensa: 'Lex sta guardando i tuoi clienti…',
    risposta: 'Ho trovato {n} clienti.',
    rispostaUno: 'Ho trovato 1 cliente.',
    nessuno: 'Nessun cliente corrisponde alla domanda.',
    generico: 'Questi sono i clienti con pratiche aperte.',
    credito: 'Usa 1 credito.',
    altra: 'Altra domanda',
  },
  modulo: {
    titoloNuovo: 'Nuovo cliente',
    titoloModifica: 'Modifica cliente',
    tipo: 'Tipo di soggetto',
    anagrafica: 'Dati anagrafici',
    societa: 'Dati della società',
    rappresentante: 'Rappresentante legale (facoltativo)',
    contatti: 'Contatti',
    indirizzo: 'Indirizzo',
    portale: 'Portale clienti',
    note: 'Note iniziali',
    nome: 'Nome *',
    cognome: 'Cognome *',
    cf: 'Codice fiscale',
    avs: 'Numero AVS',
    avsEsempio: '756.1234.5678.97',
    dataNascita: 'Data di nascita',
    luogoNascita: 'Luogo di nascita',
    ragioneSociale: 'Ragione sociale *',
    piva: 'Partita IVA',
    uid: 'Numero UID',
    uidEsempio: 'CHE-123.456.789',
    formaGiuridica: 'Forma giuridica',
    formaGiuridicaEsempio: 'SA, Sagl, ditta individuale',
    ivaAttiva: "Assoggettata all'IVA",
    sedeLegale: 'Sede legale',
    rapprNome: 'Nome',
    rapprCognome: 'Cognome',
    rapprCf: 'Codice fiscale',
    rapprAvs: 'Numero AVS',
    rapprCarica: 'Carica',
    rapprCaricaEsempio: 'Amministratore unico',
    email: 'Email *',
    telefono: 'Telefono',
    pec: 'PEC',
    via: { fisica: 'Indirizzo di domicilio', giuridica: 'Sede operativa' },
    viaSegnaposto: 'Via e numero civico',
    cap: { IT: 'CAP', CH: 'NPA' },
    citta: { IT: 'Comune', CH: 'Località' },
    provincia: 'Provincia',
    cantone: 'Cantone',
    civico: 'Numero',
    paese: 'Paese',
    paeseTesto: 'Due lettere: IT, CH, DE…',
    scegliCantone: 'Scegli il Cantone',
    fatturazione: 'Fatturazione elettronica',
    sdi: 'Codice destinatario SDI',
    sdiTesto: '7 caratteri (6 per la Pubblica Amministrazione). Se non c’è, la fattura va alla PEC.',
    pecFatturazione: 'PEC per le fatture',
    portaleAttiva: "Attiva l'accesso al portale clienti",
    portaleTesto:
      'Il cliente entra nel suo portale con email e password: vede appuntamenti, documenti condivisi, fatture e messaggi.',
    password: 'Password iniziale *',
    passwordSegnaposto: 'Almeno 8 caratteri',
    genera: 'Genera',
    passwordNota:
      'Lexum non manda la password per email: comunicala tu al cliente (al telefono o di persona).',
    noteSegnaposto: 'Primo contatto, situazione generale…',
    crea: 'Crea cliente',
    salva: 'Salva le modifiche',
    limite:
      'Hai raggiunto il limite di {totale} clienti del piano. Aggiungi posti dal sito, in Studio → Acquista.',
  },
  errori: {
    nome: 'Scrivi il nome.',
    cognome: 'Scrivi il cognome.',
    ragioneSociale: 'Scrivi la ragione sociale.',
    email: "Scrivi l'email: serve per il portale.",
    emailNonValida: "L'email non è valida.",
    cf: 'Codice fiscale non valido.',
    piva: 'Partita IVA non valida (11 cifre).',
    provincia: 'Sigla di 2 lettere, per esempio MI.',
    avs: 'Numero AVS non valido (756.xxxx.xxxx.xx).',
    uid: 'Numero UID non valido (CHE-xxx.xxx.xxx).',
    cap: { IT: 'Il CAP ha 5 cifre.', CH: "L'NPA ha 4 cifre." },
    password: 'Scrivi la password iniziale per attivare il portale.',
    passwordCorta: 'La password deve avere almeno 8 caratteri.',
    data: 'Data non valida: scrivi gg.mm.aaaa.',
    sdi: 'Il codice SDI ha 6 o 7 caratteri, lettere e numeri.',
    pecFatturazione: 'La PEC non è valida.',
    paese: 'Il paese si scrive con 2 lettere, per esempio IT.',
  },
  scheda: {
    titolo: 'Cliente',
    torna: 'Clienti',
    nonCe: "Questo cliente non c'è più",
    altreAzioni: 'Altre azioni',
    schede: {
      panoramica: 'Panoramica',
      pratiche: 'Pratiche',
      documenti: 'Documenti',
      comunicazioni: 'Messaggi',
      note: 'Note',
      pagamenti: 'Pagamenti',
    },
    clienteDal: 'Cliente dal {data}',
    portaleAttivo: 'Portale attivo',
    portaleSpento: 'Senza portale',
    creato: 'Cliente creato.',
    creatoPortale: 'Cliente creato. Il portale è attivo: comunica tu la password al cliente.',
    numeri: {
      pratiche: 'Pratiche aperte',
      daIncassare: 'Da incassare',
      documenti: 'Documenti',
    },
    anagrafica: 'Anagrafica',
    modifica: 'Modifica',
    voci: {
      cf: 'Codice fiscale',
      avs: 'Numero AVS',
      nascita: 'Nascita',
      nascitaTesto: '{data}, {luogo}',
      piva: 'Partita IVA',
      uid: 'Numero UID',
      forma: 'Forma giuridica',
      iva: 'IVA',
      ivaSi: 'Assoggettata',
      ivaNo: 'Non assoggettata',
      sede: 'Sede legale',
      rappresentante: 'Rappresentante',
      email: 'Email',
      telefono: 'Telefono',
      pec: 'PEC',
      indirizzo: 'Indirizzo',
      noteIniziali: 'Note iniziali',
      sdi: 'Codice SDI',
      pecFatturazione: 'PEC fatture',
    },
    accesso: 'Accesso al portale',
    accessoAttivo: 'Attivo: il cliente entra con {email}',
    accessoSpento: 'Non attivo',
    prossimi: 'Prossimi appuntamenti',
    nessunAppuntamento: 'Nessun appuntamento in programma.',
    fissa: 'Fissa un appuntamento',
    pratiche: {
      titolo: 'Pratiche · {n}',
      nuova: 'Nuova pratica',
      vuoto: 'Nessuna pratica per questo cliente.',
    },
    documenti: {
      portaleTitolo: 'Nel portale del cliente',
      portaleTesto: 'Li vede anche il cliente. Quelli che carica lui compaiono qui.',
      condividi: 'Condividi',
      portaleVuoto: 'Nessun documento condiviso.',
      dalCliente: 'Dal cliente',
      dalloStudio: 'Dallo studio',
      togli: 'Togli {nome} dal portale',
      archivioTitolo: "Nell'archivio dello studio",
      archivioTesto: 'Li vede solo lo studio. Lex li usa nelle pratiche del cliente.',
      carica: 'Carica',
      collega: "Dall'archivio",
      archivioVuoto: 'Nessun documento in archivio per questo cliente.',
    },
    comunicazioni: {
      titolo: 'Conversazioni · {n}',
      nuova: 'Nuovo messaggio',
      vuoto: 'Nessuna conversazione. Scrivi al cliente: ti risponde dal suo portale.',
      senzaPortale: 'Il cliente non ha il portale: vedrà i messaggi quando lo attivi.',
      aperta: 'Aperta',
      chiusa: 'Chiusa',
      messaggi: '{n} messaggi',
      unMessaggio: '1 messaggio',
      nessunMessaggio: 'Nessun messaggio',
    },
    note: {
      avviso: 'Le vede solo lo studio: Lex non le legge.',
      aggiungi: 'Aggiungi nota',
      vuoto: 'Nessuna nota.',
      modificata: 'modificata',
      modifica: 'Modifica la nota',
      elimina: 'Elimina la nota',
    },
    pagamenti: {
      daIncassare: 'Da incassare',
      incassato: 'Incassato',
      nuova: 'Nuova fattura',
      vuoto: 'Nessuna fattura per questo cliente.',
    },
    azioni: {
      modifica: 'Modifica i dati',
      nuovaPratica: 'Nuova pratica',
      nuovaFattura: 'Nuova fattura',
      appuntamento: 'Fissa un appuntamento',
      messaggio: 'Scrivi al cliente',
      accesso: 'Accesso al portale',
      accessoTesto: 'Email per reimpostare la password, o una password nuova',
      elimina: 'Elimina cliente',
    },
  },
  fogli: {
    accesso: {
      titolo: 'Accesso al portale',
      testoAttivo: 'Il cliente entra nel portale con {email}.',
      testoSpento:
        'Il portale non è attivo. Imposta una password e comunicala al cliente: da quel momento può entrare.',
      email: "Manda l'email per reimpostare la password",
      emailTesto: 'Il cliente riceve un link e sceglie lui la password.',
      emailMandata: 'Email mandata a {email}.',
      password: 'Imposta una password',
      passwordTesto: 'La scegli tu e la comunichi al cliente.',
      genera: 'Genera (12 caratteri)',
      manuale: 'La scrivo io',
      campo: 'Nuova password',
      conferma: 'Imposta la password',
      fatto: 'Password impostata',
      unaVolta: 'La vedi solo adesso. Comunicala al cliente al telefono o di persona, non per email o chat.',
      chiudi: 'Ho preso nota',
      copia: 'Copia',
      copiata: 'Copiata',
    },
    elimina: {
      titolo: 'Eliminare {nome}?',
      testo:
        'Si cancellano per sempre anagrafica, pratiche, fatture, note, appuntamenti, documenti e messaggi del cliente. Non si può annullare.',
      scrivi: 'Per confermare scrivi il nome: {nome}',
      campo: 'Nome del cliente',
      conferma: 'Elimina per sempre',
    },
    nota: {
      nuova: 'Nuova nota',
      modifica: 'Modifica la nota',
      campo: 'Nota',
      segnaposto: 'Strategia, punti critici, promemoria…',
      salva: 'Salva',
    },
    ticket: {
      titolo: 'Nuovo messaggio al cliente',
      testo: 'Il cliente lo trova nel suo portale e ti risponde da lì.',
      oggetto: 'Oggetto *',
      oggettoSegnaposto: 'Per esempio: documenti mancanti',
      messaggio: 'Messaggio',
      apri: 'Manda',
    },
    condividi: {
      titolo: 'Condividi nel portale',
      testo: 'Il file compare nel portale di {nome}.',
      dalTelefono: 'Dal telefono',
      dalTelefonoTesto: 'Un file o una foto',
      dallArchivio: "Dall'archivio dello studio",
      vuoto: 'Nessun documento in archivio per questo cliente.',
    },
    collega: {
      titolo: "Collega dall'archivio",
      testo: 'Scegli i documenti dello studio da collegare a {nome}.',
      vuoto: 'Nessun altro documento in archivio.',
      collegato: 'Collegato',
      fine: 'Fine',
    },
  },
  messaggi: {
    titolo: 'Messaggi',
    con: 'Con {nome}',
    chiudi: 'Chiudi la conversazione',
    riapri: 'Riapri la conversazione',
    chiusa: 'Conversazione chiusa. Riaprila per scrivere.',
    segnaposto: 'Scrivi al cliente…',
    tu: 'Tu',
    vuoto: 'Nessun messaggio ancora.',
    nonCe: "Questa conversazione non c'è più",
  },
};

const de: Parziale<typeof it> = {
  tipo: { fisica: 'Natürliche Person', giuridica: 'Juristische Person' },
  elenco: {
    titolo: 'Mandanten',
    nuovo: 'Neuer Mandant',
    cerca: 'Mandanten suchen',
    cercaSegnaposto: 'Name oder E-Mail…',
    chiediLex: 'Lex zu Ihren Mandanten fragen',
    chiediLexTesto: 'Rechnungen, Dossiers, Verhandlungen. Lex liest die internen Notizen nicht.',
    tutti: 'Alle · {n}',
    persone: 'Natürliche Personen · {n}',
    societa: 'Juristische Personen · {n}',
    limite: '{n} von {totale} Mandanten des Abonnements',
    limiteAvviso: 'Ihnen verbleiben noch {n} Mandanten-Slots.',
    limitePieno:
      'Sie haben das Mandantenlimit Ihres Abonnements erreicht. Weitere Slots erhalten Sie auf der Website unter Kanzlei → Kaufen.',
    pratiche: '{n} offene Dossiers',
    unaPratica: '1 offenes Dossier',
    nessunaPratica: 'Kein offenes Dossier',
    portale: 'Portal',
    vuotoTitolo: 'Keine Mandanten',
    vuotoTesto: 'Erstellen Sie den ersten mit «+» oben.',
    vuotoCercaTitolo: 'Kein Mandant mit diesen Wörtern',
    vuotoCercaTesto: 'Versuchen Sie es mit Vorname, Nachname oder E-Mail.',
  },
  lex: {
    titolo: 'Lex zu den Mandanten fragen',
    testo:
      'Lex kennt Personalien, Dossiers, Verhandlungen und Rechnungen Ihrer Mandanten. Die internen Notizen liest Lex nicht.',
    campo: 'Ihre Frage',
    segnaposto: 'Zum Beispiel: Wer hat offene Rechnungen?',
    esempi: {
      fatture: 'Wer hat offene Rechnungen?',
      udienze: 'Wer hat in den nächsten 15 Tagen eine Verhandlung?',
      portale: 'Wer hat noch kein Portal?',
    },
    chiedi: 'Lex fragen',
    pensa: 'Lex sieht sich Ihre Mandanten an…',
    risposta: 'Ich habe {n} Mandanten gefunden.',
    rispostaUno: 'Ich habe 1 Mandanten gefunden.',
    nessuno: 'Kein Mandant passt zur Frage.',
    generico: 'Das sind die Mandanten mit offenen Dossiers.',
    credito: 'Verwendet 1 Guthaben.',
    altra: 'Andere Frage',
  },
  modulo: {
    titoloNuovo: 'Neuer Mandant',
    titoloModifica: 'Mandant bearbeiten',
    tipo: 'Art der Person',
    anagrafica: 'Personalien',
    societa: 'Firmendaten',
    rappresentante: 'Gesetzlicher Vertreter (optional)',
    contatti: 'Kontakt',
    indirizzo: 'Adresse',
    portale: 'Mandantenportal',
    note: 'Erste Notizen',
    nome: 'Vorname *',
    cognome: 'Nachname *',
    cf: 'Steuernummer (IT)',
    avs: 'AHV-Nummer',
    avsEsempio: '756.1234.5678.97',
    dataNascita: 'Geburtsdatum',
    luogoNascita: 'Geburtsort',
    ragioneSociale: 'Firmenname *',
    piva: 'MWST-Nummer (IT)',
    uid: 'UID-Nummer',
    uidEsempio: 'CHE-123.456.789',
    formaGiuridica: 'Rechtsform',
    formaGiuridicaEsempio: 'AG, GmbH, Einzelunternehmen',
    ivaAttiva: 'Mehrwertsteuerpflichtig',
    sedeLegale: 'Sitz',
    rapprNome: 'Vorname',
    rapprCognome: 'Nachname',
    rapprCf: 'Steuernummer (IT)',
    rapprAvs: 'AHV-Nummer',
    rapprCarica: 'Funktion',
    rapprCaricaEsempio: 'Geschäftsführer',
    email: 'E-Mail *',
    telefono: 'Telefon',
    pec: 'PEC (IT)',
    via: { fisica: 'Wohnadresse', giuridica: 'Geschäftsadresse' },
    viaSegnaposto: 'Strasse und Hausnummer',
    cap: { IT: 'PLZ', CH: 'PLZ' },
    citta: { IT: 'Gemeinde', CH: 'Ort' },
    provincia: 'Provinz',
    cantone: 'Kanton',
    civico: 'Nummer',
    paese: 'Land',
    paeseTesto: 'Zwei Buchstaben: CH, DE, IT…',
    scegliCantone: 'Kanton wählen',
    fatturazione: 'Elektronische Rechnung (IT)',
    sdi: 'SDI-Empfängercode (IT)',
    sdiTesto: '7 Zeichen (6 für die öffentliche Verwaltung).',
    pecFatturazione: 'PEC für Rechnungen (IT)',
    portaleAttiva: 'Zugang zum Mandantenportal aktivieren',
    portaleTesto:
      'Der Mandant meldet sich mit E-Mail und Passwort in seinem Portal an: Er sieht Termine, geteilte Dokumente, Rechnungen und Nachrichten.',
    password: 'Initiales Passwort *',
    passwordSegnaposto: 'Mindestens 8 Zeichen',
    genera: 'Erzeugen',
    passwordNota:
      'Lexum versendet das Passwort nie per E-Mail: Teilen Sie es dem Mandanten selbst mit (am Telefon oder persönlich).',
    noteSegnaposto: 'Erstkontakt, allgemeine Situation…',
    crea: 'Mandant erstellen',
    salva: 'Änderungen speichern',
    limite:
      'Sie haben das Limit von {totale} Mandanten Ihres Abonnements erreicht. Weitere Slots erhalten Sie auf der Website unter Kanzlei → Kaufen.',
  },
  errori: {
    nome: 'Geben Sie den Vornamen ein.',
    cognome: 'Geben Sie den Nachnamen ein.',
    ragioneSociale: 'Geben Sie den Firmennamen ein.',
    email: 'Geben Sie die E-Mail ein: Sie wird für das Portal benötigt.',
    emailNonValida: 'Die E-Mail ist ungültig.',
    cf: 'Ungültige Steuernummer.',
    piva: 'Ungültige MWST-Nummer (11 Ziffern).',
    provincia: 'Kürzel mit 2 Buchstaben, zum Beispiel MI.',
    avs: 'Ungültige AHV-Nummer (756.xxxx.xxxx.xx).',
    uid: 'Ungültige UID-Nummer (CHE-xxx.xxx.xxx).',
    cap: { IT: 'Die PLZ hat 5 Ziffern.', CH: 'Die PLZ hat 4 Ziffern.' },
    password: 'Geben Sie das initiale Passwort ein, um das Portal zu aktivieren.',
    passwordCorta: 'Das Passwort muss mindestens 8 Zeichen haben.',
    data: 'Ungültiges Datum: Schreiben Sie TT.MM.JJJJ.',
    sdi: 'Der SDI-Code hat 6 oder 7 Zeichen, Buchstaben und Ziffern.',
    pecFatturazione: 'Die PEC ist ungültig.',
    paese: 'Das Land wird mit 2 Buchstaben geschrieben, zum Beispiel CH.',
  },
  scheda: {
    titolo: 'Mandant',
    torna: 'Mandanten',
    nonCe: 'Diesen Mandanten gibt es nicht mehr',
    altreAzioni: 'Weitere Aktionen',
    schede: {
      panoramica: 'Übersicht',
      pratiche: 'Dossiers',
      documenti: 'Dokumente',
      comunicazioni: 'Nachrichten',
      note: 'Notizen',
      pagamenti: 'Zahlungen',
    },
    clienteDal: 'Mandant seit {data}',
    portaleAttivo: 'Portal aktiv',
    portaleSpento: 'Ohne Portal',
    creato: 'Mandant erstellt.',
    creatoPortale:
      'Mandant erstellt. Das Portal ist aktiv: Teilen Sie dem Mandanten das Passwort selbst mit.',
    numeri: {
      pratiche: 'Offene Dossiers',
      daIncassare: 'Ausstehend',
      documenti: 'Dokumente',
    },
    anagrafica: 'Stammdaten',
    modifica: 'Bearbeiten',
    voci: {
      cf: 'Steuernummer (IT)',
      avs: 'AHV-Nummer',
      nascita: 'Geburt',
      nascitaTesto: '{data}, {luogo}',
      piva: 'MWST-Nummer (IT)',
      uid: 'UID-Nummer',
      forma: 'Rechtsform',
      iva: 'MWST',
      ivaSi: 'Steuerpflichtig',
      ivaNo: 'Nicht steuerpflichtig',
      sede: 'Sitz',
      rappresentante: 'Vertreter',
      email: 'E-Mail',
      telefono: 'Telefon',
      pec: 'PEC (IT)',
      indirizzo: 'Adresse',
      noteIniziali: 'Erste Notizen',
      sdi: 'SDI-Code (IT)',
      pecFatturazione: 'PEC Rechnungen (IT)',
    },
    accesso: 'Zugang zum Portal',
    accessoAttivo: 'Aktiv: Der Mandant meldet sich mit {email} an',
    accessoSpento: 'Nicht aktiv',
    prossimi: 'Nächste Termine',
    nessunAppuntamento: 'Keine Termine geplant.',
    fissa: 'Termin vereinbaren',
    pratiche: {
      titolo: 'Dossiers · {n}',
      nuova: 'Neues Dossier',
      vuoto: 'Keine Dossiers für diesen Mandanten.',
    },
    documenti: {
      portaleTitolo: 'Im Mandantenportal',
      portaleTesto: 'Der Mandant sieht sie auch. Was er selbst hochlädt, erscheint hier.',
      condividi: 'Teilen',
      portaleVuoto: 'Keine geteilten Dokumente.',
      dalCliente: 'Vom Mandanten',
      dalloStudio: 'Von der Kanzlei',
      togli: '{nome} aus dem Portal entfernen',
      archivioTitolo: 'Im Archiv der Kanzlei',
      archivioTesto: 'Nur die Kanzlei sieht sie. Lex verwendet sie in den Dossiers des Mandanten.',
      carica: 'Hochladen',
      collega: 'Aus dem Archiv',
      archivioVuoto: 'Keine Dokumente im Archiv für diesen Mandanten.',
    },
    comunicazioni: {
      titolo: 'Gespräche · {n}',
      nuova: 'Neue Nachricht',
      vuoto: 'Keine Gespräche. Schreiben Sie dem Mandanten: Er antwortet aus seinem Portal.',
      senzaPortale: 'Der Mandant hat kein Portal: Er sieht die Nachrichten, sobald Sie es aktivieren.',
      aperta: 'Offen',
      chiusa: 'Geschlossen',
      messaggi: '{n} Nachrichten',
      unMessaggio: '1 Nachricht',
      nessunMessaggio: 'Keine Nachricht',
    },
    note: {
      avviso: 'Nur die Kanzlei sieht sie: Lex liest sie nicht.',
      aggiungi: 'Notiz hinzufügen',
      vuoto: 'Keine Notizen.',
      modificata: 'bearbeitet',
      modifica: 'Notiz bearbeiten',
      elimina: 'Notiz löschen',
    },
    pagamenti: {
      daIncassare: 'Ausstehend',
      incassato: 'Eingegangen',
      nuova: 'Neue Rechnung',
      vuoto: 'Keine Rechnungen für diesen Mandanten.',
    },
    azioni: {
      modifica: 'Daten bearbeiten',
      nuovaPratica: 'Neues Dossier',
      nuovaFattura: 'Neue Rechnung',
      appuntamento: 'Termin vereinbaren',
      messaggio: 'Dem Mandanten schreiben',
      accesso: 'Zugang zum Portal',
      accessoTesto: 'E-Mail zum Zurücksetzen des Passworts oder ein neues Passwort',
      elimina: 'Mandant löschen',
    },
  },
  fogli: {
    accesso: {
      titolo: 'Zugang zum Portal',
      testoAttivo: 'Der Mandant meldet sich mit {email} im Portal an.',
      testoSpento:
        'Das Portal ist nicht aktiv. Legen Sie ein Passwort fest und teilen Sie es dem Mandanten mit: Ab dann kann er sich anmelden.',
      email: 'E-Mail zum Passwort-Reset senden',
      emailTesto: 'Der Mandant erhält einen Link und wählt das Passwort selbst.',
      emailMandata: 'E-Mail an {email} gesendet.',
      password: 'Passwort festlegen',
      passwordTesto: 'Sie wählen es und teilen es dem Mandanten mit.',
      genera: 'Erzeugen (12 Zeichen)',
      manuale: 'Selbst eingeben',
      campo: 'Neues Passwort',
      conferma: 'Passwort festlegen',
      fatto: 'Passwort festgelegt',
      unaVolta:
        'Sie sehen es nur jetzt. Teilen Sie es dem Mandanten am Telefon oder persönlich mit, nicht per E-Mail oder Chat.',
      chiudi: 'Notiert',
      copia: 'Kopieren',
      copiata: 'Kopiert',
    },
    elimina: {
      titolo: '{nome} löschen?',
      testo:
        'Personalien, Dossiers, Rechnungen, Notizen, Termine, Dokumente und Nachrichten des Mandanten werden endgültig gelöscht. Das lässt sich nicht rückgängig machen.',
      scrivi: 'Zur Bestätigung geben Sie den Namen ein: {nome}',
      campo: 'Name des Mandanten',
      conferma: 'Endgültig löschen',
    },
    nota: {
      nuova: 'Neue Notiz',
      modifica: 'Notiz bearbeiten',
      campo: 'Notiz',
      segnaposto: 'Strategie, kritische Punkte, interne Erinnerungen…',
      salva: 'Speichern',
    },
    ticket: {
      titolo: 'Neue Nachricht an den Mandanten',
      testo: 'Der Mandant findet sie in seinem Portal und antwortet von dort.',
      oggetto: 'Betreff *',
      oggettoSegnaposto: 'Zum Beispiel: fehlende Dokumente',
      messaggio: 'Nachricht',
      apri: 'Senden',
    },
    condividi: {
      titolo: 'Im Portal teilen',
      testo: 'Die Datei erscheint im Portal von {nome}.',
      dalTelefono: 'Vom Telefon',
      dalTelefonoTesto: 'Eine Datei oder ein Foto',
      dallArchivio: 'Aus dem Archiv der Kanzlei',
      vuoto: 'Keine Dokumente im Archiv für diesen Mandanten.',
    },
    collega: {
      titolo: 'Aus dem Archiv verknüpfen',
      testo: 'Wählen Sie die Dokumente der Kanzlei, die Sie mit {nome} verknüpfen möchten.',
      vuoto: 'Keine weiteren Dokumente im Archiv.',
      collegato: 'Verknüpft',
      fine: 'Fertig',
    },
  },
  messaggi: {
    titolo: 'Nachrichten',
    con: 'Mit {nome}',
    chiudi: 'Gespräch schliessen',
    riapri: 'Gespräch wieder öffnen',
    chiusa: 'Gespräch geschlossen. Öffnen Sie es wieder, um zu schreiben.',
    segnaposto: 'Dem Mandanten schreiben…',
    tu: 'Sie',
    vuoto: 'Noch keine Nachrichten.',
    nonCe: 'Dieses Gespräch gibt es nicht mehr',
  },
};

const fr: Parziale<typeof it> = {
  tipo: { fisica: 'Personne physique', giuridica: 'Personne morale' },
  elenco: {
    titolo: 'Clients',
    nuovo: 'Nouveau client',
    cerca: 'Rechercher un client',
    cercaSegnaposto: 'Nom ou e-mail…',
    chiediLex: 'Interroger Lex sur vos clients',
    chiediLexTesto: 'Factures, dossiers, audiences. Lex ne lit pas les notes internes.',
    tutti: 'Tous · {n}',
    persone: 'Personnes physiques · {n}',
    societa: 'Personnes morales · {n}',
    limite: '{n} clients sur {totale} de l’abonnement',
    limiteAvviso: 'Il vous reste {n} emplacements clients.',
    limitePieno:
      'Vous avez atteint la limite de clients de votre abonnement. Ajoutez des emplacements sur le site, sous Étude → Acheter.',
    pratiche: '{n} dossiers ouverts',
    unaPratica: '1 dossier ouvert',
    nessunaPratica: 'Aucun dossier ouvert',
    portale: 'Portail',
    vuotoTitolo: 'Aucun client',
    vuotoTesto: 'Créez le premier avec « + » en haut.',
    vuotoCercaTitolo: 'Aucun client avec ces mots',
    vuotoCercaTesto: 'Essayez avec le prénom, le nom ou l’e-mail.',
  },
  lex: {
    titolo: 'Interroger Lex sur les clients',
    testo:
      'Lex connaît les données, dossiers, audiences et factures de vos clients. Il ne lit pas les notes internes.',
    campo: 'Votre question',
    segnaposto: 'Par exemple : qui a des factures à encaisser ?',
    esempi: {
      fatture: 'Qui a des factures à encaisser ?',
      udienze: 'Qui a une audience dans les 15 prochains jours ?',
      portale: 'Qui n’a pas encore le portail ?',
    },
    chiedi: 'Demander à Lex',
    pensa: 'Lex examine vos clients…',
    risposta: 'J’ai trouvé {n} clients.',
    rispostaUno: 'J’ai trouvé 1 client.',
    nessuno: 'Aucun client ne correspond à la question.',
    generico: 'Voici les clients avec des dossiers ouverts.',
    credito: 'Utilise 1 crédit.',
    altra: 'Autre question',
  },
  modulo: {
    titoloNuovo: 'Nouveau client',
    titoloModifica: 'Modifier le client',
    tipo: 'Type de personne',
    anagrafica: 'Données personnelles',
    societa: 'Données de la société',
    rappresentante: 'Représentant légal (facultatif)',
    contatti: 'Contacts',
    indirizzo: 'Adresse',
    portale: 'Portail clients',
    note: 'Notes initiales',
    nome: 'Prénom *',
    cognome: 'Nom *',
    cf: 'Code fiscal (IT)',
    avs: 'Numéro AVS',
    avsEsempio: '756.1234.5678.97',
    dataNascita: 'Date de naissance',
    luogoNascita: 'Lieu de naissance',
    ragioneSociale: 'Raison sociale *',
    piva: 'Numéro de TVA (IT)',
    uid: 'Numéro IDE',
    uidEsempio: 'CHE-123.456.789',
    formaGiuridica: 'Forme juridique',
    formaGiuridicaEsempio: 'SA, Sàrl, entreprise individuelle',
    ivaAttiva: 'Assujettie à la TVA',
    sedeLegale: 'Siège social',
    rapprNome: 'Prénom',
    rapprCognome: 'Nom',
    rapprCf: 'Code fiscal (IT)',
    rapprAvs: 'Numéro AVS',
    rapprCarica: 'Fonction',
    rapprCaricaEsempio: 'Administrateur unique',
    email: 'E-mail *',
    telefono: 'Téléphone',
    pec: 'PEC (IT)',
    via: { fisica: 'Adresse de domicile', giuridica: 'Adresse d’exploitation' },
    viaSegnaposto: 'Rue et numéro',
    cap: { IT: 'NPA', CH: 'NPA' },
    citta: { IT: 'Commune', CH: 'Localité' },
    provincia: 'Province',
    cantone: 'Canton',
    civico: 'Numéro',
    paese: 'Pays',
    paeseTesto: 'Deux lettres : CH, FR, IT…',
    scegliCantone: 'Choisir le canton',
    fatturazione: 'Facture électronique (IT)',
    sdi: 'Code destinataire SDI (IT)',
    sdiTesto: '7 caractères (6 pour l’administration publique).',
    pecFatturazione: 'PEC pour les factures (IT)',
    portaleAttiva: 'Activer l’accès au portail clients',
    portaleTesto:
      'Le client se connecte à son portail avec son e-mail et son mot de passe : il voit rendez-vous, documents partagés, factures et messages.',
    password: 'Mot de passe initial *',
    passwordSegnaposto: 'Au moins 8 caractères',
    genera: 'Générer',
    passwordNota:
      'Lexum n’envoie jamais le mot de passe par e-mail : communiquez-le vous-même au client (au téléphone ou en personne).',
    noteSegnaposto: 'Premier contact, situation générale…',
    crea: 'Créer le client',
    salva: 'Enregistrer les modifications',
    limite:
      'Vous avez atteint la limite de {totale} clients de votre abonnement. Ajoutez des emplacements sur le site, sous Étude → Acheter.',
  },
  errori: {
    nome: 'Saisissez le prénom.',
    cognome: 'Saisissez le nom.',
    ragioneSociale: 'Saisissez la raison sociale.',
    email: 'Saisissez l’e-mail : il sert pour le portail.',
    emailNonValida: 'L’e-mail n’est pas valide.',
    cf: 'Code fiscal non valide.',
    piva: 'Numéro de TVA non valide (11 chiffres).',
    provincia: 'Sigle de 2 lettres, par exemple MI.',
    avs: 'Numéro AVS non valide (756.xxxx.xxxx.xx).',
    uid: 'Numéro IDE non valide (CHE-xxx.xxx.xxx).',
    cap: { IT: 'Le code postal a 5 chiffres.', CH: 'Le NPA a 4 chiffres.' },
    password: 'Saisissez le mot de passe initial pour activer le portail.',
    passwordCorta: 'Le mot de passe doit comporter au moins 8 caractères.',
    data: 'Date non valide : écrivez jj.mm.aaaa.',
    sdi: 'Le code SDI a 6 ou 7 caractères, lettres et chiffres.',
    pecFatturazione: 'La PEC n’est pas valide.',
    paese: 'Le pays s’écrit avec 2 lettres, par exemple CH.',
  },
  scheda: {
    titolo: 'Client',
    torna: 'Clients',
    nonCe: 'Ce client n’existe plus',
    altreAzioni: 'Autres actions',
    schede: {
      panoramica: 'Aperçu',
      pratiche: 'Dossiers',
      documenti: 'Documents',
      comunicazioni: 'Messages',
      note: 'Notes',
      pagamenti: 'Paiements',
    },
    clienteDal: 'Client depuis le {data}',
    portaleAttivo: 'Portail actif',
    portaleSpento: 'Sans portail',
    creato: 'Client créé.',
    creatoPortale: 'Client créé. Le portail est actif : communiquez vous-même le mot de passe au client.',
    numeri: {
      pratiche: 'Dossiers ouverts',
      daIncassare: 'À encaisser',
      documenti: 'Documents',
    },
    anagrafica: 'Données personnelles',
    modifica: 'Modifier',
    voci: {
      cf: 'Code fiscal (IT)',
      avs: 'Numéro AVS',
      nascita: 'Naissance',
      nascitaTesto: '{data}, {luogo}',
      piva: 'Numéro de TVA (IT)',
      uid: 'Numéro IDE',
      forma: 'Forme juridique',
      iva: 'TVA',
      ivaSi: 'Assujettie',
      ivaNo: 'Non assujettie',
      sede: 'Siège social',
      rappresentante: 'Représentant',
      email: 'E-mail',
      telefono: 'Téléphone',
      pec: 'PEC (IT)',
      indirizzo: 'Adresse',
      noteIniziali: 'Notes initiales',
      sdi: 'Code SDI (IT)',
      pecFatturazione: 'PEC factures (IT)',
    },
    accesso: 'Accès au portail',
    accessoAttivo: 'Actif : le client se connecte avec {email}',
    accessoSpento: 'Inactif',
    prossimi: 'Prochains rendez-vous',
    nessunAppuntamento: 'Aucun rendez-vous prévu.',
    fissa: 'Fixer un rendez-vous',
    pratiche: {
      titolo: 'Dossiers · {n}',
      nuova: 'Nouveau dossier',
      vuoto: 'Aucun dossier pour ce client.',
    },
    documenti: {
      portaleTitolo: 'Dans le portail du client',
      portaleTesto: 'Le client les voit aussi. Ceux qu’il téléverse lui-même apparaissent ici.',
      condividi: 'Partager',
      portaleVuoto: 'Aucun document partagé.',
      dalCliente: 'Du client',
      dalloStudio: 'De l’étude',
      togli: 'Retirer {nome} du portail',
      archivioTitolo: 'Dans les archives de l’étude',
      archivioTesto: 'Seule l’étude les voit. Lex les utilise dans les dossiers du client.',
      carica: 'Téléverser',
      collega: 'Des archives',
      archivioVuoto: 'Aucun document dans les archives pour ce client.',
    },
    comunicazioni: {
      titolo: 'Conversations · {n}',
      nuova: 'Nouveau message',
      vuoto: 'Aucune conversation. Écrivez au client : il vous répond depuis son portail.',
      senzaPortale: 'Le client n’a pas de portail : il verra les messages quand vous l’activerez.',
      aperta: 'Ouverte',
      chiusa: 'Fermée',
      messaggi: '{n} messages',
      unMessaggio: '1 message',
      nessunMessaggio: 'Aucun message',
    },
    note: {
      avviso: 'Seule l’étude les voit : Lex ne les lit pas.',
      aggiungi: 'Ajouter une note',
      vuoto: 'Aucune note.',
      modificata: 'modifiée',
      modifica: 'Modifier la note',
      elimina: 'Supprimer la note',
    },
    pagamenti: {
      daIncassare: 'À encaisser',
      incassato: 'Encaissé',
      nuova: 'Nouvelle facture',
      vuoto: 'Aucune facture pour ce client.',
    },
    azioni: {
      modifica: 'Modifier les données',
      nuovaPratica: 'Nouveau dossier',
      nuovaFattura: 'Nouvelle facture',
      appuntamento: 'Fixer un rendez-vous',
      messaggio: 'Écrire au client',
      accesso: 'Accès au portail',
      accessoTesto: 'E-mail pour réinitialiser le mot de passe, ou un nouveau mot de passe',
      elimina: 'Supprimer le client',
    },
  },
  fogli: {
    accesso: {
      titolo: 'Accès au portail',
      testoAttivo: 'Le client se connecte au portail avec {email}.',
      testoSpento:
        'Le portail n’est pas actif. Définissez un mot de passe et communiquez-le au client : dès lors, il peut se connecter.',
      email: 'Envoyer l’e-mail de réinitialisation',
      emailTesto: 'Le client reçoit un lien et choisit lui-même le mot de passe.',
      emailMandata: 'E-mail envoyé à {email}.',
      password: 'Définir un mot de passe',
      passwordTesto: 'Vous le choisissez et le communiquez au client.',
      genera: 'Générer (12 caractères)',
      manuale: 'Je le saisis',
      campo: 'Nouveau mot de passe',
      conferma: 'Définir le mot de passe',
      fatto: 'Mot de passe défini',
      unaVolta:
        'Vous ne le voyez que maintenant. Communiquez-le au client au téléphone ou en personne, pas par e-mail ou chat.',
      chiudi: 'C’est noté',
      copia: 'Copier',
      copiata: 'Copié',
    },
    elimina: {
      titolo: 'Supprimer {nome} ?',
      testo:
        'Les données, dossiers, factures, notes, rendez-vous, documents et messages du client sont supprimés définitivement. C’est irréversible.',
      scrivi: 'Pour confirmer, saisissez le nom : {nome}',
      campo: 'Nom du client',
      conferma: 'Supprimer définitivement',
    },
    nota: {
      nuova: 'Nouvelle note',
      modifica: 'Modifier la note',
      campo: 'Note',
      segnaposto: 'Stratégie, points critiques, rappels internes…',
      salva: 'Enregistrer',
    },
    ticket: {
      titolo: 'Nouveau message au client',
      testo: 'Le client le trouve dans son portail et vous répond depuis là.',
      oggetto: 'Objet *',
      oggettoSegnaposto: 'Par exemple : documents manquants',
      messaggio: 'Message',
      apri: 'Envoyer',
    },
    condividi: {
      titolo: 'Partager dans le portail',
      testo: 'Le fichier apparaît dans le portail de {nome}.',
      dalTelefono: 'Depuis le téléphone',
      dalTelefonoTesto: 'Un fichier ou une photo',
      dallArchivio: 'Des archives de l’étude',
      vuoto: 'Aucun document dans les archives pour ce client.',
    },
    collega: {
      titolo: 'Rattacher depuis les archives',
      testo: 'Choisissez les documents de l’étude à rattacher à {nome}.',
      vuoto: 'Aucun autre document dans les archives.',
      collegato: 'Rattaché',
      fine: 'Terminé',
    },
  },
  messaggi: {
    titolo: 'Messages',
    con: 'Avec {nome}',
    chiudi: 'Fermer la conversation',
    riapri: 'Rouvrir la conversation',
    chiusa: 'Conversation fermée. Rouvrez-la pour écrire.',
    segnaposto: 'Écrire au client…',
    tu: 'Vous',
    vuoto: 'Pas encore de messages.',
    nonCe: 'Cette conversation n’existe plus',
  },
};

export const clienti = { it, de, fr };
