import type { Parziale } from '../tipi';

// Sezione «dashboard»: la Dashboard dei professionisti, come le pagine «Dashboard» dei siti.
// Avvocati (IT e CH): agenda di oggi e dei prossimi 7 giorni, fatture, messaggi, pratiche da seguire.
// Commercialisti (IT) e fiduciari (CH): il quadro dello studio, con mandati e scadenze.
// Tedesco e francese vengono dal sito svizzero (public/locales/*/avv_dashboard.json e fid_dashboard.json);
// le frasi del commercialista, che c'è solo in Italia, sono tradotte solo per completezza.

const it = {
  titolo: 'Dashboard',
  orario: { notte: 'Buonanotte', mattino: 'Buongiorno', pomeriggio: 'Buon pomeriggio', sera: 'Buonasera' },
  saluto: '{saluto}, {nome}.',
  sommario: {
    vuoto:
      'Niente in calendario per oggi. Approfittane per aggiornare le pratiche o organizzare le ricerche.',
    oggi: 'Oggi hai {parti}.',
    udienzeUno: '1 udienza',
    udienze: '{n} udienze',
    terminiUno: '1 termine',
    termini: '{n} termini',
    appuntamentiUno: '1 appuntamento',
    appuntamenti: '{n} appuntamenti',
    fattureUno: '1 fattura in attesa.',
    fatture: '{n} fatture in attesa.',
    messaggiUno: '1 messaggio nuovo.',
    messaggi: '{n} messaggi nuovi.',
  },
  periodo: {
    titolo: 'Periodo',
    testo: 'Vale per le pratiche chiuse e per l’incassato. Il resto della Dashboard guarda sempre a oggi.',
    meseCorrente: 'Questo mese',
    meseScorso: 'Mese scorso',
    ultimi90: 'Ultimi 90 giorni',
    personalizzato: 'Personalizzato',
    da: 'Da',
    a: 'A',
    applica: 'Applica',
    ordine: 'La data d’inizio deve venire prima di quella di fine.',
  },
  prova: {
    titolo: 'La tua prova gratuita è scaduta',
    testo: 'Scegli un piano per continuare a lavorare con le tue pratiche, clienti e documenti.',
    dopo: 'Dopo',
    piani: 'Vedi i piani',
  },
  contatori: {
    clienti: 'Clienti',
    clientiSotto: 'Totale',
    aperte: 'Pratiche aperte',
    aperteSotto: 'Adesso',
    chiuse: 'Pratiche chiuse',
  },
  vediTutti: 'Vedi tutti',
  oggi: { titolo: 'Oggi', vuoto: 'Nessun impegno oggi.' },
  fatturazione: {
    titolo: 'Fatturazione',
    incassato: 'Incassato',
    daIncassare: 'Da incassare',
    totaleDebito: 'Totale debito attivo',
    fattura: 'Fattura {numero}',
    vuoto: 'Nessuna fattura in attesa.',
  },
  settimana: { titolo: 'Prossimi 7 giorni', vuoto: 'Nessun impegno nei prossimi 7 giorni.' },
  messaggi: {
    titolo: 'Messaggi non letti',
    senzaOggetto: 'Senza oggetto',
    vuoto: 'Nessun messaggio in attesa.',
  },
  attenzione: {
    titolo: 'Pratiche che richiedono attenzione',
    vuoto: 'Nessuna pratica con scadenza imminente.',
    udienza: 'Udienza del {data}',
  },
  badge: { fa: '{n}gg fa', oggi: 'Oggi', fra: 'Fra {n}gg' },
  commercialista: { etichetta: 'Commercialista', sottotitolo: 'Il quadro del tuo studio' },
  fiduciario: {
    etichetta: 'Studio fiduciario',
    titolo: 'Quadro generale',
    titoloNome: 'Quadro generale, {nome}',
    sottotitoloUno: 'Anno {anno} · 1 cliente',
    sottotitolo: 'Anno {anno} · {n} clienti',
  },
  kpi: {
    clienti: 'Clienti',
    mandati: 'Mandati attivi',
    fatturatoAnno: 'Fatturato anno',
    incassatoAnno: 'Incassato anno',
    fatturato: 'Fatturato {anno}',
    daIncassare: 'Da incassare',
  },
  fattureScadute: {
    uno: '1 fattura scaduta da incassare',
    molte: '{n} fatture scadute da incassare',
    gestisci: 'Gestisci',
  },
  scadenze: {
    titoloFiscali: 'Prossime scadenze fiscali',
    titolo: 'Prossime scadenze',
    banco: 'Banco di lavoro',
    vuotoFiscali:
      'Nessuna scadenza aperta. Sul sito apri un mandato con l’anno di riferimento e genera lo scadenzario.',
    vuoto: 'Nessuna scadenza in arrivo.',
    oggi: 'oggi',
    fraUno: 'tra 1 g',
    fra: 'tra {n} gg',
    scadutaDa: 'scaduta da {n} gg',
    scaduteUno: '1 scadenza scaduta',
    scadute: '{n} scadenze scadute',
    sulSito: 'Mandati e scadenze si gestiscono sul sito, nel Banco di lavoro.',
  },
  tipiScadenza: { iva: 'IVA', lipe: 'LIPE', dichiarativo: 'Dichiarativo', acconto: 'Acconti', imu: 'IMU' },
  appuntamenti: {
    titoloSettimana: 'Prossimi appuntamenti (7 giorni)',
    titolo: 'Prossimi appuntamenti',
    vuoto: 'Nessun appuntamento in programma.',
    calendario: 'Calendario',
    studio: 'studio',
  },
  mesi: { titolo: 'Studio: fatturazione ultimi 6 mesi', vai: 'Fatturazione' },
  annoStudio: {
    titolo: 'Studio: fatturazione {anno}',
    fatturato: 'Fatturato',
    incassato: 'Incassato',
    daIncassare: 'Da incassare',
    scaduto: 'Scaduto',
    nota: 'Fatture emesse dallo studio ai clienti (i ricavi dello studio). Niente a che vedere con i conti economici dei singoli clienti.',
  },
  conti: {
    titolo: 'Conto economico per cliente {anno}',
    nota: 'Ogni cliente è a sé: non si somma.',
    entrate: 'Entrate',
    costi: 'Costi',
    stipendi: 'Stipendi',
    saldo: 'Saldo',
  },
  apriSito: 'Apri sul sito',
  altri: {
    titolo: 'La tua Dashboard è sul sito',
    testo: 'Nell’app la Dashboard c’è per avvocati, commercialisti e fiduciari.',
  },
};

const de: Parziale<typeof it> = {
  titolo: 'Dashboard',
  orario: { notte: 'Gute Nacht', mattino: 'Guten Morgen', pomeriggio: 'Guten Tag', sera: 'Guten Abend' },
  saluto: '{saluto}, {nome}.',
  sommario: {
    vuoto:
      'Heute steht nichts im Kalender. Nutzen Sie die Zeit, um Ihre Dossiers zu aktualisieren oder Ihre Recherchen zu organisieren.',
    oggi: 'Heute haben Sie {parti}.',
    udienzeUno: '1 Verhandlung',
    udienze: '{n} Verhandlungen',
    terminiUno: '1 Frist',
    termini: '{n} Fristen',
    appuntamentiUno: '1 Termin',
    appuntamenti: '{n} Termine',
    fattureUno: '1 offene Rechnung.',
    fatture: '{n} offene Rechnungen.',
    messaggiUno: '1 neue Nachricht.',
    messaggi: '{n} neue Nachrichten.',
  },
  periodo: {
    titolo: 'Zeitraum',
    testo:
      'Gilt für abgeschlossene Dossiers und Einnahmen. Der Rest der Dashboard zeigt immer den heutigen Stand.',
    meseCorrente: 'Dieser Monat',
    meseScorso: 'Letzter Monat',
    ultimi90: 'Letzte 90 Tage',
    personalizzato: 'Benutzerdefiniert',
    da: 'Von',
    a: 'Bis',
    applica: 'Anwenden',
    ordine: 'Das Anfangsdatum muss vor dem Enddatum liegen.',
  },
  prova: {
    titolo: 'Ihre kostenlose Testphase ist abgelaufen',
    testo: 'Wählen Sie einen Plan, um weiterhin mit Ihren Dossiers, Mandanten und Dokumenten zu arbeiten.',
    dopo: 'Später',
    piani: 'Pläne ansehen',
  },
  contatori: {
    clienti: 'Mandanten',
    clientiSotto: 'Gesamt',
    aperte: 'Offene Dossiers',
    aperteSotto: 'Jetzt',
    chiuse: 'Abgeschlossene Dossiers',
  },
  vediTutti: 'Alle anzeigen',
  oggi: { titolo: 'Heute', vuoto: 'Heute keine Termine.' },
  fatturazione: {
    titolo: 'Fakturierung',
    incassato: 'Eingenommen',
    daIncassare: 'Ausstehend',
    totaleDebito: 'Gesamte offene Forderungen',
    fattura: 'Rechnung {numero}',
    vuoto: 'Keine offenen Rechnungen.',
  },
  settimana: { titolo: 'Nächste 7 Tage', vuoto: 'Keine Termine in den nächsten 7 Tagen.' },
  messaggi: {
    titolo: 'Ungelesene Nachrichten',
    senzaOggetto: 'Ohne Betreff',
    vuoto: 'Keine ausstehenden Nachrichten.',
  },
  attenzione: {
    titolo: 'Dossiers, die Aufmerksamkeit erfordern',
    vuoto: 'Kein Dossier mit nahender Frist.',
    udienza: 'Verhandlung am {data}',
  },
  badge: { fa: 'vor {n} T', oggi: 'Heute', fra: 'in {n} T' },
  commercialista: { etichetta: 'Steuerberater', sottotitolo: 'Die Übersicht über Ihr Büro' },
  fiduciario: {
    etichetta: 'Treuhandbüro',
    titolo: 'Gesamtübersicht',
    titoloNome: 'Gesamtübersicht, {nome}',
    sottotitoloUno: 'Jahr {anno} · 1 Kunde',
    sottotitolo: 'Jahr {anno} · {n} Kunden',
  },
  kpi: {
    clienti: 'Kunden',
    mandati: 'Aktive Mandate',
    fatturatoAnno: 'Umsatz im Jahr',
    incassatoAnno: 'Eingegangen im Jahr',
    fatturato: 'Umsatz {anno}',
    daIncassare: 'Ausstehend',
  },
  fattureScadute: {
    uno: '1 überfällige Rechnung offen',
    molte: '{n} überfällige Rechnungen offen',
    gestisci: 'Verwalten',
  },
  scadenze: {
    titoloFiscali: 'Nächste Steuerfristen',
    titolo: 'Nächste Fristen',
    banco: 'Arbeitsplatz',
    vuotoFiscali:
      'Keine offenen Fristen. Eröffnen Sie auf der Website ein Mandat mit Bezugsjahr und erstellen Sie den Fristenkalender.',
    vuoto: 'Keine bevorstehenden Fristen.',
    oggi: 'heute',
    fraUno: 'in 1 Tag',
    fra: 'in {n} Tagen',
    scadutaDa: 'seit {n} Tagen überfällig',
    scaduteUno: '1 überfällige Frist',
    scadute: '{n} überfällige Fristen',
    sulSito: 'Mandate und Fristen verwalten Sie auf der Website, im Arbeitsplatz.',
  },
  tipiScadenza: { iva: 'MWST', lipe: 'LIPE', dichiarativo: 'Erklärung', acconto: 'Akonto', imu: 'IMU' },
  appuntamenti: {
    titoloSettimana: 'Nächste Termine (7 Tage)',
    titolo: 'Nächste Termine',
    vuoto: 'Keine Termine geplant.',
    calendario: 'Kalender',
    studio: 'Büro',
  },
  mesi: { titolo: 'Büro: Fakturierung der letzten 6 Monate', vai: 'Fakturierung' },
  annoStudio: {
    titolo: 'Büro: Fakturierung {anno}',
    fatturato: 'Umsatz',
    incassato: 'Eingegangen',
    daIncassare: 'Ausstehend',
    scaduto: 'Überfällig',
    nota: 'Vom Büro an die Kunden gestellte Rechnungen (die Erträge des Büros). Hat nichts mit den Erfolgsrechnungen der einzelnen Kunden zu tun.',
  },
  conti: {
    titolo: 'Erfolgsrechnung pro Kunde {anno}',
    nota: 'Jeder Kunde wird einzeln betrachtet, nicht summiert.',
    entrate: 'Einnahmen',
    costi: 'Kosten',
    stipendi: 'Löhne',
    saldo: 'Saldo',
  },
  apriSito: 'Auf der Website öffnen',
  altri: {
    titolo: 'Ihre Dashboard finden Sie auf der Website',
    testo: 'In der App gibt es die Dashboard für Anwälte, Steuerberater und Treuhänder.',
  },
};

const fr: Parziale<typeof it> = {
  titolo: 'Tableau de bord',
  orario: { notte: 'Bonne nuit', mattino: 'Bonjour', pomeriggio: 'Bon après-midi', sera: 'Bonsoir' },
  saluto: '{saluto}, {nome}.',
  sommario: {
    vuoto:
      'Rien dans l’agenda aujourd’hui. Profitez-en pour mettre à jour vos dossiers ou organiser vos recherches.',
    oggi: 'Aujourd’hui, vous avez {parti}.',
    udienzeUno: '1 audience',
    udienze: '{n} audiences',
    terminiUno: '1 délai',
    termini: '{n} délais',
    appuntamentiUno: '1 rendez-vous',
    appuntamenti: '{n} rendez-vous',
    fattureUno: '1 facture en attente.',
    fatture: '{n} factures en attente.',
    messaggiUno: '1 nouveau message.',
    messaggi: '{n} nouveaux messages.',
  },
  periodo: {
    titolo: 'Période',
    testo:
      'S’applique aux dossiers clôturés et à l’encaissé. Le reste du tableau de bord montre toujours la situation du jour.',
    meseCorrente: 'Ce mois-ci',
    meseScorso: 'Mois dernier',
    ultimi90: '90 derniers jours',
    personalizzato: 'Personnalisé',
    da: 'Du',
    a: 'Au',
    applica: 'Appliquer',
    ordine: 'La date de début doit précéder la date de fin.',
  },
  prova: {
    titolo: 'Votre essai gratuit a expiré',
    testo: 'Choisissez un forfait pour continuer à travailler avec vos dossiers, clients et documents.',
    dopo: 'Plus tard',
    piani: 'Voir les forfaits',
  },
  contatori: {
    clienti: 'Clients',
    clientiSotto: 'Total',
    aperte: 'Dossiers ouverts',
    aperteSotto: 'Maintenant',
    chiuse: 'Dossiers clôturés',
  },
  vediTutti: 'Tout voir',
  oggi: { titolo: 'Aujourd’hui', vuoto: 'Aucun engagement aujourd’hui.' },
  fatturazione: {
    titolo: 'Facturation',
    incassato: 'Encaissé',
    daIncassare: 'À encaisser',
    totaleDebito: 'Total des créances actives',
    fattura: 'Facture {numero}',
    vuoto: 'Aucune facture en attente.',
  },
  settimana: { titolo: '7 prochains jours', vuoto: 'Aucun engagement dans les 7 prochains jours.' },
  messaggi: {
    titolo: 'Messages non lus',
    senzaOggetto: 'Sans objet',
    vuoto: 'Aucun message en attente.',
  },
  attenzione: {
    titolo: 'Dossiers nécessitant une attention',
    vuoto: 'Aucun dossier avec échéance imminente.',
    udienza: 'Audience du {data}',
  },
  badge: { fa: 'il y a {n} j', oggi: 'Aujourd’hui', fra: 'dans {n} j' },
  commercialista: { etichetta: 'Expert-comptable', sottotitolo: 'La vue d’ensemble de votre cabinet' },
  fiduciario: {
    etichetta: 'Fiduciaire',
    titolo: 'Vue d’ensemble',
    titoloNome: 'Vue d’ensemble, {nome}',
    sottotitoloUno: 'Année {anno} · 1 client',
    sottotitolo: 'Année {anno} · {n} clients',
  },
  kpi: {
    clienti: 'Clients',
    mandati: 'Mandats actifs',
    fatturatoAnno: 'Chiffre d’affaires de l’année',
    incassatoAnno: 'Encaissé dans l’année',
    fatturato: 'Chiffre d’affaires {anno}',
    daIncassare: 'À encaisser',
  },
  fattureScadute: {
    uno: '1 facture échue à encaisser',
    molte: '{n} factures échues à encaisser',
    gestisci: 'Gérer',
  },
  scadenze: {
    titoloFiscali: 'Prochaines échéances fiscales',
    titolo: 'Prochaines échéances',
    banco: 'Poste de travail',
    vuotoFiscali:
      'Aucune échéance ouverte. Sur le site, ouvrez un mandat avec l’année de référence et générez l’échéancier.',
    vuoto: 'Aucune échéance à venir.',
    oggi: 'aujourd’hui',
    fraUno: 'dans 1 j',
    fra: 'dans {n} j',
    scadutaDa: 'échue depuis {n} j',
    scaduteUno: '1 échéance dépassée',
    scadute: '{n} échéances dépassées',
    sulSito: 'Les mandats et les échéances se gèrent sur le site, dans le poste de travail.',
  },
  tipiScadenza: { iva: 'TVA', lipe: 'LIPE', dichiarativo: 'Déclaration', acconto: 'Acomptes', imu: 'IMU' },
  appuntamenti: {
    titoloSettimana: 'Prochains rendez-vous (7 jours)',
    titolo: 'Prochains rendez-vous',
    vuoto: 'Aucun rendez-vous prévu.',
    calendario: 'Calendrier',
    studio: 'fiduciaire',
  },
  mesi: { titolo: 'Cabinet : facturation des 6 derniers mois', vai: 'Facturation' },
  annoStudio: {
    titolo: 'Fiduciaire : facturation {anno}',
    fatturato: 'Chiffre d’affaires',
    incassato: 'Encaissé',
    daIncassare: 'À encaisser',
    scaduto: 'Échu',
    nota: 'Factures émises par la fiduciaire à ses clients (les produits de la fiduciaire). Sans rapport avec les comptes de résultat des différents clients.',
  },
  conti: {
    titolo: 'Compte de résultat par client {anno}',
    nota: 'Chaque client est traité séparément, sans addition.',
    entrate: 'Recettes',
    costi: 'Charges',
    stipendi: 'Salaires',
    saldo: 'Solde',
  },
  apriSito: 'Ouvrir sur le site',
  altri: {
    titolo: 'Votre tableau de bord est sur le site',
    testo:
      'Dans l’app, le tableau de bord existe pour les avocats, les experts-comptables et les fiduciaires.',
  },
};

export const dashboard = { it, de, fr };
