import type { Parziale } from '../tipi';

// Sezione «documenti»: l'archivio dello studio (categorie, sottocategorie, cliente e pratica di ogni
// documento), il caricamento collegato, i documenti della pratica, gli atti di Lex salvati in PDF e la
// fattura collegata a una pratica. Italiano di riferimento, poi tedesco svizzero e francese.
// I termini svizzeri vengono dal sito (public/locales/*/avv_archivio.json).

const it = {
  archivio: {
    sottotitolo: 'Archivio dello studio',
    filtroCliente: 'Cliente: {nome}',
    filtroPratica: 'Pratica: {titolo}',
    tuttiClienti: 'Tutti i clienti',
    tuttePratiche: 'Tutte le pratiche',
    senzaCliente: 'Senza cliente',
    tutteSotto: 'Tutte',
    senzaSotto: 'Senza sottocategoria',
    categorie: 'Gestisci categorie',
    visibilita: 'Collegato a un cliente: lo vede solo chi lo segue. Non collegato: tutto lo studio.',
    atto: 'Atto di Lex',
    fattura: 'Fattura',
    sceltaCliente: 'Filtra per cliente',
    sceltaPratica: 'Filtra per pratica',
  },
  documento: {
    categoria: 'Categoria',
    cliente: 'Cliente',
    pratica: 'Pratica',
    caricato: 'Caricato',
    dimensione: 'Dimensione',
    nessuno: 'Nessuno',
    nessuna: 'Nessuna',
    collega: 'Cliente e pratica',
    collegaTesto: 'A chi e a quale pratica appartiene',
    sposta: 'Sposta in un’altra categoria',
    condividi: 'Condividi nel portale del cliente',
    condiviso: 'Condiviso nel portale di {nome}.',
    apriFattura: 'Apri la fattura',
    apriPratica: 'Apri la pratica',
    elimina: 'Elimina',
    confermaElimina: 'Eliminare «{titolo}»? Il file si cancella per sempre.',
    eliminaConferma: 'Elimina per sempre',
    fattura: 'Il PDF di una fattura non si elimina dall’archivio.',
  },
  collega: {
    titolo: 'Cliente e pratica',
    testo: 'Una pratica porta con sé il suo cliente.',
    cliente: 'Cliente',
    pratica: 'Pratica',
    nessuno: 'Nessuno',
    nessuna: 'Nessuna',
    senzaPratiche: 'Questo cliente non ha pratiche aperte.',
    salva: 'Salva',
  },
  sposta: {
    titolo: 'Sposta in categoria',
    categoria: 'Categoria',
    sottocategoria: 'Sottocategoria',
    nessuna: 'Nessuna categoria',
    nessunaSotto: 'Nessuna sottocategoria',
    salva: 'Sposta',
  },
  categorie: {
    titolo: 'Categorie',
    testo: 'Per ordinare l’archivio dello studio. Eliminando una categoria i documenti restano.',
    nuova: 'Nuova categoria',
    segnaposto: 'Nome della categoria',
    nuovaSotto: 'Nuova sottocategoria in {nome}',
    segnapostoSotto: 'Nome della sottocategoria',
    aggiungi: 'Aggiungi',
    aggiungiSotto: 'Sottocategoria',
    rinomina: 'Rinomina {nome}',
    elimina: 'Elimina {nome}',
    nDoc: '{n} doc.',
    vuoto: 'Nessuna categoria ancora: crea la prima.',
    confermaCategoria: 'Eliminare «{nome}»? {n} documenti restano senza categoria.',
    confermaSotto: 'Eliminare «{nome}»? I documenti restano nella categoria principale.',
    eliminaConferma: 'Elimina',
    salva: 'Salva',
    fine: 'Fine',
  },
  carica: {
    titolo: 'Carica un documento',
    titoloScansione: 'Scansiona un documento',
    file: 'File',
    fileScelto: '{nome} · {dimensione}',
    scansione: 'Scansione · {pagine} pagine',
    titoloCampo: 'Titolo *',
    categoria: 'Categoria',
    sottocategoria: 'Sottocategoria',
    cliente: 'Cliente',
    pratica: 'Pratica',
    nessuna: 'Nessuna',
    nessuno: 'Nessuno',
    carica: 'Carica',
    lettura: 'Dopo il caricamento Lex lo legge e lo rende cercabile.',
    caricato: '«{titolo}» è nell’archivio.',
  },
  pratica: {
    titolo: 'Documenti · {n}',
    aggiungi: 'Aggiungi',
    vuoto: 'Nessun documento. Caricane uno o scegline uno dall’archivio.',
    aggiungiTitolo: 'Aggiungi un documento',
    carica: 'Carica un file',
    caricaTesto: 'Entra nell’archivio, collegato a questa pratica',
    scansiona: 'Scansiona',
    scansionaTesto: 'Con la fotocamera, diventa un PDF',
    scegli: 'Scegli dall’archivio',
    scegliTesto: 'Un documento che lo studio ha già',
    scegliTitolo: 'Scegli dall’archivio',
    scegliVuoto: 'Nessun altro documento in archivio.',
    togli: 'Togli dalla pratica',
    togliTesto: 'Resta nell’archivio dello studio',
    eliminaAtto: 'Elimina il documento',
    soloPratica: 'Solo nella pratica',
  },
  atto: {
    salva: 'Salva come PDF nella pratica',
    salvato: '«{titolo}» è nei documenti della pratica.',
    apri: 'Vedi i documenti',
  },
  fattura: {
    collega: 'Collega a una pratica',
    cambia: 'Cambia pratica',
    scollega: 'Scollega dalla pratica',
    titolo: 'Collega a una pratica',
    testo: 'Le pratiche di {nome}.',
    nessuna: 'Questo cliente non ha pratiche.',
  },
  ricerca: {
    pratica: 'Collega anche a una pratica (facoltativo)',
    nessuna: 'Nessuna',
  },
};

const de: Parziale<typeof it> = {
  archivio: {
    sottotitolo: 'Archiv der Kanzlei',
    filtroCliente: 'Mandant: {nome}',
    filtroPratica: 'Dossier: {titolo}',
    tuttiClienti: 'Alle Mandanten',
    tuttePratiche: 'Alle Dossiers',
    senzaCliente: 'Ohne Mandant',
    tutteSotto: 'Alle',
    senzaSotto: 'Ohne Unterkategorie',
    categorie: 'Kategorien verwalten',
    visibilita:
      'Mit Mandant verknüpft: nur für den zuständigen Bearbeiter. Nicht verknüpft: gesamte Kanzlei.',
    atto: 'Akte von Lex',
    fattura: 'Rechnung',
    sceltaCliente: 'Nach Mandant filtern',
    sceltaPratica: 'Nach Dossier filtern',
  },
  documento: {
    categoria: 'Kategorie',
    cliente: 'Mandant',
    pratica: 'Dossier',
    caricato: 'Hochgeladen',
    dimensione: 'Grösse',
    nessuno: 'Keiner',
    nessuna: 'Keines',
    collega: 'Mandant und Dossier',
    collegaTesto: 'Wem und zu welchem Dossier es gehört',
    sposta: 'In eine andere Kategorie verschieben',
    condividi: 'Im Mandantenportal teilen',
    condiviso: 'Im Portal von {nome} geteilt.',
    apriFattura: 'Rechnung öffnen',
    apriPratica: 'Dossier öffnen',
    elimina: 'Löschen',
    confermaElimina: '«{titolo}» löschen? Die Datei wird endgültig gelöscht.',
    eliminaConferma: 'Endgültig löschen',
    fattura: 'Das PDF einer Rechnung lässt sich nicht aus dem Archiv löschen.',
  },
  collega: {
    titolo: 'Mandant und Dossier',
    testo: 'Ein Dossier bringt seinen Mandanten mit.',
    cliente: 'Mandant',
    pratica: 'Dossier',
    nessuno: 'Keiner',
    nessuna: 'Keines',
    senzaPratiche: 'Dieser Mandant hat keine offenen Dossiers.',
    salva: 'Speichern',
  },
  sposta: {
    titolo: 'In Kategorie verschieben',
    categoria: 'Kategorie',
    sottocategoria: 'Unterkategorie',
    nessuna: 'Keine Kategorie',
    nessunaSotto: 'Keine Unterkategorie',
    salva: 'Verschieben',
  },
  categorie: {
    titolo: 'Kategorien',
    testo:
      'Um das Archiv der Kanzlei zu ordnen. Wird eine Kategorie gelöscht, bleiben die Dokumente erhalten.',
    nuova: 'Neue Kategorie',
    segnaposto: 'Name der Kategorie',
    nuovaSotto: 'Neue Unterkategorie in {nome}',
    segnapostoSotto: 'Name der Unterkategorie',
    aggiungi: 'Hinzufügen',
    aggiungiSotto: 'Unterkategorie',
    rinomina: '{nome} umbenennen',
    elimina: '{nome} löschen',
    nDoc: '{n} Dok.',
    vuoto: 'Noch keine Kategorie: Erstellen Sie die erste.',
    confermaCategoria: '«{nome}» löschen? {n} Dokumente bleiben ohne Kategorie.',
    confermaSotto: '«{nome}» löschen? Die Dokumente bleiben in der Hauptkategorie.',
    eliminaConferma: 'Löschen',
    salva: 'Speichern',
    fine: 'Fertig',
  },
  carica: {
    titolo: 'Dokument hochladen',
    titoloScansione: 'Dokument scannen',
    file: 'Datei',
    fileScelto: '{nome} · {dimensione}',
    scansione: 'Scan · {pagine} Seiten',
    titoloCampo: 'Titel *',
    categoria: 'Kategorie',
    sottocategoria: 'Unterkategorie',
    cliente: 'Mandant',
    pratica: 'Dossier',
    nessuna: 'Keine',
    nessuno: 'Keiner',
    carica: 'Hochladen',
    lettura: 'Nach dem Hochladen liest Lex das Dokument und macht es durchsuchbar.',
    caricato: '«{titolo}» ist im Archiv.',
  },
  pratica: {
    titolo: 'Dokumente · {n}',
    aggiungi: 'Hinzufügen',
    vuoto: 'Keine Dokumente. Laden Sie eines hoch oder wählen Sie eines aus dem Archiv.',
    aggiungiTitolo: 'Dokument hinzufügen',
    carica: 'Datei hochladen',
    caricaTesto: 'Kommt ins Archiv, mit diesem Dossier verknüpft',
    scansiona: 'Scannen',
    scansionaTesto: 'Mit der Kamera, wird zu einem PDF',
    scegli: 'Aus dem Archiv wählen',
    scegliTesto: 'Ein Dokument, das die Kanzlei bereits hat',
    scegliTitolo: 'Aus dem Archiv wählen',
    scegliVuoto: 'Keine weiteren Dokumente im Archiv.',
    togli: 'Aus dem Dossier entfernen',
    togliTesto: 'Bleibt im Archiv der Kanzlei',
    eliminaAtto: 'Dokument löschen',
    soloPratica: 'Nur im Dossier',
  },
  atto: {
    salva: 'Als PDF im Dossier speichern',
    salvato: '«{titolo}» ist in den Dokumenten des Dossiers.',
    apri: 'Dokumente ansehen',
  },
  fattura: {
    collega: 'Mit einem Dossier verknüpfen',
    cambia: 'Dossier ändern',
    scollega: 'Vom Dossier trennen',
    titolo: 'Mit einem Dossier verknüpfen',
    testo: 'Die Dossiers von {nome}.',
    nessuna: 'Dieser Mandant hat keine Dossiers.',
  },
  ricerca: {
    pratica: 'Auch mit einem Dossier verknüpfen (optional)',
    nessuna: 'Keines',
  },
};

const fr: Parziale<typeof it> = {
  archivio: {
    sottotitolo: 'Archives de l’étude',
    filtroCliente: 'Client : {nome}',
    filtroPratica: 'Dossier : {titolo}',
    tuttiClienti: 'Tous les clients',
    tuttePratiche: 'Tous les dossiers',
    senzaCliente: 'Sans client',
    tutteSotto: 'Toutes',
    senzaSotto: 'Sans sous-catégorie',
    categorie: 'Gérer les catégories',
    visibilita: 'Lié à un client : uniquement le gestionnaire. Non lié : toute l’étude.',
    atto: 'Acte de Lex',
    fattura: 'Facture',
    sceltaCliente: 'Filtrer par client',
    sceltaPratica: 'Filtrer par dossier',
  },
  documento: {
    categoria: 'Catégorie',
    cliente: 'Client',
    pratica: 'Dossier',
    caricato: 'Téléversé',
    dimensione: 'Taille',
    nessuno: 'Aucun',
    nessuna: 'Aucun',
    collega: 'Client et dossier',
    collegaTesto: 'À qui et à quel dossier il appartient',
    sposta: 'Déplacer dans une autre catégorie',
    condividi: 'Partager dans le portail du client',
    condiviso: 'Partagé dans le portail de {nome}.',
    apriFattura: 'Ouvrir la facture',
    apriPratica: 'Ouvrir le dossier',
    elimina: 'Supprimer',
    confermaElimina: 'Supprimer « {titolo} » ? Le fichier est supprimé définitivement.',
    eliminaConferma: 'Supprimer définitivement',
    fattura: 'Le PDF d’une facture ne peut pas être supprimé des archives.',
  },
  collega: {
    titolo: 'Client et dossier',
    testo: 'Un dossier entraîne son client.',
    cliente: 'Client',
    pratica: 'Dossier',
    nessuno: 'Aucun',
    nessuna: 'Aucun',
    senzaPratiche: 'Ce client n’a pas de dossier ouvert.',
    salva: 'Enregistrer',
  },
  sposta: {
    titolo: 'Déplacer dans une catégorie',
    categoria: 'Catégorie',
    sottocategoria: 'Sous-catégorie',
    nessuna: 'Aucune catégorie',
    nessunaSotto: 'Aucune sous-catégorie',
    salva: 'Déplacer',
  },
  categorie: {
    titolo: 'Catégories',
    testo: 'Pour organiser les archives de l’étude. En supprimant une catégorie, les documents restent.',
    nuova: 'Nouvelle catégorie',
    segnaposto: 'Nom de la catégorie',
    nuovaSotto: 'Nouvelle sous-catégorie dans {nome}',
    segnapostoSotto: 'Nom de la sous-catégorie',
    aggiungi: 'Ajouter',
    aggiungiSotto: 'Sous-catégorie',
    rinomina: 'Renommer {nome}',
    elimina: 'Supprimer {nome}',
    nDoc: '{n} doc.',
    vuoto: 'Aucune catégorie pour l’instant : créez la première.',
    confermaCategoria: 'Supprimer « {nome} » ? {n} documents restent sans catégorie.',
    confermaSotto: 'Supprimer « {nome} » ? Les documents restent dans la catégorie principale.',
    eliminaConferma: 'Supprimer',
    salva: 'Enregistrer',
    fine: 'Terminé',
  },
  carica: {
    titolo: 'Téléverser un document',
    titoloScansione: 'Scanner un document',
    file: 'Fichier',
    fileScelto: '{nome} · {dimensione}',
    scansione: 'Scan · {pagine} pages',
    titoloCampo: 'Titre *',
    categoria: 'Catégorie',
    sottocategoria: 'Sous-catégorie',
    cliente: 'Client',
    pratica: 'Dossier',
    nessuna: 'Aucune',
    nessuno: 'Aucun',
    carica: 'Téléverser',
    lettura: 'Après le téléversement, Lex le lit et le rend consultable.',
    caricato: '« {titolo} » est dans les archives.',
  },
  pratica: {
    titolo: 'Documents · {n}',
    aggiungi: 'Ajouter',
    vuoto: 'Aucun document. Téléversez-en un ou choisissez-le dans les archives.',
    aggiungiTitolo: 'Ajouter un document',
    carica: 'Téléverser un fichier',
    caricaTesto: 'Il entre dans les archives, lié à ce dossier',
    scansiona: 'Scanner',
    scansionaTesto: 'Avec l’appareil photo, il devient un PDF',
    scegli: 'Choisir dans les archives',
    scegliTesto: 'Un document que l’étude a déjà',
    scegliTitolo: 'Choisir dans les archives',
    scegliVuoto: 'Aucun autre document dans les archives.',
    togli: 'Retirer du dossier',
    togliTesto: 'Il reste dans les archives de l’étude',
    eliminaAtto: 'Supprimer le document',
    soloPratica: 'Seulement dans le dossier',
  },
  atto: {
    salva: 'Enregistrer en PDF dans le dossier',
    salvato: '« {titolo} » est dans les documents du dossier.',
    apri: 'Voir les documents',
  },
  fattura: {
    collega: 'Lier à un dossier',
    cambia: 'Changer de dossier',
    scollega: 'Détacher du dossier',
    titolo: 'Lier à un dossier',
    testo: 'Les dossiers de {nome}.',
    nessuna: 'Ce client n’a pas de dossier.',
  },
  ricerca: {
    pratica: 'Lier aussi à un dossier (facultatif)',
    nessuna: 'Aucun',
  },
};

export const documenti = { it, de, fr };
