import type { Parziale } from '../tipi';

// Sezione «fatture»: elenco, dettaglio, nuova fattura, dati di fatturazione, totali e regole
// (src/studio/fatturazione.ts). Italiano di riferimento, poi tedesco svizzero («Sie», «ss») e francese («vous»).
// Termini svizzeri: IVA = MWST / TVA, QR-fattura = QR-Rechnung / QR-facture, esente = steuerbefreit / exonéré.
// Dove esiste, il testo viene dal sito svizzero (public/locales/*/avv_fatturazione*.json).
// Stati, metodi di pagamento e motivi d'esenzione si salvano in italiano: qui c'è solo come si mostrano.
// Le parti solo italiane (partita IVA, CPA, ritenuta, SDI) si vedono sempre in italiano: de e fr servono
// solo a tenere complete le lingue.

const it = {
  stati: {
    in_attesa: 'In attesa',
    scaduta: 'Scaduta',
    pagata: 'Pagata',
    annullata: 'Annullata',
    emessa: 'Emessa',
  },
  quando: {
    emessaAnnullata: 'Emessa il {data} · annullata',
    pagataIl: 'Pagata il {data}',
    emessaIl: 'Emessa il {data}',
    scadutaIeri: 'Scaduta da ieri',
    scadutaDa: 'Scaduta da {n} giorni',
    scadeOggi: 'Scade oggi',
    scadeDomani: 'Scade domani',
    scadeTra: 'Scade tra {n} giorni',
    scadeIl: 'Scade il {data}',
  },
  manca: {
    partitaIva: 'partita IVA',
    codiceFiscale: 'codice fiscale',
    indirizzoStudio: 'indirizzo dello studio',
    iban: 'IBAN per la QR-fattura',
    numeroIva: 'numero IDI',
    indirizzo: 'indirizzo',
    e: 'e',
  },
  metodi: {
    bonifico: 'Bonifico',
    contanti: 'Contanti',
    carta: 'Carta',
    assegno: 'Assegno',
    qr: 'QR-fattura',
    twint: 'Carta / TWINT',
  },
  esenzione: {
    estero: 'Prestazione a un cliente all’estero (art. 8 LIVA)',
    esclusa: 'Prestazione esclusa dall’imposta (art. 21 LIVA)',
    nonAssoggettato: 'Non assoggettato all’IVA',
  },
  contributo: {
    cpa: 'CPA',
    cnpadc: 'Contributo integrativo CNPADC',
    cnpr: 'Contributo integrativo CNPR',
  },
  voci: {
    numero: 'Numero',
    cliente: 'Cliente',
    pratica: 'Pratica',
    emessa: 'Emessa',
    scadenza: 'Scadenza',
    prestazione: 'Prestazione',
    prestazioni: 'Prestazioni',
    pagamento: 'Pagamento',
    iban: 'IBAN',
    iva: 'IVA',
    esente: 'Esente',
  },
  scorciatoie: {
    oggi: 'Oggi',
    ieri: 'Ieri',
    traGiorni: 'Tra {n} giorni',
  },
  totali: {
    titolo: 'Totali',
    imponibile: 'Imponibile',
    iva: 'IVA {aliquota}',
    totaleFattura: 'Totale fattura',
    ritenuta: "Ritenuta d'acconto {aliquota}",
    netto: 'Netto a pagare',
    totale: 'Totale',
  },
  elenco: {
    titolo: 'Fatture',
    mancanoDati: 'Mancano i tuoi dati di fatturazione',
    completa: 'Completa',
    numeriAnno: 'I numeri del {anno}',
    fatturato: 'Fatturato',
    incassato: 'Incassato',
    daIncassare: 'Da incassare',
    scaduto: 'Scaduto',
    emesseNel: 'Fatture emesse nel {anno}',
    filtri: {
      daIncassare: 'Da incassare {n}',
      scadute: 'Scadute {n}',
      pagate: 'Pagate {n}',
      tutte: 'Tutte {n}',
    },
    vuoto: {
      nessuna: 'Nessuna fattura, per ora',
      nienteDaIncassare: 'Niente da incassare',
      nessunaQui: 'Nessuna fattura qui',
      crea: 'Crea la prima con «+» in alto.',
    },
    riga: 'Fattura {numero}, {cliente}, {importo}, {stato}',
  },
  dettaglio: {
    fattura: 'Fattura',
    nonCe: "Questa fattura non c'è più",
    tornaFatture: 'Torna alle fatture',
    altreAzioni: 'Altre azioni',
    restaDaIncassare: 'Resta da incassare',
    alNetto: "Al netto della ritenuta d'acconto: il cliente la versa al fisco.",
    pagamenti: 'Pagamenti',
    nessunPagamento: 'Nessun pagamento registrato.',
    residuo: 'Residuo',
    registraPagamento: 'Registra pagamento',
    generaPdf: 'Genera il PDF',
    fatturaNumero: 'Fattura {numero}',
    rigeneraPdf: 'Rigenera il PDF',
    rigeneraQuando: 'Dopo un pagamento o un cambio dei tuoi dati',
    annulla: 'Annulla la fattura',
    annullareDomanda: 'Annullare la fattura {numero}?',
    annullareTesto: "Resta nell'elenco come annullata e il suo numero non si usa più. Non si torna indietro.",
    lasciala: "Lasciala com'è",
    generato: 'Generato · {data}',
    condividi: 'Condividi',
    apriPdf: 'Apri il PDF',
  },
  pagamento: {
    titolo: 'Registra un pagamento',
    residuo: 'Residuo: {importo}. Puoi registrare anche un pagamento parziale.',
    importo: 'Importo ({valuta})',
    erroreImporto: 'Scrivi un importo, per esempio 250,00.',
    piuDelResiduo: 'È più del residuo ({importo}).',
    metodo: 'Metodo',
    data: "Data dell'incasso",
    registra: 'Registra il pagamento',
  },
  nuova: {
    titolo: 'Nuova fattura',
    passo: 'Passo {n} di {totale} · {nome}',
    passi: {
      cliente: 'Cliente',
      prestazioni: 'Prestazioni',
      fisco: 'Fisco e pagamento',
      controlla: 'Controlla',
    },
    servonoDati: 'Prima servono i tuoi dati di fatturazione',
    mancanoDati: 'Mancano {elenco}. Vanno sul PDF di ogni fattura: li scrivi una volta sola.',
    completaDati: 'Completa i dati di fatturazione',
    blocchi: {
      cliente: 'Scegli il cliente.',
      datiCliente: 'Completa i dati del cliente sul sito.',
      prestazione: 'Aggiungi almeno una prestazione.',
      zero: 'Il totale è zero.',
      emissione: 'Scrivi la data di emissione.',
      scadenzaPrima: 'La scadenza viene prima dell’emissione.',
      percentuali: 'Controlla le percentuali.',
      periodo: 'Scrivi la data o il periodo della prestazione.',
      iban: 'Manca il tuo IBAN.',
    },
    mancanoCliente: 'A {nome} mancano {elenco}. Si aggiungono sul sito, in Clienti: poi torna qui.',
    righePronte: 'Le righe della parcella sono pronte: scegli il cliente.',
    praticaFacoltativa: 'Pratica (facoltativa)',
    togli: 'Togli «{descrizione}»',
    nessunaPrestazione: 'Nessuna prestazione, per ora.',
    aggiungiPrestazione: 'Aggiungi una prestazione',
    descrizione: 'Descrizione',
    esempioDescrizione: {
      IT: 'Es. Parere scritto',
      CH: 'Es. Consulenza (ore)',
    },
    quantita: 'Quantità',
    prezzo: 'Prezzo ({valuta})',
    aggiungiLaPrestazione: 'Aggiungi la prestazione',
    ivaPercento: 'IVA (%)',
    ritenuta: "Ritenuta d'acconto 20%",
    ritenutaSpiega: "Se il cliente è un'azienda o un professionista: la versa lui al fisco",
    motivoGruppo: "Motivo dell'esenzione",
    periodo: 'Data o periodo della prestazione',
    esempioPeriodo: 'Es. settembre 2026',
    mesePrestazione: 'Mese della prestazione',
    periodoLegge: "La chiede la legge sull'IVA (art. 26 LIVA).",
    emessaIl: 'Emessa il',
    scadenzaPagamento: 'Scadenza del pagamento',
    sulPdf: 'Sul PDF: IBAN {iban}.',
    sulPdfQr: 'Sul PDF: IBAN {iban}, con la sezione di pagamento QR.',
    mancaIban: 'Manca il tuo IBAN: aggiungilo nei dati di fatturazione.',
    note: 'Note sulla fattura (facoltative)',
    noteSegnaposto: 'Le legge anche il cliente',
    prestazioniN: 'Prestazioni · {n}',
    notaFinale: {
      IT: 'Il numero si assegna quando la crei. Il PDF lo generi dal dettaglio.',
      CH: 'Il numero si assegna quando la crei. Il PDF, con la QR-fattura, lo generi dal dettaglio.',
    },
    crea: 'Crea la fattura',
  },
  dati: {
    titolo: 'Dati di fatturazione',
    intro: 'Vanno sul PDF di ogni fattura. Sono gli stessi del sito: li cambi qui e cambiano anche lì.',
    datiFiscali: 'Dati fiscali',
    partitaIva: 'Partita IVA',
    undiciCifre: '11 cifre',
    codiceFiscale: 'Codice fiscale',
    regime: 'Regime fiscale',
    cassa: 'Cassa di previdenza',
    indirizzo: 'Indirizzo dello studio',
    via: 'Via',
    civico: 'Numero',
    cap: { IT: 'CAP', CH: 'NPA' },
    citta: { IT: 'Comune', CH: 'Località' },
    provincia: 'Provincia',
    iban: { IT: 'IBAN', CH: 'IBAN o QR-IBAN' },
    assoggettatoDomanda: "Sei assoggettato all'IVA?",
    assoggettato: "Assoggettato all'IVA",
    si: 'Sì',
    no: 'No',
    obbligo: 'Obbligatorio da CHF 100’000 di cifra d’affari all’anno.',
    salva: 'Salva',
    errori: {
      piva: 'La partita IVA ha 11 cifre: controlla.',
      cf: 'Il codice fiscale ha 16 caratteri (o 11 cifre).',
      provincia: 'La sigla ha due lettere, per esempio MI.',
      cap: { IT: 'Il CAP ha 5 cifre.', CH: 'Il NPA ha 4 cifre.' },
    },
  },
  nc: {
    titolo: 'Nota di credito',
    numero: 'Nota di credito {numero}',
    aStorno: 'A storno della fattura {numero}',
    aStornoDel: 'A storno della fattura n. {numero} del {data}.',
    ripete: 'La nota di credito ripete IVA, cassa e ritenuta della fattura {numero}.',
    righe:
      'Per uno storno totale lascia le righe come sono; per uno storno parziale togli o cambia le righe.',
    crea: 'Crea la nota di credito',
    azione: 'Nota di credito',
    azioneTesto: 'Storna la fattura, tutta o in parte',
    elenco: 'Note di credito',
    totale: 'Totale nota di credito',
  },
  emissione: {
    nonEliminaIT:
      'Documento emesso: non si elimina. Per correggerlo o annullarlo emetti una nota di credito.',
    nonEliminaCH: 'Fattura emessa: non si elimina più. Se serve, si annulla.',
    elimina: 'Elimina',
    eliminaTesto: 'Non è ancora emessa: si può cancellare',
    eliminareDomanda: 'Eliminare {numero}?',
    eliminareTesto: 'Il documento non è ancora emesso (niente PDF): si cancella del tutto, con le sue righe.',
    eliminaConferma: 'Elimina per sempre',
  },
  xml: {
    azione: 'XML FatturaPA',
    azioneTesto: 'Da caricare su «Fatture e Corrispettivi» o da dare al commercialista',
    pronto: 'XML pronto',
    spiega:
      'Caricalo su «Fatture e Corrispettivi» dell’Agenzia delle Entrate (Fatturazione elettronica, Trasmissione) oppure mandalo al tuo commercialista.',
    mancano: 'Per preparare l’XML sistema prima: {elenco}.',
    nota: 'Il PDF è una copia di cortesia: la fattura elettronica è l’XML FatturaPA, da trasmettere allo SDI.',
  },
  fisco: {
    regime: { RF01: 'Regime ordinario', RF19: 'Regime forfettario' },
    forfettario:
      "Regime forfettario: niente IVA (natura N2.2) e niente ritenuta d'acconto. In fattura compaiono le diciture di legge (art. 1, commi 54-89 e comma 67, L. 190/2014).",
    cambia: 'Il regime si cambia nei dati di fatturazione.',
    natura: "Natura dell'operazione *",
    riferimento: 'Riferimento normativo (compare in fattura)',
    riferimentoEsempio: "Es. Operazione esente ai sensi dell'art. 10 DPR 633/72",
    naturaManca: "Con IVA 0% indica la natura dell'operazione.",
    ivaZero: 'IVA 0% · {natura}',
    spesa: 'Spesa anticipata per conto del cliente',
    spesaTesto: 'Esente art. 15: niente cassa, IVA e ritenuta',
    esente: 'esente art. 15',
    bollo: 'Imposta di bollo 2 €',
    bolloServe: 'Dovuta quando la parte senza IVA supera 77,47 €: per questa fattura serve.',
    bolloNonServe: 'Dovuta quando la parte senza IVA supera 77,47 €.',
    bolloCliente: 'Addebita i 2 € al cliente',
    clienteSdi:
      'Il cliente ha la partita IVA ma non il codice destinatario SDI né la PEC di fatturazione: li aggiungi dalla sua scheda.',
    destinatario: 'Fattura elettronica: {destinatario}',
    esenti: 'Spese esenti art. 15',
    bolloRiga: 'Imposta di bollo',
    nonAssoggettato: 'Non sei iscritto nel registro IVA: la fattura esce senza IVA.',
    cambiaDati: 'Si cambia nei dati di fatturazione.',
    aliquota: 'Aliquota IVA',
    aliquoteSpiega: 'Normale 8,1%, ridotta 2,6%, alloggio 3,8%.',
    motivo: "Motivo dell'esenzione (facoltativo, va in fattura)",
    motivoEsempio: "Es. Luogo della prestazione all'estero (art. 8 LIVA)",
    lingua: 'Lingua della fattura',
    ibanQr: 'Un QR-IBAN non va bene per il bonifico: nei dati di fatturazione metti l’IBAN del conto.',
  },
  datiNuovi: {
    casse: {
      cassa_forense: 'Cassa Forense (C.P.A. 4%)',
      cnpadc: 'CNPADC, dottori commercialisti (4%)',
      cnpr: 'CNPR, ragionieri (4%)',
      nessuna: 'Nessuna cassa',
    },
    regimi: { RF01: 'Ordinario (RF01)', RF19: 'Forfettario (RF19)' },
    sdi: 'Codice destinatario SDI',
    paese: 'Paese',
    cantone: 'Cantone',
    scegliCantone: 'Scegli il Cantone',
    ibanConto: 'IBAN del conto',
    qrIban: 'QR-IBAN (facoltativo)',
    qrIbanTesto: 'Solo se la banca te l’ha dato: serve per la QR-fattura con riferimento QR.',
    numeroIdi: 'Numero IDI',
    esempioIdi: 'CHE-123.456.789',
    nonAssoggettato: 'Non assoggettato: le tue fatture escono senza IVA.',
    errori: {
      iban: 'IBAN non valido: controlla le cifre.',
      ibanQr: 'Questo è un QR-IBAN: mettilo nel campo QR-IBAN.',
      qrIban: 'Non è un QR-IBAN svizzero (banca tra 30000 e 31999).',
      idi: 'Numero IDI non valido: CHE-123.456.789, con la cifra di controllo giusta.',
      idiObbligatorio: "Se sei assoggettato all'IVA serve il numero IDI.",
      sdi: 'Il codice SDI ha 7 caratteri, lettere e numeri.',
      paese: 'Il paese si scrive con 2 lettere, per esempio IT.',
    },
  },
};

const de: Parziale<typeof it> = {
  stati: {
    in_attesa: 'Ausstehend',
    scaduta: 'Überfällig',
    pagata: 'Bezahlt',
    annullata: 'Storniert',
    emessa: 'Ausgestellt',
  },
  quando: {
    emessaAnnullata: 'Ausgestellt am {data} · storniert',
    pagataIl: 'Bezahlt am {data}',
    emessaIl: 'Ausgestellt am {data}',
    scadutaIeri: 'Seit gestern überfällig',
    scadutaDa: 'Seit {n} Tagen überfällig',
    scadeOggi: 'Heute fällig',
    scadeDomani: 'Morgen fällig',
    scadeTra: 'Fällig in {n} Tagen',
    scadeIl: 'Fällig am {data}',
  },
  manca: {
    partitaIva: 'MWST-Nummer (Partita IVA)',
    codiceFiscale: 'Steuernummer (Codice fiscale)',
    indirizzoStudio: 'Geschäftsadresse',
    iban: 'IBAN für die QR-Rechnung',
    numeroIva: 'UID-Nummer',
    indirizzo: 'Adresse',
    e: 'und',
  },
  metodi: {
    bonifico: 'Überweisung',
    contanti: 'Bar',
    carta: 'Karte',
    assegno: 'Scheck',
    qr: 'QR-Rechnung',
    twint: 'Karte / TWINT',
  },
  esenzione: {
    estero: 'Leistung an einen Mandanten im Ausland (Art. 8 MWSTG)',
    esclusa: 'Von der Steuer ausgenommene Leistung (Art. 21 MWSTG)',
    nonAssoggettato: 'Nicht mehrwertsteuerpflichtig',
  },
  contributo: {
    cpa: 'CPA',
    cnpadc: 'Integrativbeitrag CNPADC',
    cnpr: 'Integrativbeitrag CNPR',
  },
  voci: {
    numero: 'Nummer',
    cliente: 'Mandant',
    pratica: 'Dossier',
    emessa: 'Ausgestellt',
    scadenza: 'Fälligkeit',
    prestazione: 'Leistung',
    prestazioni: 'Leistungen',
    pagamento: 'Zahlung',
    iban: 'IBAN',
    iva: 'MWST',
    esente: 'Steuerbefreit',
  },
  scorciatoie: {
    oggi: 'Heute',
    ieri: 'Gestern',
    traGiorni: 'In {n} Tagen',
  },
  totali: {
    titolo: 'Zusammenfassung',
    imponibile: 'Nettobetrag',
    iva: 'MWST {aliquota}',
    totaleFattura: 'Rechnungsbetrag',
    ritenuta: 'Quellensteuer {aliquota}',
    netto: 'Netto zu bezahlen',
    totale: 'Total',
  },
  elenco: {
    titolo: 'Rechnungen',
    mancanoDati: 'Ihre Rechnungsdaten fehlen',
    completa: 'Ergänzen',
    numeriAnno: 'Die Zahlen {anno}',
    fatturato: 'Umsatz',
    incassato: 'Eingegangen',
    daIncassare: 'Ausstehend',
    scaduto: 'Überfällig',
    emesseNel: 'Im Jahr {anno} ausgestellte Rechnungen',
    filtri: {
      daIncassare: 'Ausstehend {n}',
      scadute: 'Überfällig {n}',
      pagate: 'Bezahlt {n}',
      tutte: 'Alle {n}',
    },
    vuoto: {
      nessuna: 'Noch keine Rechnungen',
      nienteDaIncassare: 'Nichts ausstehend',
      nessunaQui: 'Keine Rechnungen hier',
      crea: 'Erstellen Sie die erste mit «+» oben.',
    },
    riga: 'Rechnung {numero}, {cliente}, {importo}, {stato}',
  },
  dettaglio: {
    fattura: 'Rechnung',
    nonCe: 'Diese Rechnung gibt es nicht mehr',
    tornaFatture: 'Zurück zu den Rechnungen',
    altreAzioni: 'Weitere Aktionen',
    restaDaIncassare: 'Noch offen',
    alNetto: 'Ohne Quellensteuer: Der Mandant zahlt sie direkt an die Steuerbehörde.',
    pagamenti: 'Zahlungen',
    nessunPagamento: 'Keine Zahlung erfasst.',
    residuo: 'Offener Betrag',
    registraPagamento: 'Zahlung erfassen',
    generaPdf: 'PDF erstellen',
    fatturaNumero: 'Rechnung {numero}',
    rigeneraPdf: 'PDF neu erstellen',
    rigeneraQuando: 'Nach einer Zahlung oder wenn sich Ihre Daten ändern',
    annulla: 'Rechnung stornieren',
    annullareDomanda: 'Rechnung {numero} stornieren?',
    annullareTesto:
      'Sie bleibt als storniert in der Liste, und ihre Nummer wird nicht mehr verwendet. Das lässt sich nicht rückgängig machen.',
    lasciala: 'So belassen',
    generato: 'Erstellt · {data}',
    condividi: 'Teilen',
    apriPdf: 'PDF öffnen',
  },
  pagamento: {
    titolo: 'Eine Zahlung erfassen',
    residuo: 'Offen: {importo}. Sie können auch eine Teilzahlung erfassen.',
    importo: 'Betrag ({valuta})',
    erroreImporto: 'Geben Sie einen Betrag ein, zum Beispiel 250.00.',
    piuDelResiduo: 'Das ist mehr als der offene Betrag ({importo}).',
    metodo: 'Zahlungsart',
    data: 'Eingangsdatum',
    registra: 'Zahlung speichern',
  },
  nuova: {
    titolo: 'Neue Rechnung',
    passo: 'Schritt {n} von {totale} · {nome}',
    passi: {
      cliente: 'Mandant',
      prestazioni: 'Leistungen',
      fisco: 'Steuern und Zahlung',
      controlla: 'Prüfen',
    },
    servonoDati: 'Zuerst braucht es Ihre Rechnungsdaten',
    mancanoDati:
      'Es fehlen: {elenco}. Diese Angaben stehen auf dem PDF jeder Rechnung: Sie erfassen sie nur einmal.',
    completaDati: 'Rechnungsdaten ergänzen',
    blocchi: {
      cliente: 'Wählen Sie den Mandanten.',
      datiCliente: 'Ergänzen Sie die Daten des Mandanten auf der Website.',
      prestazione: 'Fügen Sie mindestens eine Leistung hinzu.',
      zero: 'Das Total ist null.',
      emissione: 'Geben Sie das Rechnungsdatum ein.',
      scadenzaPrima: 'Die Fälligkeit liegt vor dem Rechnungsdatum.',
      percentuali: 'Prüfen Sie die Prozentsätze.',
      periodo: 'Geben Sie das Datum oder den Zeitraum der Leistung ein.',
      iban: 'Ihre IBAN fehlt.',
    },
    mancanoCliente:
      'Bei {nome} fehlen: {elenco}. Sie ergänzen das auf der Website unter «Mandanten» und kommen dann hierher zurück.',
    righePronte: 'Die Positionen der Honorarnote sind bereit: Wählen Sie den Mandanten.',
    praticaFacoltativa: 'Dossier (optional)',
    togli: '«{descrizione}» entfernen',
    nessunaPrestazione: 'Noch keine Leistung.',
    aggiungiPrestazione: 'Neue Leistung',
    descrizione: 'Beschreibung',
    esempioDescrizione: {
      IT: 'Z. B. Schriftliches Gutachten',
      CH: 'Z. B. Beratung (Stunden)',
    },
    quantita: 'Menge',
    prezzo: 'Preis ({valuta})',
    aggiungiLaPrestazione: 'Leistung hinzufügen',
    ivaPercento: 'MWST (%)',
    ritenuta: 'Quellensteuer 20%',
    ritenutaSpiega:
      'Wenn der Mandant ein Unternehmen oder eine Fachperson ist: Er zahlt sie an die Steuerbehörde',
    motivoGruppo: 'Grund der Steuerbefreiung',
    periodo: 'Datum oder Zeitraum der Leistung',
    esempioPeriodo: 'Z. B. September 2026',
    mesePrestazione: 'Monat der Leistung',
    periodoLegge: 'Das verlangt das Mehrwertsteuergesetz (Art. 26 MWSTG).',
    emessaIl: 'Ausgestellt am',
    scadenzaPagamento: 'Zahlungsfrist',
    sulPdf: 'Auf dem PDF: IBAN {iban}.',
    sulPdfQr: 'Auf dem PDF: IBAN {iban}, mit dem QR-Zahlteil.',
    mancaIban: 'Ihre IBAN fehlt: Ergänzen Sie sie in den Rechnungsdaten.',
    note: 'Bemerkungen auf der Rechnung (optional)',
    noteSegnaposto: 'Auch der Mandant liest sie',
    prestazioniN: 'Leistungen · {n}',
    notaFinale: {
      IT: 'Die Nummer wird beim Erstellen vergeben. Das PDF erstellen Sie in der Detailansicht.',
      CH: 'Die Nummer wird beim Erstellen vergeben. Das PDF mit der QR-Rechnung erstellen Sie in der Detailansicht.',
    },
    crea: 'Rechnung erstellen',
  },
  dati: {
    titolo: 'Rechnungsdaten',
    intro:
      'Sie stehen auf dem PDF jeder Rechnung. Es sind dieselben wie auf der Website: Ändern Sie sie hier, ändern sie sich auch dort.',
    datiFiscali: 'Steuerdaten',
    partitaIva: 'MWST-Nummer (Partita IVA)',
    undiciCifre: '11 Ziffern',
    codiceFiscale: 'Steuernummer (Codice fiscale)',
    regime: 'Steuerregime',
    cassa: 'Vorsorgekasse',
    indirizzo: 'Geschäftsadresse',
    via: 'Strasse',
    civico: 'Nr.',
    cap: { IT: 'PLZ', CH: 'PLZ' },
    citta: { IT: 'Gemeinde', CH: 'Ort' },
    provincia: 'Provinz',
    iban: { IT: 'IBAN', CH: 'IBAN oder QR-IBAN' },
    assoggettatoDomanda: 'Sind Sie mehrwertsteuerpflichtig?',
    assoggettato: 'Mehrwertsteuerpflichtig',
    si: 'Ja',
    no: 'Nein',
    obbligo: 'Pflicht ab CHF 100’000 Umsatz pro Jahr.',
    salva: 'Speichern',
    errori: {
      piva: 'Die Partita IVA hat 11 Ziffern: Bitte prüfen.',
      cf: 'Der Codice fiscale hat 16 Zeichen (oder 11 Ziffern).',
      provincia: 'Das Kürzel hat zwei Buchstaben, zum Beispiel MI.',
      cap: { IT: 'Die PLZ hat 5 Ziffern.', CH: 'Die PLZ hat 4 Ziffern.' },
    },
  },
  nc: {
    titolo: 'Gutschrift',
    numero: 'Gutschrift {numero}',
    aStorno: 'Storno der Rechnung {numero}',
    aStornoDel: 'Storno der Rechnung Nr. {numero} vom {data}.',
    ripete: 'Die Gutschrift übernimmt MWST, Kasse und Quellensteuer der Rechnung {numero}.',
    righe:
      'Für ein vollständiges Storno lassen Sie die Positionen, wie sie sind; für ein Teilstorno entfernen oder ändern Sie Positionen.',
    crea: 'Gutschrift erstellen',
    azione: 'Gutschrift',
    azioneTesto: 'Die Rechnung ganz oder teilweise stornieren',
    elenco: 'Gutschriften',
    totale: 'Total Gutschrift',
  },
  emissione: {
    nonEliminaIT:
      'Ausgestelltes Dokument: Es lässt sich nicht löschen. Zum Korrigieren oder Annullieren stellen Sie eine Gutschrift aus.',
    nonEliminaCH: 'Ausgestellte Rechnung: Sie lässt sich nicht mehr löschen. Wenn nötig, wird sie storniert.',
    elimina: 'Löschen',
    eliminaTesto: 'Noch nicht ausgestellt: Sie kann gelöscht werden',
    eliminareDomanda: '{numero} löschen?',
    eliminareTesto:
      'Das Dokument ist noch nicht ausgestellt (kein PDF): Es wird mit allen Positionen gelöscht.',
    eliminaConferma: 'Endgültig löschen',
  },
  xml: {
    azione: 'XML FatturaPA',
    azioneTesto: 'Für «Fatture e Corrispettivi» oder für den Treuhänder',
    pronto: 'XML bereit',
    spiega:
      'Laden Sie es bei «Fatture e Corrispettivi» der Agenzia delle Entrate hoch oder senden Sie es Ihrem Steuerberater.',
    mancano: 'Um das XML vorzubereiten, ergänzen Sie zuerst: {elenco}.',
    nota: 'Das PDF ist eine Kopie: Die elektronische Rechnung ist das XML FatturaPA, das an das SDI geht.',
  },
  fisco: {
    regime: { RF01: 'Ordentliches Regime', RF19: 'Pauschalregime' },
    forfettario:
      'Pauschalregime: keine MWST (Natur N2.2) und keine Quellensteuer. Auf der Rechnung stehen die gesetzlichen Vermerke.',
    cambia: 'Das Regime ändern Sie in den Rechnungsdaten.',
    natura: 'Natur des Umsatzes *',
    riferimento: 'Gesetzliche Grundlage (steht auf der Rechnung)',
    riferimentoEsempio: 'Z. B. Steuerbefreit nach Art. 10 DPR 633/72',
    naturaManca: 'Bei 0 % MWST geben Sie die Natur des Umsatzes an.',
    ivaZero: 'MWST 0 % · {natura}',
    spesa: 'Auslage im Namen des Mandanten',
    spesaTesto: 'Befreit nach Art. 15: keine Kasse, MWST und Quellensteuer',
    esente: 'befreit Art. 15',
    bollo: 'Stempelsteuer 2 €',
    bolloServe: 'Geschuldet, wenn der Teil ohne MWST 77,47 € übersteigt: für diese Rechnung nötig.',
    bolloNonServe: 'Geschuldet, wenn der Teil ohne MWST 77,47 € übersteigt.',
    bolloCliente: 'Die 2 € dem Mandanten belasten',
    clienteSdi:
      'Der Mandant hat eine MWST-Nummer, aber weder SDI-Code noch PEC für Rechnungen: Ergänzen Sie sie in seiner Karte.',
    destinatario: 'Elektronische Rechnung: {destinatario}',
    esenti: 'Befreite Auslagen Art. 15',
    bolloRiga: 'Stempelsteuer',
    nonAssoggettato: 'Sie sind nicht im MWST-Register eingetragen: Die Rechnung wird ohne MWST ausgestellt.',
    cambiaDati: 'Das ändern Sie in den Rechnungsdaten.',
    aliquota: 'MWST-Satz',
    aliquoteSpiega: 'Normalsatz 8,1 %, reduziert 2,6 %, Beherbergung 3,8 %.',
    motivo: 'Grund der Steuerbefreiung (optional, steht auf der Rechnung)',
    motivoEsempio: 'Z. B. Ort der Leistung im Ausland (Art. 8 MWSTG)',
    lingua: 'Sprache der Rechnung',
    ibanQr:
      'Eine QR-IBAN eignet sich nicht für Überweisungen: Hinterlegen Sie in den Rechnungsdaten die IBAN des Kontos.',
  },
  datiNuovi: {
    casse: {
      cassa_forense: 'Cassa Forense (C.P.A. 4 %)',
      cnpadc: 'CNPADC, Steuerberater (4 %)',
      cnpr: 'CNPR, Buchhalter (4 %)',
      nessuna: 'Keine Kasse',
    },
    regimi: { RF01: 'Ordentlich (RF01)', RF19: 'Pauschal (RF19)' },
    sdi: 'SDI-Empfängercode',
    paese: 'Land',
    cantone: 'Kanton',
    scegliCantone: 'Kanton wählen',
    ibanConto: 'IBAN des Kontos',
    qrIban: 'QR-IBAN (optional)',
    qrIbanTesto: 'Nur wenn Ihre Bank sie Ihnen gegeben hat: für die QR-Rechnung mit QR-Referenz.',
    numeroIdi: 'UID-Nummer',
    esempioIdi: 'CHE-123.456.789',
    nonAssoggettato: 'Nicht steuerpflichtig: Ihre Rechnungen werden ohne MWST ausgestellt.',
    errori: {
      iban: 'Ungültige IBAN: Prüfen Sie die Ziffern.',
      ibanQr: 'Das ist eine QR-IBAN: Tragen Sie sie im Feld QR-IBAN ein.',
      qrIban: 'Keine Schweizer QR-IBAN (Bank zwischen 30000 und 31999).',
      idi: 'Ungültige UID-Nummer: CHE-123.456.789, mit der richtigen Prüfziffer.',
      idiObbligatorio: 'Wenn Sie mehrwertsteuerpflichtig sind, braucht es die UID-Nummer.',
      sdi: 'Der SDI-Code hat 7 Zeichen, Buchstaben und Ziffern.',
      paese: 'Das Land wird mit 2 Buchstaben geschrieben, zum Beispiel CH.',
    },
  },
};

const fr: Parziale<typeof it> = {
  stati: {
    in_attesa: 'En attente',
    scaduta: 'Échue',
    pagata: 'Payée',
    annullata: 'Annulée',
    emessa: 'Émise',
  },
  quando: {
    emessaAnnullata: 'Émise le {data} · annulée',
    pagataIl: 'Payée le {data}',
    emessaIl: 'Émise le {data}',
    scadutaIeri: 'Échue depuis hier',
    scadutaDa: 'Échue depuis {n} jours',
    scadeOggi: "Échéance aujourd'hui",
    scadeDomani: 'Échéance demain',
    scadeTra: 'Échéance dans {n} jours',
    scadeIl: 'Échéance le {data}',
  },
  manca: {
    partitaIva: 'numéro TVA (partita IVA)',
    codiceFiscale: 'code fiscal (codice fiscale)',
    indirizzoStudio: 'adresse professionnelle',
    iban: 'IBAN pour la QR-facture',
    numeroIva: 'numéro IDE',
    indirizzo: 'adresse',
    e: 'et',
  },
  metodi: {
    bonifico: 'Virement',
    contanti: 'Espèces',
    carta: 'Carte',
    assegno: 'Chèque',
    qr: 'QR-facture',
    twint: 'Carte / TWINT',
  },
  esenzione: {
    estero: "Prestation à un client à l'étranger (art. 8 LTVA)",
    esclusa: "Prestation exclue du champ de l'impôt (art. 21 LTVA)",
    nonAssoggettato: 'Non assujetti à la TVA',
  },
  contributo: {
    cpa: 'CPA',
    cnpadc: 'Contribution intégrative CNPADC',
    cnpr: 'Contribution intégrative CNPR',
  },
  voci: {
    numero: 'Numéro',
    cliente: 'Client',
    pratica: 'Dossier',
    emessa: 'Émise',
    scadenza: 'Échéance',
    prestazione: 'Prestation',
    prestazioni: 'Prestations',
    pagamento: 'Paiement',
    iban: 'IBAN',
    iva: 'TVA',
    esente: 'Exonérée',
  },
  scorciatoie: {
    oggi: "Aujourd'hui",
    ieri: 'Hier',
    traGiorni: 'Dans {n} jours',
  },
  totali: {
    titolo: 'Récapitulatif',
    imponibile: 'Montant net',
    iva: 'TVA {aliquota}',
    totaleFattura: 'Total de la facture',
    ritenuta: 'Retenue à la source {aliquota}',
    netto: 'Net à payer',
    totale: 'Total',
  },
  elenco: {
    titolo: 'Factures',
    mancanoDati: 'Vos données de facturation manquent',
    completa: 'Compléter',
    numeriAnno: 'Les chiffres {anno}',
    fatturato: 'Facturé',
    incassato: 'Encaissé',
    daIncassare: 'À encaisser',
    scaduto: 'Échu',
    emesseNel: 'Factures émises en {anno}',
    filtri: {
      daIncassare: 'À encaisser {n}',
      scadute: 'Échues {n}',
      pagate: 'Payées {n}',
      tutte: 'Toutes {n}',
    },
    vuoto: {
      nessuna: 'Aucune facture pour le moment',
      nienteDaIncassare: 'Rien à encaisser',
      nessunaQui: 'Aucune facture ici',
      crea: 'Créez la première avec « + » en haut.',
    },
    riga: 'Facture {numero}, {cliente}, {importo}, {stato}',
  },
  dettaglio: {
    fattura: 'Facture',
    nonCe: "Cette facture n'existe plus",
    tornaFatture: 'Retour aux factures',
    altreAzioni: 'Autres actions',
    restaDaIncassare: 'Reste à encaisser',
    alNetto: 'Hors retenue à la source : le client la verse directement au fisc.',
    pagamenti: 'Paiements',
    nessunPagamento: 'Aucun paiement enregistré.',
    residuo: 'Solde',
    registraPagamento: 'Enregistrer un paiement',
    generaPdf: 'Générer le PDF',
    fatturaNumero: 'Facture {numero}',
    rigeneraPdf: 'Régénérer le PDF',
    rigeneraQuando: 'Après un paiement ou une modification de vos données',
    annulla: 'Annuler la facture',
    annullareDomanda: 'Annuler la facture {numero} ?',
    annullareTesto:
      "Elle reste dans la liste comme annulée et son numéro n'est plus utilisé. C'est définitif.",
    lasciala: 'La laisser telle quelle',
    generato: 'Généré · {data}',
    condividi: 'Partager',
    apriPdf: 'Ouvrir le PDF',
  },
  pagamento: {
    titolo: 'Enregistrer un paiement',
    residuo: 'Solde : {importo}. Vous pouvez aussi enregistrer un paiement partiel.',
    importo: 'Montant ({valuta})',
    erroreImporto: 'Saisissez un montant, par exemple 250.00.',
    piuDelResiduo: "C'est plus que le solde ({importo}).",
    metodo: 'Mode de paiement',
    data: "Date de l'encaissement",
    registra: 'Enregistrer le paiement',
  },
  nuova: {
    titolo: 'Nouvelle facture',
    passo: 'Étape {n} sur {totale} · {nome}',
    passi: {
      cliente: 'Client',
      prestazioni: 'Prestations',
      fisco: 'Impôts et paiement',
      controlla: 'Vérifier',
    },
    servonoDati: "Il faut d'abord vos données de facturation",
    mancanoDati:
      "Il manque : {elenco}. Ces données figurent sur le PDF de chaque facture : vous ne les saisissez qu'une fois.",
    completaDati: 'Compléter les données de facturation',
    blocchi: {
      cliente: 'Choisissez le client.',
      datiCliente: 'Complétez les données du client sur le site.',
      prestazione: 'Ajoutez au moins une prestation.',
      zero: 'Le total est de zéro.',
      emissione: "Saisissez la date d'émission.",
      scadenzaPrima: "L'échéance est antérieure à l'émission.",
      percentuali: 'Vérifiez les pourcentages.',
      periodo: 'Saisissez la date ou la période de la prestation.',
      iban: 'Votre IBAN manque.',
    },
    mancanoCliente:
      'Pour {nome}, il manque : {elenco}. Vous les ajoutez sur le site, dans « Clients », puis revenez ici.',
    righePronte: "Les lignes de la note d'honoraires sont prêtes : choisissez le client.",
    praticaFacoltativa: 'Dossier (facultatif)',
    togli: 'Retirer « {descrizione} »',
    nessunaPrestazione: 'Aucune prestation pour le moment.',
    aggiungiPrestazione: 'Nouvelle prestation',
    descrizione: 'Description',
    esempioDescrizione: {
      IT: 'P. ex. avis écrit',
      CH: 'P. ex. conseil (heures)',
    },
    quantita: 'Quantité',
    prezzo: 'Prix ({valuta})',
    aggiungiLaPrestazione: 'Ajouter la prestation',
    ivaPercento: 'TVA (%)',
    ritenuta: 'Retenue à la source 20%',
    ritenutaSpiega: "Si le client est une entreprise ou un professionnel : c'est lui qui la verse au fisc",
    motivoGruppo: "Motif de l'exonération",
    periodo: 'Date ou période de la prestation',
    esempioPeriodo: 'P. ex. septembre 2026',
    mesePrestazione: 'Mois de la prestation',
    periodoLegge: "La loi sur la TVA l'exige (art. 26 LTVA).",
    emessaIl: 'Émise le',
    scadenzaPagamento: 'Délai de paiement',
    sulPdf: 'Sur le PDF : IBAN {iban}.',
    sulPdfQr: 'Sur le PDF : IBAN {iban}, avec la section paiement QR.',
    mancaIban: 'Votre IBAN manque : ajoutez-le dans les données de facturation.',
    note: 'Remarques sur la facture (facultatives)',
    noteSegnaposto: 'Le client les lit aussi',
    prestazioniN: 'Prestations · {n}',
    notaFinale: {
      IT: 'Le numéro est attribué à la création. Vous générez le PDF depuis le détail.',
      CH: 'Le numéro est attribué à la création. Vous générez le PDF, avec la QR-facture, depuis le détail.',
    },
    crea: 'Créer la facture',
  },
  dati: {
    titolo: 'Données de facturation',
    intro:
      'Elles figurent sur le PDF de chaque facture. Ce sont les mêmes que sur le site : si vous les modifiez ici, elles changent aussi là-bas.',
    datiFiscali: 'Données fiscales',
    partitaIva: 'Numéro TVA (partita IVA)',
    undiciCifre: '11 chiffres',
    codiceFiscale: 'Code fiscal (codice fiscale)',
    regime: 'Régime fiscal',
    cassa: 'Caisse de prévoyance',
    indirizzo: 'Adresse professionnelle',
    via: 'Rue',
    civico: 'N°',
    cap: { IT: 'Code postal', CH: 'NPA' },
    citta: { IT: 'Commune', CH: 'Localité' },
    provincia: 'Province',
    iban: { IT: 'IBAN', CH: 'IBAN ou QR-IBAN' },
    assoggettatoDomanda: 'Êtes-vous assujetti à la TVA ?',
    assoggettato: 'Assujetti à la TVA',
    si: 'Oui',
    no: 'Non',
    obbligo: "Obligatoire dès CHF 100’000 de chiffre d'affaires par an.",
    salva: 'Enregistrer',
    errori: {
      piva: 'La partita IVA compte 11 chiffres : vérifiez-la.',
      cf: 'Le code fiscal compte 16 caractères (ou 11 chiffres).',
      provincia: 'Le sigle compte deux lettres, par exemple MI.',
      cap: { IT: 'Le code postal compte 5 chiffres.', CH: 'Le NPA compte 4 chiffres.' },
    },
  },
  nc: {
    titolo: 'Note de crédit',
    numero: 'Note de crédit {numero}',
    aStorno: 'Extourne de la facture {numero}',
    aStornoDel: 'Extourne de la facture n° {numero} du {data}.',
    ripete: 'La note de crédit reprend la TVA, la caisse et la retenue de la facture {numero}.',
    righe:
      'Pour une extourne totale, laissez les lignes telles quelles ; pour une extourne partielle, retirez ou modifiez des lignes.',
    crea: 'Créer la note de crédit',
    azione: 'Note de crédit',
    azioneTesto: 'Extourner la facture, en tout ou en partie',
    elenco: 'Notes de crédit',
    totale: 'Total de la note de crédit',
  },
  emissione: {
    nonEliminaIT:
      'Document émis : il ne se supprime pas. Pour le corriger ou l’annuler, émettez une note de crédit.',
    nonEliminaCH: 'Facture émise : elle ne se supprime plus. Si nécessaire, elle s’annule.',
    elimina: 'Supprimer',
    eliminaTesto: 'Pas encore émise : elle peut être supprimée',
    eliminareDomanda: 'Supprimer {numero} ?',
    eliminareTesto:
      'Le document n’est pas encore émis (pas de PDF) : il est supprimé entièrement, avec ses lignes.',
    eliminaConferma: 'Supprimer définitivement',
  },
  xml: {
    azione: 'XML FatturaPA',
    azioneTesto: 'À téléverser sur « Fatture e Corrispettivi » ou à donner au comptable',
    pronto: 'XML prêt',
    spiega:
      'Téléversez-le sur « Fatture e Corrispettivi » de l’Agenzia delle Entrate ou envoyez-le à votre expert-comptable.',
    mancano: 'Pour préparer l’XML, complétez d’abord : {elenco}.',
    nota: 'Le PDF est une copie de courtoisie : la facture électronique est l’XML FatturaPA, à transmettre au SDI.',
  },
  fisco: {
    regime: { RF01: 'Régime ordinaire', RF19: 'Régime forfaitaire' },
    forfettario:
      'Régime forfaitaire : pas de TVA (nature N2.2) ni de retenue à la source. Les mentions légales figurent sur la facture.',
    cambia: 'Le régime se modifie dans les données de facturation.',
    natura: "Nature de l'opération *",
    riferimento: 'Référence légale (figure sur la facture)',
    riferimentoEsempio: "Ex. Opération exonérée selon l'art. 10 DPR 633/72",
    naturaManca: "Avec une TVA à 0 %, indiquez la nature de l'opération.",
    ivaZero: 'TVA 0 % · {natura}',
    spesa: 'Débours au nom du client',
    spesaTesto: 'Exonéré art. 15 : ni caisse, ni TVA, ni retenue',
    esente: 'exonéré art. 15',
    bollo: 'Droit de timbre 2 €',
    bolloServe: 'Dû lorsque la partie sans TVA dépasse 77,47 € : nécessaire pour cette facture.',
    bolloNonServe: 'Dû lorsque la partie sans TVA dépasse 77,47 €.',
    bolloCliente: 'Facturer les 2 € au client',
    clienteSdi:
      'Le client a un numéro de TVA mais ni code SDI ni PEC de facturation : ajoutez-les dans sa fiche.',
    destinatario: 'Facture électronique : {destinatario}',
    esenti: 'Débours exonérés art. 15',
    bolloRiga: 'Droit de timbre',
    nonAssoggettato: 'Vous n’êtes pas inscrit au registre TVA : la facture est émise sans TVA.',
    cambiaDati: 'Cela se modifie dans les données de facturation.',
    aliquota: 'Taux de TVA',
    aliquoteSpiega: 'Normal 8,1 %, réduit 2,6 %, hébergement 3,8 %.',
    motivo: "Motif de l'exonération (facultatif, figure sur la facture)",
    motivoEsempio: "Ex. Lieu de la prestation à l'étranger (art. 8 LTVA)",
    lingua: 'Langue de la facture',
    ibanQr:
      'Un QR-IBAN ne convient pas au virement : indiquez l’IBAN du compte dans les données de facturation.',
  },
  datiNuovi: {
    casse: {
      cassa_forense: 'Cassa Forense (C.P.A. 4 %)',
      cnpadc: 'CNPADC, experts-comptables (4 %)',
      cnpr: 'CNPR, comptables (4 %)',
      nessuna: 'Aucune caisse',
    },
    regimi: { RF01: 'Ordinaire (RF01)', RF19: 'Forfaitaire (RF19)' },
    sdi: 'Code destinataire SDI',
    paese: 'Pays',
    cantone: 'Canton',
    scegliCantone: 'Choisir le canton',
    ibanConto: 'IBAN du compte',
    qrIban: 'QR-IBAN (facultatif)',
    qrIbanTesto: 'Seulement si votre banque vous l’a donné : pour la QR-facture avec référence QR.',
    numeroIdi: 'Numéro IDE',
    esempioIdi: 'CHE-123.456.789',
    nonAssoggettato: 'Non assujetti : vos factures sont émises sans TVA.',
    errori: {
      iban: 'IBAN non valide : vérifiez les chiffres.',
      ibanQr: 'C’est un QR-IBAN : indiquez-le dans le champ QR-IBAN.',
      qrIban: 'Ce n’est pas un QR-IBAN suisse (banque entre 30000 et 31999).',
      idi: 'Numéro IDE non valide : CHE-123.456.789, avec le bon chiffre de contrôle.',
      idiObbligatorio: 'Si vous êtes assujetti à la TVA, le numéro IDE est nécessaire.',
      sdi: 'Le code SDI a 7 caractères, lettres et chiffres.',
      paese: 'Le pays s’écrit avec 2 lettres, par exemple CH.',
    },
  },
};

export const fatture = { it, de, fr };
