import type { Parziale } from '../tipi';

// Sezione «fatture»: elenco, dettaglio, nuova fattura, dati di fatturazione, totali e regole
// (src/studio/fatturazione.ts). Italiano di riferimento, poi tedesco svizzero («Sie», «ss») e francese («vous»).
// Termini svizzeri: IVA = MWST / TVA, QR-fattura = QR-Rechnung / QR-facture, esente = steuerbefreit / exonéré.
// Dove esiste, il testo viene dal sito svizzero (public/locales/*/avv_fatturazione*.json).
// Stati, metodi di pagamento e motivi d'esenzione si salvano in italiano: qui c'è solo come si mostrano.
// Le parti solo italiane (partita IVA, CPA, ritenuta, SDI) si vedono sempre in italiano: de e fr servono
// solo a tenere complete le lingue.

const it = {
  stati: {
    in_attesa: 'In attesa',
    scaduta: 'Scaduta',
    pagata: 'Pagata',
    annullata: 'Annullata',
  },
  quando: {
    emessaAnnullata: 'Emessa il {data} · annullata',
    pagataIl: 'Pagata il {data}',
    emessaIl: 'Emessa il {data}',
    scadutaIeri: 'Scaduta da ieri',
    scadutaDa: 'Scaduta da {n} giorni',
    scadeOggi: 'Scade oggi',
    scadeDomani: 'Scade domani',
    scadeTra: 'Scade tra {n} giorni',
    scadeIl: 'Scade il {data}',
  },
  manca: {
    partitaIva: 'partita IVA',
    codiceFiscale: 'codice fiscale',
    indirizzoStudio: 'indirizzo dello studio',
    regime: 'regime fiscale',
    iban: 'IBAN per la QR-fattura',
    assoggettato: 'se sei assoggettato all’IVA',
    numeroIva: 'numero IVA',
    indirizzo: 'indirizzo',
    e: 'e',
  },
  metodi: {
    bonifico: 'Bonifico',
    contanti: 'Contanti',
    carta: 'Carta',
    assegno: 'Assegno',
    qr: 'QR-fattura',
  },
  esenzione: {
    sottoSoglia: 'Non assoggettato all’IVA (cifra d’affari sotto CHF 100’000)',
    estero: 'Prestazione a un cliente all’estero (art. 8 LIVA)',
    esclusa: 'Prestazione esclusa dall’imposta (art. 21 LIVA)',
  },
  contributo: {
    cpa: 'CPA',
    integrativo: 'Contributo integrativo',
  },
  voci: {
    numero: 'Numero',
    cliente: 'Cliente',
    pratica: 'Pratica',
    emessa: 'Emessa',
    scadenza: 'Scadenza',
    prestazione: 'Prestazione',
    prestazioni: 'Prestazioni',
    pagamento: 'Pagamento',
    iban: 'IBAN',
    iva: 'IVA',
    esente: 'Esente',
  },
  scorciatoie: {
    oggi: 'Oggi',
    ieri: 'Ieri',
    traGiorni: 'Tra {n} giorni',
  },
  totali: {
    titolo: 'Totali',
    imponibile: 'Imponibile',
    iva: 'IVA {aliquota}',
    totaleFattura: 'Totale fattura',
    ritenuta: "Ritenuta d'acconto {aliquota}",
    netto: 'Netto a pagare',
    totale: 'Totale',
  },
  elenco: {
    titolo: 'Fatture',
    mancanoDati: 'Mancano i tuoi dati di fatturazione',
    completa: 'Completa',
    numeriAnno: 'I numeri del {anno}',
    fatturato: 'Fatturato',
    incassato: 'Incassato',
    daIncassare: 'Da incassare',
    scaduto: 'Scaduto',
    emesseNel: 'Fatture emesse nel {anno}',
    filtri: {
      daIncassare: 'Da incassare {n}',
      scadute: 'Scadute {n}',
      pagate: 'Pagate {n}',
      tutte: 'Tutte {n}',
    },
    vuoto: {
      nessuna: 'Nessuna fattura, per ora',
      nienteDaIncassare: 'Niente da incassare',
      nessunaQui: 'Nessuna fattura qui',
      crea: 'Crea la prima con «+» in alto.',
    },
    riga: 'Fattura {numero}, {cliente}, {importo}, {stato}',
  },
  dettaglio: {
    fattura: 'Fattura',
    nonCe: "Questa fattura non c'è più",
    tornaFatture: 'Torna alle fatture',
    altreAzioni: 'Altre azioni',
    restaDaIncassare: 'Resta da incassare',
    alNetto: "Al netto della ritenuta d'acconto: il cliente la versa al fisco.",
    pagamenti: 'Pagamenti',
    nessunPagamento: 'Nessun pagamento registrato.',
    residuo: 'Residuo',
    noSdi: 'Il PDF non è una fattura elettronica: non passa dal Sistema di Interscambio (SDI).',
    registraPagamento: 'Registra pagamento',
    generaPdf: 'Genera il PDF',
    fatturaNumero: 'Fattura {numero}',
    rigeneraPdf: 'Rigenera il PDF',
    rigeneraQuando: 'Dopo un pagamento o un cambio dei tuoi dati',
    annulla: 'Annulla la fattura',
    eliminaSulSito: 'Per eliminare una fattura vai sul sito: si può, ma lascia un vuoto nella numerazione.',
    annullareDomanda: 'Annullare la fattura {numero}?',
    annullareTesto: "Resta nell'elenco come annullata e il suo numero non si usa più. Non si torna indietro.",
    lasciala: "Lasciala com'è",
    generato: 'Generato · {data}',
    condividi: 'Condividi',
    apriPdf: 'Apri il PDF',
  },
  pagamento: {
    titolo: 'Registra un pagamento',
    residuo: 'Residuo: {importo}. Puoi registrare anche un pagamento parziale.',
    importo: 'Importo ({valuta})',
    erroreImporto: 'Scrivi un importo, per esempio 250,00.',
    piuDelResiduo: 'È più del residuo ({importo}).',
    metodo: 'Metodo',
    data: "Data dell'incasso",
    registra: 'Registra il pagamento',
  },
  nuova: {
    titolo: 'Nuova fattura',
    passo: 'Passo {n} di {totale} · {nome}',
    passi: {
      cliente: 'Cliente',
      prestazioni: 'Prestazioni',
      fisco: 'Fisco e pagamento',
      controlla: 'Controlla',
    },
    servonoDati: 'Prima servono i tuoi dati di fatturazione',
    mancanoDati: 'Mancano {elenco}. Vanno sul PDF di ogni fattura: li scrivi una volta sola.',
    completaDati: 'Completa i dati di fatturazione',
    blocchi: {
      cliente: 'Scegli il cliente.',
      datiCliente: 'Completa i dati del cliente sul sito.',
      prestazione: 'Aggiungi almeno una prestazione.',
      zero: 'Il totale è zero.',
      emissione: 'Scrivi la data di emissione.',
      scadenzaPrima: 'La scadenza viene prima dell’emissione.',
      percentuali: 'Controlla le percentuali.',
      periodo: 'Scrivi la data o il periodo della prestazione.',
      motivo: 'Scegli il motivo dell’esenzione.',
      iban: 'Manca il tuo IBAN.',
    },
    mancanoCliente: 'A {nome} mancano {elenco}. Si aggiungono sul sito, in Clienti: poi torna qui.',
    righePronte: 'Le righe della parcella sono pronte: scegli il cliente.',
    praticaFacoltativa: 'Pratica (facoltativa)',
    togli: 'Togli «{descrizione}»',
    nessunaPrestazione: 'Nessuna prestazione, per ora.',
    aggiungiPrestazione: 'Aggiungi una prestazione',
    descrizione: 'Descrizione',
    esempioDescrizione: {
      IT: 'Es. Parere scritto',
      CH: 'Es. Consulenza (ore)',
    },
    quantita: 'Quantità',
    prezzo: 'Prezzo ({valuta})',
    aggiungiLaPrestazione: 'Aggiungi la prestazione',
    forfettario:
      'Regime forfettario: la fattura è senza IVA e senza ritenuta. Sopra 77,47 € va la marca da bollo da 2 €.',
    ivaPercento: 'IVA (%)',
    ritenuta: "Ritenuta d'acconto 20%",
    ritenutaSpiega: "Se il cliente è un'azienda o un professionista: la versa lui al fisco",
    motivo: "Motivo dell'esenzione (va sulla fattura)",
    motivoGruppo: "Motivo dell'esenzione",
    periodo: 'Data o periodo della prestazione',
    esempioPeriodo: 'Es. settembre 2026',
    mesePrestazione: 'Mese della prestazione',
    periodoLegge: "La chiede la legge sull'IVA (art. 26 LIVA).",
    emessaIl: 'Emessa il',
    scadenzaPagamento: 'Scadenza del pagamento',
    sulPdf: 'Sul PDF: IBAN {iban}.',
    sulPdfQr: 'Sul PDF: IBAN {iban}, con la sezione di pagamento QR.',
    mancaIban: 'Manca il tuo IBAN: aggiungilo nei dati di fatturazione.',
    note: 'Note sulla fattura (facoltative)',
    noteSegnaposto: 'Le legge anche il cliente',
    prestazioniN: 'Prestazioni · {n}',
    notaFinale: {
      IT: 'Il numero si assegna quando la crei. Il PDF lo generi dal dettaglio.',
      CH: 'Il numero si assegna quando la crei. Il PDF, con la QR-fattura, lo generi dal dettaglio.',
    },
    crea: 'Crea la fattura',
  },
  dati: {
    titolo: 'Dati di fatturazione',
    intro: 'Vanno sul PDF di ogni fattura. Sono gli stessi del sito: li cambi qui e cambiano anche lì.',
    datiFiscali: 'Dati fiscali',
    partitaIva: 'Partita IVA',
    undiciCifre: '11 cifre',
    codiceFiscale: 'Codice fiscale',
    regime: 'Regime fiscale',
    ordinario: 'Ordinario',
    forfettario: 'Forfettario',
    cassa: 'Cassa di previdenza',
    indirizzo: 'Indirizzo dello studio',
    via: 'Via',
    civico: 'Numero',
    cap: { IT: 'CAP', CH: 'NPA' },
    citta: { IT: 'Comune', CH: 'Località' },
    provincia: 'Provincia',
    iban: { IT: 'IBAN', CH: 'IBAN o QR-IBAN' },
    qrIban: 'È un QR-IBAN: la QR-fattura avrà un riferimento QR.',
    sullaQr: 'Va sulla QR-fattura, la sezione di pagamento in fondo al PDF.',
    assoggettatoDomanda: "Sei assoggettato all'IVA?",
    assoggettato: "Assoggettato all'IVA",
    si: 'Sì',
    no: 'No',
    esenti: 'Le tue fatture saranno esenti, con il motivo scritto in fattura.',
    obbligo: 'Obbligatorio da CHF 100’000 di cifra d’affari all’anno.',
    numeroIva: 'Numero IVA',
    esempioNumeroIva: 'CHE-123.456.789 IVA',
    salva: 'Salva',
    errori: {
      piva: 'La partita IVA ha 11 cifre: controlla.',
      cf: 'Il codice fiscale ha 16 caratteri (o 11 cifre).',
      provincia: 'La sigla ha due lettere, per esempio MI.',
      numeroIva: 'Si scrive così: CHE-123.456.789 IVA.',
      cap: { IT: 'Il CAP ha 5 cifre.', CH: 'Il NPA ha 4 cifre.' },
      iban: {
        IT: 'L’IBAN italiano ha 27 caratteri e inizia con IT.',
        CH: 'L’IBAN svizzero ha 21 caratteri e inizia con CH.',
      },
    },
  },
};

const de: Parziale<typeof it> = {
  stati: {
    in_attesa: 'Ausstehend',
    scaduta: 'Überfällig',
    pagata: 'Bezahlt',
    annullata: 'Storniert',
  },
  quando: {
    emessaAnnullata: 'Ausgestellt am {data} · storniert',
    pagataIl: 'Bezahlt am {data}',
    emessaIl: 'Ausgestellt am {data}',
    scadutaIeri: 'Seit gestern überfällig',
    scadutaDa: 'Seit {n} Tagen überfällig',
    scadeOggi: 'Heute fällig',
    scadeDomani: 'Morgen fällig',
    scadeTra: 'Fällig in {n} Tagen',
    scadeIl: 'Fällig am {data}',
  },
  manca: {
    partitaIva: 'MWST-Nummer (Partita IVA)',
    codiceFiscale: 'Steuernummer (Codice fiscale)',
    indirizzoStudio: 'Geschäftsadresse',
    regime: 'Steuerregime',
    iban: 'IBAN für die QR-Rechnung',
    assoggettato: 'ob Sie mehrwertsteuerpflichtig sind',
    numeroIva: 'MWST-Nummer',
    indirizzo: 'Adresse',
    e: 'und',
  },
  metodi: {
    bonifico: 'Überweisung',
    contanti: 'Bar',
    carta: 'Karte',
    assegno: 'Scheck',
    qr: 'QR-Rechnung',
  },
  esenzione: {
    sottoSoglia: 'Nicht mehrwertsteuerpflichtig (Umsatz unter CHF 100’000)',
    estero: 'Leistung an einen Mandanten im Ausland (Art. 8 MWSTG)',
    esclusa: 'Von der Steuer ausgenommene Leistung (Art. 21 MWSTG)',
  },
  contributo: {
    cpa: 'CPA',
    integrativo: 'Integrativbeitrag',
  },
  voci: {
    numero: 'Nummer',
    cliente: 'Mandant',
    pratica: 'Dossier',
    emessa: 'Ausgestellt',
    scadenza: 'Fälligkeit',
    prestazione: 'Leistung',
    prestazioni: 'Leistungen',
    pagamento: 'Zahlung',
    iban: 'IBAN',
    iva: 'MWST',
    esente: 'Steuerbefreit',
  },
  scorciatoie: {
    oggi: 'Heute',
    ieri: 'Gestern',
    traGiorni: 'In {n} Tagen',
  },
  totali: {
    titolo: 'Zusammenfassung',
    imponibile: 'Nettobetrag',
    iva: 'MWST {aliquota}',
    totaleFattura: 'Rechnungsbetrag',
    ritenuta: 'Quellensteuer {aliquota}',
    netto: 'Netto zu bezahlen',
    totale: 'Total',
  },
  elenco: {
    titolo: 'Rechnungen',
    mancanoDati: 'Ihre Rechnungsdaten fehlen',
    completa: 'Ergänzen',
    numeriAnno: 'Die Zahlen {anno}',
    fatturato: 'Umsatz',
    incassato: 'Eingegangen',
    daIncassare: 'Ausstehend',
    scaduto: 'Überfällig',
    emesseNel: 'Im Jahr {anno} ausgestellte Rechnungen',
    filtri: {
      daIncassare: 'Ausstehend {n}',
      scadute: 'Überfällig {n}',
      pagate: 'Bezahlt {n}',
      tutte: 'Alle {n}',
    },
    vuoto: {
      nessuna: 'Noch keine Rechnungen',
      nienteDaIncassare: 'Nichts ausstehend',
      nessunaQui: 'Keine Rechnungen hier',
      crea: 'Erstellen Sie die erste mit «+» oben.',
    },
    riga: 'Rechnung {numero}, {cliente}, {importo}, {stato}',
  },
  dettaglio: {
    fattura: 'Rechnung',
    nonCe: 'Diese Rechnung gibt es nicht mehr',
    tornaFatture: 'Zurück zu den Rechnungen',
    altreAzioni: 'Weitere Aktionen',
    restaDaIncassare: 'Noch offen',
    alNetto: 'Ohne Quellensteuer: Der Mandant zahlt sie direkt an die Steuerbehörde.',
    pagamenti: 'Zahlungen',
    nessunPagamento: 'Keine Zahlung erfasst.',
    residuo: 'Offener Betrag',
    noSdi: 'Das PDF ist keine elektronische Rechnung: Es läuft nicht über das Sistema di Interscambio (SDI).',
    registraPagamento: 'Zahlung erfassen',
    generaPdf: 'PDF erstellen',
    fatturaNumero: 'Rechnung {numero}',
    rigeneraPdf: 'PDF neu erstellen',
    rigeneraQuando: 'Nach einer Zahlung oder wenn sich Ihre Daten ändern',
    annulla: 'Rechnung stornieren',
    eliminaSulSito:
      'Um eine Rechnung zu löschen, gehen Sie auf die Website: Das geht, hinterlässt aber eine Lücke in der Nummerierung.',
    annullareDomanda: 'Rechnung {numero} stornieren?',
    annullareTesto:
      'Sie bleibt als storniert in der Liste, und ihre Nummer wird nicht mehr verwendet. Das lässt sich nicht rückgängig machen.',
    lasciala: 'So belassen',
    generato: 'Erstellt · {data}',
    condividi: 'Teilen',
    apriPdf: 'PDF öffnen',
  },
  pagamento: {
    titolo: 'Eine Zahlung erfassen',
    residuo: 'Offen: {importo}. Sie können auch eine Teilzahlung erfassen.',
    importo: 'Betrag ({valuta})',
    erroreImporto: 'Geben Sie einen Betrag ein, zum Beispiel 250.00.',
    piuDelResiduo: 'Das ist mehr als der offene Betrag ({importo}).',
    metodo: 'Zahlungsart',
    data: 'Eingangsdatum',
    registra: 'Zahlung speichern',
  },
  nuova: {
    titolo: 'Neue Rechnung',
    passo: 'Schritt {n} von {totale} · {nome}',
    passi: {
      cliente: 'Mandant',
      prestazioni: 'Leistungen',
      fisco: 'Steuern und Zahlung',
      controlla: 'Prüfen',
    },
    servonoDati: 'Zuerst braucht es Ihre Rechnungsdaten',
    mancanoDati:
      'Es fehlen: {elenco}. Diese Angaben stehen auf dem PDF jeder Rechnung: Sie erfassen sie nur einmal.',
    completaDati: 'Rechnungsdaten ergänzen',
    blocchi: {
      cliente: 'Wählen Sie den Mandanten.',
      datiCliente: 'Ergänzen Sie die Daten des Mandanten auf der Website.',
      prestazione: 'Fügen Sie mindestens eine Leistung hinzu.',
      zero: 'Das Total ist null.',
      emissione: 'Geben Sie das Rechnungsdatum ein.',
      scadenzaPrima: 'Die Fälligkeit liegt vor dem Rechnungsdatum.',
      percentuali: 'Prüfen Sie die Prozentsätze.',
      periodo: 'Geben Sie das Datum oder den Zeitraum der Leistung ein.',
      motivo: 'Wählen Sie den Grund der Steuerbefreiung.',
      iban: 'Ihre IBAN fehlt.',
    },
    mancanoCliente:
      'Bei {nome} fehlen: {elenco}. Sie ergänzen das auf der Website unter «Mandanten» und kommen dann hierher zurück.',
    righePronte: 'Die Positionen der Honorarnote sind bereit: Wählen Sie den Mandanten.',
    praticaFacoltativa: 'Dossier (optional)',
    togli: '«{descrizione}» entfernen',
    nessunaPrestazione: 'Noch keine Leistung.',
    aggiungiPrestazione: 'Neue Leistung',
    descrizione: 'Beschreibung',
    esempioDescrizione: {
      IT: 'Z. B. Schriftliches Gutachten',
      CH: 'Z. B. Beratung (Stunden)',
    },
    quantita: 'Menge',
    prezzo: 'Preis ({valuta})',
    aggiungiLaPrestazione: 'Leistung hinzufügen',
    forfettario:
      'Pauschalregime: Die Rechnung ist ohne MWST und ohne Quellensteuer. Über 77,47 € braucht es eine Stempelmarke von 2 €.',
    ivaPercento: 'MWST (%)',
    ritenuta: 'Quellensteuer 20%',
    ritenutaSpiega:
      'Wenn der Mandant ein Unternehmen oder eine Fachperson ist: Er zahlt sie an die Steuerbehörde',
    motivo: 'Grund der Steuerbefreiung (steht auf der Rechnung)',
    motivoGruppo: 'Grund der Steuerbefreiung',
    periodo: 'Datum oder Zeitraum der Leistung',
    esempioPeriodo: 'Z. B. September 2026',
    mesePrestazione: 'Monat der Leistung',
    periodoLegge: 'Das verlangt das Mehrwertsteuergesetz (Art. 26 MWSTG).',
    emessaIl: 'Ausgestellt am',
    scadenzaPagamento: 'Zahlungsfrist',
    sulPdf: 'Auf dem PDF: IBAN {iban}.',
    sulPdfQr: 'Auf dem PDF: IBAN {iban}, mit dem QR-Zahlteil.',
    mancaIban: 'Ihre IBAN fehlt: Ergänzen Sie sie in den Rechnungsdaten.',
    note: 'Bemerkungen auf der Rechnung (optional)',
    noteSegnaposto: 'Auch der Mandant liest sie',
    prestazioniN: 'Leistungen · {n}',
    notaFinale: {
      IT: 'Die Nummer wird beim Erstellen vergeben. Das PDF erstellen Sie in der Detailansicht.',
      CH: 'Die Nummer wird beim Erstellen vergeben. Das PDF mit der QR-Rechnung erstellen Sie in der Detailansicht.',
    },
    crea: 'Rechnung erstellen',
  },
  dati: {
    titolo: 'Rechnungsdaten',
    intro:
      'Sie stehen auf dem PDF jeder Rechnung. Es sind dieselben wie auf der Website: Ändern Sie sie hier, ändern sie sich auch dort.',
    datiFiscali: 'Steuerdaten',
    partitaIva: 'MWST-Nummer (Partita IVA)',
    undiciCifre: '11 Ziffern',
    codiceFiscale: 'Steuernummer (Codice fiscale)',
    regime: 'Steuerregime',
    ordinario: 'Ordentlich',
    forfettario: 'Pauschal',
    cassa: 'Vorsorgekasse',
    indirizzo: 'Geschäftsadresse',
    via: 'Strasse',
    civico: 'Nr.',
    cap: { IT: 'PLZ', CH: 'PLZ' },
    citta: { IT: 'Gemeinde', CH: 'Ort' },
    provincia: 'Provinz',
    iban: { IT: 'IBAN', CH: 'IBAN oder QR-IBAN' },
    qrIban: 'Das ist eine QR-IBAN: Die QR-Rechnung erhält eine QR-Referenz.',
    sullaQr: 'Sie steht auf der QR-Rechnung, dem Zahlteil unten im PDF.',
    assoggettatoDomanda: 'Sind Sie mehrwertsteuerpflichtig?',
    assoggettato: 'Mehrwertsteuerpflichtig',
    si: 'Ja',
    no: 'Nein',
    esenti: 'Ihre Rechnungen sind dann steuerbefreit, mit dem Grund auf der Rechnung.',
    obbligo: 'Pflicht ab CHF 100’000 Umsatz pro Jahr.',
    numeroIva: 'MWST-Nummer',
    esempioNumeroIva: 'CHE-123.456.789 MWST',
    salva: 'Speichern',
    errori: {
      piva: 'Die Partita IVA hat 11 Ziffern: Bitte prüfen.',
      cf: 'Der Codice fiscale hat 16 Zeichen (oder 11 Ziffern).',
      provincia: 'Das Kürzel hat zwei Buchstaben, zum Beispiel MI.',
      numeroIva: 'So schreiben Sie sie: CHE-123.456.789 MWST.',
      cap: { IT: 'Die PLZ hat 5 Ziffern.', CH: 'Die PLZ hat 4 Ziffern.' },
      iban: {
        IT: 'Die italienische IBAN hat 27 Zeichen und beginnt mit IT.',
        CH: 'Die Schweizer IBAN hat 21 Zeichen und beginnt mit CH.',
      },
    },
  },
};

const fr: Parziale<typeof it> = {
  stati: {
    in_attesa: 'En attente',
    scaduta: 'Échue',
    pagata: 'Payée',
    annullata: 'Annulée',
  },
  quando: {
    emessaAnnullata: 'Émise le {data} · annulée',
    pagataIl: 'Payée le {data}',
    emessaIl: 'Émise le {data}',
    scadutaIeri: 'Échue depuis hier',
    scadutaDa: 'Échue depuis {n} jours',
    scadeOggi: "Échéance aujourd'hui",
    scadeDomani: 'Échéance demain',
    scadeTra: 'Échéance dans {n} jours',
    scadeIl: 'Échéance le {data}',
  },
  manca: {
    partitaIva: 'numéro TVA (partita IVA)',
    codiceFiscale: 'code fiscal (codice fiscale)',
    indirizzoStudio: 'adresse professionnelle',
    regime: 'régime fiscal',
    iban: 'IBAN pour la QR-facture',
    assoggettato: 'si vous êtes assujetti à la TVA',
    numeroIva: 'numéro TVA',
    indirizzo: 'adresse',
    e: 'et',
  },
  metodi: {
    bonifico: 'Virement',
    contanti: 'Espèces',
    carta: 'Carte',
    assegno: 'Chèque',
    qr: 'QR-facture',
  },
  esenzione: {
    sottoSoglia: "Non assujetti à la TVA (chiffre d'affaires inférieur à CHF 100’000)",
    estero: "Prestation à un client à l'étranger (art. 8 LTVA)",
    esclusa: "Prestation exclue du champ de l'impôt (art. 21 LTVA)",
  },
  contributo: {
    cpa: 'CPA',
    integrativo: 'Contribution intégrative',
  },
  voci: {
    numero: 'Numéro',
    cliente: 'Client',
    pratica: 'Dossier',
    emessa: 'Émise',
    scadenza: 'Échéance',
    prestazione: 'Prestation',
    prestazioni: 'Prestations',
    pagamento: 'Paiement',
    iban: 'IBAN',
    iva: 'TVA',
    esente: 'Exonérée',
  },
  scorciatoie: {
    oggi: "Aujourd'hui",
    ieri: 'Hier',
    traGiorni: 'Dans {n} jours',
  },
  totali: {
    titolo: 'Récapitulatif',
    imponibile: 'Montant net',
    iva: 'TVA {aliquota}',
    totaleFattura: 'Total de la facture',
    ritenuta: 'Retenue à la source {aliquota}',
    netto: 'Net à payer',
    totale: 'Total',
  },
  elenco: {
    titolo: 'Factures',
    mancanoDati: 'Vos données de facturation manquent',
    completa: 'Compléter',
    numeriAnno: 'Les chiffres {anno}',
    fatturato: 'Facturé',
    incassato: 'Encaissé',
    daIncassare: 'À encaisser',
    scaduto: 'Échu',
    emesseNel: 'Factures émises en {anno}',
    filtri: {
      daIncassare: 'À encaisser {n}',
      scadute: 'Échues {n}',
      pagate: 'Payées {n}',
      tutte: 'Toutes {n}',
    },
    vuoto: {
      nessuna: 'Aucune facture pour le moment',
      nienteDaIncassare: 'Rien à encaisser',
      nessunaQui: 'Aucune facture ici',
      crea: 'Créez la première avec « + » en haut.',
    },
    riga: 'Facture {numero}, {cliente}, {importo}, {stato}',
  },
  dettaglio: {
    fattura: 'Facture',
    nonCe: "Cette facture n'existe plus",
    tornaFatture: 'Retour aux factures',
    altreAzioni: 'Autres actions',
    restaDaIncassare: 'Reste à encaisser',
    alNetto: 'Hors retenue à la source : le client la verse directement au fisc.',
    pagamenti: 'Paiements',
    nessunPagamento: 'Aucun paiement enregistré.',
    residuo: 'Solde',
    noSdi:
      "Le PDF n'est pas une facture électronique : il ne passe pas par le Sistema di Interscambio (SDI).",
    registraPagamento: 'Enregistrer un paiement',
    generaPdf: 'Générer le PDF',
    fatturaNumero: 'Facture {numero}',
    rigeneraPdf: 'Régénérer le PDF',
    rigeneraQuando: 'Après un paiement ou une modification de vos données',
    annulla: 'Annuler la facture',
    eliminaSulSito:
      "Pour supprimer une facture, allez sur le site : c'est possible, mais cela laisse un trou dans la numérotation.",
    annullareDomanda: 'Annuler la facture {numero} ?',
    annullareTesto:
      "Elle reste dans la liste comme annulée et son numéro n'est plus utilisé. C'est définitif.",
    lasciala: 'La laisser telle quelle',
    generato: 'Généré · {data}',
    condividi: 'Partager',
    apriPdf: 'Ouvrir le PDF',
  },
  pagamento: {
    titolo: 'Enregistrer un paiement',
    residuo: 'Solde : {importo}. Vous pouvez aussi enregistrer un paiement partiel.',
    importo: 'Montant ({valuta})',
    erroreImporto: 'Saisissez un montant, par exemple 250.00.',
    piuDelResiduo: "C'est plus que le solde ({importo}).",
    metodo: 'Mode de paiement',
    data: "Date de l'encaissement",
    registra: 'Enregistrer le paiement',
  },
  nuova: {
    titolo: 'Nouvelle facture',
    passo: 'Étape {n} sur {totale} · {nome}',
    passi: {
      cliente: 'Client',
      prestazioni: 'Prestations',
      fisco: 'Impôts et paiement',
      controlla: 'Vérifier',
    },
    servonoDati: "Il faut d'abord vos données de facturation",
    mancanoDati:
      "Il manque : {elenco}. Ces données figurent sur le PDF de chaque facture : vous ne les saisissez qu'une fois.",
    completaDati: 'Compléter les données de facturation',
    blocchi: {
      cliente: 'Choisissez le client.',
      datiCliente: 'Complétez les données du client sur le site.',
      prestazione: 'Ajoutez au moins une prestation.',
      zero: 'Le total est de zéro.',
      emissione: "Saisissez la date d'émission.",
      scadenzaPrima: "L'échéance est antérieure à l'émission.",
      percentuali: 'Vérifiez les pourcentages.',
      periodo: 'Saisissez la date ou la période de la prestation.',
      motivo: "Choisissez le motif de l'exonération.",
      iban: 'Votre IBAN manque.',
    },
    mancanoCliente:
      'Pour {nome}, il manque : {elenco}. Vous les ajoutez sur le site, dans « Clients », puis revenez ici.',
    righePronte: "Les lignes de la note d'honoraires sont prêtes : choisissez le client.",
    praticaFacoltativa: 'Dossier (facultatif)',
    togli: 'Retirer « {descrizione} »',
    nessunaPrestazione: 'Aucune prestation pour le moment.',
    aggiungiPrestazione: 'Nouvelle prestation',
    descrizione: 'Description',
    esempioDescrizione: {
      IT: 'P. ex. avis écrit',
      CH: 'P. ex. conseil (heures)',
    },
    quantita: 'Quantité',
    prezzo: 'Prix ({valuta})',
    aggiungiLaPrestazione: 'Ajouter la prestation',
    forfettario:
      'Régime forfaitaire : la facture est sans TVA et sans retenue à la source. Au-delà de 77,47 €, un timbre fiscal de 2 € est dû.',
    ivaPercento: 'TVA (%)',
    ritenuta: 'Retenue à la source 20%',
    ritenutaSpiega: "Si le client est une entreprise ou un professionnel : c'est lui qui la verse au fisc",
    motivo: "Motif de l'exonération (figure sur la facture)",
    motivoGruppo: "Motif de l'exonération",
    periodo: 'Date ou période de la prestation',
    esempioPeriodo: 'P. ex. septembre 2026',
    mesePrestazione: 'Mois de la prestation',
    periodoLegge: "La loi sur la TVA l'exige (art. 26 LTVA).",
    emessaIl: 'Émise le',
    scadenzaPagamento: 'Délai de paiement',
    sulPdf: 'Sur le PDF : IBAN {iban}.',
    sulPdfQr: 'Sur le PDF : IBAN {iban}, avec la section paiement QR.',
    mancaIban: 'Votre IBAN manque : ajoutez-le dans les données de facturation.',
    note: 'Remarques sur la facture (facultatives)',
    noteSegnaposto: 'Le client les lit aussi',
    prestazioniN: 'Prestations · {n}',
    notaFinale: {
      IT: 'Le numéro est attribué à la création. Vous générez le PDF depuis le détail.',
      CH: 'Le numéro est attribué à la création. Vous générez le PDF, avec la QR-facture, depuis le détail.',
    },
    crea: 'Créer la facture',
  },
  dati: {
    titolo: 'Données de facturation',
    intro:
      'Elles figurent sur le PDF de chaque facture. Ce sont les mêmes que sur le site : si vous les modifiez ici, elles changent aussi là-bas.',
    datiFiscali: 'Données fiscales',
    partitaIva: 'Numéro TVA (partita IVA)',
    undiciCifre: '11 chiffres',
    codiceFiscale: 'Code fiscal (codice fiscale)',
    regime: 'Régime fiscal',
    ordinario: 'Ordinaire',
    forfettario: 'Forfaitaire',
    cassa: 'Caisse de prévoyance',
    indirizzo: 'Adresse professionnelle',
    via: 'Rue',
    civico: 'N°',
    cap: { IT: 'Code postal', CH: 'NPA' },
    citta: { IT: 'Commune', CH: 'Localité' },
    provincia: 'Province',
    iban: { IT: 'IBAN', CH: 'IBAN ou QR-IBAN' },
    qrIban: "C'est un QR-IBAN : la QR-facture aura une référence QR.",
    sullaQr: 'Il figure sur la QR-facture, la section paiement en bas du PDF.',
    assoggettatoDomanda: 'Êtes-vous assujetti à la TVA ?',
    assoggettato: 'Assujetti à la TVA',
    si: 'Oui',
    no: 'Non',
    esenti: 'Vos factures seront exonérées, avec le motif indiqué sur la facture.',
    obbligo: "Obligatoire dès CHF 100’000 de chiffre d'affaires par an.",
    numeroIva: 'Numéro TVA',
    esempioNumeroIva: 'CHE-123.456.789 TVA',
    salva: 'Enregistrer',
    errori: {
      piva: 'La partita IVA compte 11 chiffres : vérifiez-la.',
      cf: 'Le code fiscal compte 16 caractères (ou 11 chiffres).',
      provincia: 'Le sigle compte deux lettres, par exemple MI.',
      numeroIva: "S'écrit ainsi : CHE-123.456.789 TVA.",
      cap: { IT: 'Le code postal compte 5 chiffres.', CH: 'Le NPA compte 4 chiffres.' },
      iban: {
        IT: "L'IBAN italien compte 27 caractères et commence par IT.",
        CH: "L'IBAN suisse compte 21 caractères et commence par CH.",
      },
    },
  },
};

export const fatture = { it, de, fr };
