import type { Parziale } from '../tipi';

// Pezzi comuni dell'interfaccia: intestazione, menù laterale, compositore, stati, fogli.

const it = {
  apriMenu: 'Apri il menù',
  chiudiMenu: 'Chiudi il menù',
  menu: 'Menù',
  indietro: 'Indietro',
  chiudi: 'Chiudi',
  cancellaRicerca: 'Cancella la ricerca',
  mostraPassword: 'Mostra la password',
  nascondiPassword: 'Nascondi la password',
  caricamento: 'Caricamento in corso',
  offline: 'Sei senza connessione. Lex e la Banca dati tornano appena sei online.',
  crediti: {
    nessuno: 'Nessun credito disponibile',
    uno: '1 credito disponibile',
    molti: '{n} crediti disponibili',
    breveUno: '1 credito',
    breveMolti: '{n} crediti',
  },
  compositore: {
    segnaposto: 'Racconta il tuo caso a Lex…',
    lavora: 'Lex sta lavorando…',
    offline: 'Senza connessione: Lex torna appena sei online',
    scrivi: 'Scrivi a Lex',
    allega: 'Allega un documento',
    invia: 'Invia',
    nota: 'Lex può commettere errori: verifica sempre le fonti citate.',
  },
  lex: { inBreve: 'In breve:' },
  voci: {
    nuovaChat: 'Nuova chat',
    bancaDati: 'Banca dati',
    ricerche: 'Ricerche',
    archivio: 'Archivio',
    domande: 'Domande',
    profilo: 'Profilo',
    dashboard: 'Dashboard',
    clienti: 'Clienti',
    pratiche: 'Pratiche',
    calendario: 'Calendario',
    fatture: 'Fatture',
    studio: 'Studio',
    lexum: 'Lexum',
    etichette: 'Etichette',
    etichetteVuote: 'Le etichette che crei salvando le chat compaiono qui.',
    etichetta: 'Etichetta {nome}, {n} elementi',
    apriProfilo: 'Apri il profilo',
  },
};

const de: Parziale<typeof it> = {
  apriMenu: 'Menü öffnen',
  chiudiMenu: 'Menü schliessen',
  menu: 'Menü',
  indietro: 'Zurück',
  chiudi: 'Schliessen',
  cancellaRicerca: 'Suche löschen',
  mostraPassword: 'Passwort anzeigen',
  nascondiPassword: 'Passwort verbergen',
  caricamento: 'Wird geladen',
  offline: 'Sie sind offline. Lex und die Datenbank sind wieder da, sobald Sie online sind.',
  crediti: {
    nessuno: 'Kein Credit verfügbar',
    uno: '1 Credit verfügbar',
    molti: '{n} Credits verfügbar',
    breveUno: '1 Credit',
    breveMolti: '{n} Credits',
  },
  compositore: {
    segnaposto: 'Schildern Sie Lex Ihren Fall…',
    lavora: 'Lex arbeitet…',
    offline: 'Keine Verbindung: Lex ist zurück, sobald Sie online sind',
    scrivi: 'An Lex schreiben',
    allega: 'Dokument anhängen',
    invia: 'Senden',
    nota: 'Lex kann Fehler machen: Prüfen Sie immer die zitierten Quellen.',
  },
  lex: { inBreve: 'Kurz gesagt:' },
  voci: {
    nuovaChat: 'Neuer Chat',
    bancaDati: 'Datenbank',
    ricerche: 'Recherchen',
    archivio: 'Archiv',
    domande: 'Fragen',
    profilo: 'Profil',
    dashboard: 'Dashboard',
    clienti: 'Mandanten',
    pratiche: 'Dossiers',
    calendario: 'Kalender',
    fatture: 'Rechnungen',
    studio: 'Kanzlei',
    lexum: 'Lexum',
    etichette: 'Etiketten',
    etichetteVuote: 'Die Etiketten, die Sie beim Speichern von Chats erstellen, erscheinen hier.',
    etichetta: 'Etikett {nome}, {n} Elemente',
    apriProfilo: 'Profil öffnen',
  },
};

const fr: Parziale<typeof it> = {
  apriMenu: 'Ouvrir le menu',
  chiudiMenu: 'Fermer le menu',
  menu: 'Menu',
  indietro: 'Retour',
  chiudi: 'Fermer',
  cancellaRicerca: 'Effacer la recherche',
  mostraPassword: 'Afficher le mot de passe',
  nascondiPassword: 'Masquer le mot de passe',
  caricamento: 'Chargement en cours',
  offline: 'Vous êtes hors ligne. Lex et la base de données reviennent dès que vous êtes en ligne.',
  crediti: {
    nessuno: 'Aucun crédit disponible',
    uno: '1 crédit disponible',
    molti: '{n} crédits disponibles',
    breveUno: '1 crédit',
    breveMolti: '{n} crédits',
  },
  compositore: {
    segnaposto: 'Racontez votre cas à Lex…',
    lavora: 'Lex travaille…',
    offline: 'Hors ligne : Lex revient dès que vous êtes en ligne',
    scrivi: 'Écrire à Lex',
    allega: 'Joindre un document',
    invia: 'Envoyer',
    nota: 'Lex peut se tromper : vérifiez toujours les sources citées.',
  },
  lex: { inBreve: 'En bref :' },
  voci: {
    nuovaChat: 'Nouveau chat',
    bancaDati: 'Base de données',
    ricerche: 'Recherches',
    archivio: 'Archives',
    domande: 'Questions',
    profilo: 'Profil',
    dashboard: 'Tableau de bord',
    clienti: 'Clients',
    pratiche: 'Dossiers',
    calendario: 'Calendrier',
    fatture: 'Factures',
    studio: 'Étude',
    lexum: 'Lexum',
    etichette: 'Étiquettes',
    etichetteVuote: 'Les étiquettes que vous créez en enregistrant les chats apparaissent ici.',
    etichetta: 'Étiquette {nome}, {n} éléments',
    apriProfilo: 'Ouvrir le profil',
  },
};

export const interfaccia = { it, de, fr };
