import type { Parziale } from '../tipi';

// Sezione «ricerche»: italiano di riferimento, poi tedesco svizzero («Sie», «ss») e francese («vous»).
// Ricerche (D1), confronto, chat salvata e i fogli delle etichette, della nuova ricerca e degli appunti.
// Dove c'era già, il testo tedesco e francese viene da lexum.ch (user_ricerche.json).

const it = {
  titolo: 'Ricerche',
  nuova: 'Nuova ricerca',
  intro: 'Tutto quello che hai chiesto a Lex e salvato: chat, appunti, norme, sentenze e prassi.',
  copiaOffline: 'Senza rete: stai leggendo la copia salvata sul telefono.',
  cerca: 'Cerca tra le tue ricerche',
  cercaSegnaposto: 'Cerca tra le tue ricerche…',
  etichetta: 'Etichetta',
  nuovaEtichetta: 'Nuova etichetta',
  gestisci: 'Gestisci etichette',
  sceltaConfronto: 'Scegli da 2 a {max} elementi, anche da etichette diverse · {n} / {max} selezionati',
  didascalia: 'Etichetta «{nome}» · {elementi}',
  elementiUno: '1 elemento',
  elementiMolti: '{n} elementi',
  offlineTitolo: 'Ricerche si apre con la connessione',
  offlineTesto:
    'Per leggere chat, norme e appunti salvati anche senza rete, accendi «Ricerche anche senza rete» nel Profilo.',
  vaiProfilo: 'Vai al Profilo',
  vuotoTitolo: 'Non hai ancora salvato niente',
  vuotoTesto: "Quando una risposta di Lex ti serve, salvala con un'etichetta: la ritrovi qui e sul sito.",
  chiedi: 'Chiedi a Lex',
  chiediSu: 'Chiedi a Lex su «{nome}»',
  nessunRisultatoTitolo: 'Nessun elemento con queste parole',
  nessunRisultatoTesto: 'Prova con altre parole.',
  etichettaVuotaTitolo: "In questa etichetta non c'è ancora niente",
  etichettaVuotaTesto: 'Salva qui chat, norme e sentenze, o scrivi i tuoi appunti con «+».',
  confronta: 'Confronta',
  confrontaDueOTre: 'Confronta due o tre elementi',
  confrontaAffiancati: 'Confronta affiancati',
  normaSalvata: 'Norma salvata',
  tornaRicerche: 'Torna a Ricerche',
  // Il tipo di ogni elemento salvato (la chiave è il tipo dei dati).
  tipi: {
    'Chat con Lex': 'Chat con Lex',
    Norma: 'Norma',
    Sentenza: 'Sentenza',
    Appunti: 'Appunti',
  },
  confronto: {
    titolo: 'Confronto',
    vuotoTitolo: 'Scegli almeno due elementi',
    vuotoTesto: 'In Ricerche tocca «Confronta» e scegli da 2 a 3 elementi.',
    conteggio: 'Confronto · {n} elementi',
    elementi: 'Elementi a confronto',
    spiega: 'Lex legge gli elementi scelti e li mette a confronto. Usa i crediti, come una domanda.',
    attesa: 'Lex sta confrontando gli elementi',
    // Le quattro richieste del sito (AZIONI_CONFRONTO), per id.
    azioni: {
      sintesi_unificata: {
        titolo: 'Sintesi unificata',
        descrizione: 'Fonde gli elementi in un quadro unitario',
      },
      conflitti: { titolo: 'Conflitti & tensioni', descrizione: 'Evidenzia divergenze e contraddizioni' },
      comuni: { titolo: 'Punti in comune', descrizione: 'Estrae il filo che li unisce' },
      parere: { titolo: 'Parere completo', descrizione: 'Documento strutturato pronto da copiare' },
    },
  },
  chatSalvata: {
    titolo: 'Chat salvata',
    sparitaTitolo: "Questa chat non c'è più",
    sparitaTesto: "Forse l'hai tolta dall'etichetta, qui o sul sito.",
    salvataIn: 'Salvata in «{nome}» · {quando}',
    continua: 'Continua la chat',
  },
  etichette: {
    nuovaTesto: 'Raccoglie chat, norme e sentenze sullo stesso tema. La ritrovi anche sul sito.',
    nome: 'Nome',
    nomeSegnaposto: 'Es. Casa, Lavoro, Multe…',
    doppione: "Esiste già un'etichetta con questo nome.",
    colore: 'Colore',
    coloreNome: 'Colore {nome}',
    anteprima: 'Anteprima',
    crea: 'Crea etichetta',
    gestisciTesto: 'Le modifiche valgono anche sul sito.',
    nessuna: 'Nessuna etichetta da gestire.',
    salva: 'Salva',
    elimina: 'Elimina',
    eliminaDomanda: 'Eliminare «{nome}»?',
    vuota: "L'etichetta è vuota.",
    restaUno:
      "L'elemento resta: perde solo questa etichetta. Sul sito le ricerche senza etichetta sono al massimo 20: oltre, le più vecchie si cancellano da sole.",
    restanoMolti:
      'I {n} elementi restano: perdono solo questa etichetta. Sul sito le ricerche senza etichetta sono al massimo 20: oltre, le più vecchie si cancellano da sole.',
    modifica: 'Modifica «{nome}»',
    eliminaNome: 'Elimina «{nome}»',
  },
  // Nomi dei colori delle etichette per il lettore dello schermo (la chiave è il nome in src/tema).
  colori: {
    salvia: 'salvia',
    oro: 'oro',
    azzurro: 'azzurro',
    rosso: 'rosso',
    viola: 'viola',
    arancio: 'arancio',
    verde: 'verde',
    lilla: 'lilla',
  },
  nuovaRicerca: {
    testo: "Scrivi i tuoi appunti e salvali in un'etichetta. Per una domanda a Lex usa «Chiedi a Lex».",
    titolo: 'Titolo (facoltativo)',
    titoloSegnaposto: "Es. Cosa chiedere all'ufficio tecnico",
    contenuto: 'Contenuto',
    contenutoSegnaposto: 'Scrivi i tuoi appunti, il ragionamento, le citazioni…',
    senzaEtichette: 'Non hai ancora etichette: creane una con «+ Etichetta» in Ricerche.',
    salvaIn: 'Salva in «{nome}»',
    scegli: "Scegli un'etichetta",
    sulSito: 'La ritrovi anche sul sito, con lo stesso account.',
  },
  appunti: { inEtichetta: 'In «{nome}»' },
};

const de: Parziale<typeof it> = {
  titolo: 'Recherchen',
  nuova: 'Neue Recherche',
  intro: 'Alles, was Sie Lex gefragt und gespeichert haben: Chats, Notizen, Normen, Urteile und Praxis.',
  copiaOffline: 'Offline: Sie lesen die auf dem Telefon gespeicherte Kopie.',
  cerca: 'In Ihren Recherchen suchen',
  cercaSegnaposto: 'In Ihren Recherchen suchen…',
  etichetta: 'Etikett',
  nuovaEtichetta: 'Neues Etikett',
  gestisci: 'Etiketten verwalten',
  sceltaConfronto:
    'Wählen Sie 2 bis {max} Elemente, auch aus verschiedenen Etiketten · {n} / {max} ausgewählt',
  didascalia: 'Etikett «{nome}» · {elementi}',
  elementiUno: '1 Element',
  elementiMolti: '{n} Elemente',
  offlineTitolo: 'Recherchen gibt es nur mit Verbindung',
  offlineTesto:
    'Um gespeicherte Chats, Normen und Notizen auch offline zu lesen, schalten Sie im Profil «Recherchen auch offline» ein.',
  vaiProfilo: 'Zum Profil',
  vuotoTitolo: 'Sie haben noch nichts gespeichert',
  vuotoTesto:
    'Wenn Ihnen eine Antwort von Lex hilft, speichern Sie sie mit einem Etikett: Sie finden sie hier und auf der Website.',
  chiedi: 'Lex fragen',
  chiediSu: 'Lex zu «{nome}» fragen',
  nessunRisultatoTitolo: 'Kein Element mit diesen Wörtern',
  nessunRisultatoTesto: 'Versuchen Sie es mit anderen Wörtern.',
  etichettaVuotaTitolo: 'Dieses Etikett ist noch leer',
  etichettaVuotaTesto:
    'Speichern Sie hier Chats, Normen und Urteile oder schreiben Sie Ihre Notizen mit «+».',
  confronta: 'Vergleichen',
  confrontaDueOTre: 'Zwei oder drei Elemente vergleichen',
  confrontaAffiancati: 'Nebeneinander vergleichen',
  normaSalvata: 'Gespeicherte Norm',
  tornaRicerche: 'Zurück zu Recherchen',
  tipi: {
    'Chat con Lex': 'Chat mit Lex',
    Norma: 'Norm',
    Sentenza: 'Urteil',
    Appunti: 'Notizen',
  },
  confronto: {
    titolo: 'Vergleich',
    vuotoTitolo: 'Wählen Sie mindestens zwei Elemente',
    vuotoTesto: 'Tippen Sie in Recherchen auf «Vergleichen» und wählen Sie 2 bis 3 Elemente.',
    conteggio: 'Vergleich · {n} Elemente',
    elementi: 'Verglichene Elemente',
    spiega: 'Lex liest die gewählten Elemente und vergleicht sie. Das kostet Credits, wie eine Frage.',
    attesa: 'Lex vergleicht die Elemente',
    azioni: {
      sintesi_unificata: {
        titolo: 'Vereinheitlichte Synthese',
        descrizione: 'Fügt die Elemente zu einem einheitlichen Bild zusammen',
      },
      conflitti: {
        titolo: 'Konflikte & Spannungen',
        descrizione: 'Hebt Abweichungen und Widersprüche hervor',
      },
      comuni: { titolo: 'Gemeinsamkeiten', descrizione: 'Extrahiert den gemeinsamen roten Faden' },
      parere: {
        titolo: 'Vollständiges Gutachten',
        descrizione: 'Strukturiertes Dokument, bereit zum Kopieren',
      },
    },
  },
  chatSalvata: {
    titolo: 'Gespeicherter Chat',
    sparitaTitolo: 'Diesen Chat gibt es nicht mehr',
    sparitaTesto: 'Vielleicht haben Sie ihn aus dem Etikett entfernt, hier oder auf der Website.',
    salvataIn: 'Gespeichert in «{nome}» · {quando}',
    continua: 'Chat fortsetzen',
  },
  etichette: {
    nuovaTesto: 'Sammelt Chats, Normen und Urteile zum selben Thema. Sie finden es auch auf der Website.',
    nome: 'Name',
    nomeSegnaposto: 'Z. B. Wohnen, Arbeit, Bussen…',
    doppione: 'Es existiert bereits ein Etikett mit diesem Namen.',
    colore: 'Farbe',
    coloreNome: 'Farbe {nome}',
    anteprima: 'Vorschau',
    crea: 'Etikett erstellen',
    gestisciTesto: 'Die Änderungen gelten auch auf der Website.',
    nessuna: 'Keine Etiketten zu verwalten.',
    salva: 'Speichern',
    elimina: 'Löschen',
    eliminaDomanda: '«{nome}» löschen?',
    vuota: 'Das Etikett ist leer.',
    restaUno:
      'Das Element bleibt erhalten: Es verliert nur dieses Etikett. Auf der Website gibt es höchstens 20 Recherchen ohne Etikett: Darüber hinaus werden die ältesten automatisch gelöscht.',
    restanoMolti:
      'Die {n} Elemente bleiben erhalten: Sie verlieren nur dieses Etikett. Auf der Website gibt es höchstens 20 Recherchen ohne Etikett: Darüber hinaus werden die ältesten automatisch gelöscht.',
    modifica: '«{nome}» bearbeiten',
    eliminaNome: '«{nome}» löschen',
  },
  colori: {
    salvia: 'Salbeigrün',
    oro: 'Gold',
    azzurro: 'Hellblau',
    rosso: 'Rot',
    viola: 'Violett',
    arancio: 'Orange',
    verde: 'Grün',
    lilla: 'Lila',
  },
  nuovaRicerca: {
    testo:
      'Schreiben Sie Ihre Notizen und speichern Sie sie in einem Etikett. Für eine Frage an Lex nutzen Sie «Lex fragen».',
    titolo: 'Titel (optional)',
    titoloSegnaposto: 'Z. B. Fragen an das Bauamt',
    contenuto: 'Inhalt',
    contenutoSegnaposto: 'Schreiben Sie Ihre Notizen, Überlegungen, Zitate…',
    senzaEtichette: 'Sie haben noch keine Etiketten: Erstellen Sie eines mit «+ Etikett» in Recherchen.',
    salvaIn: 'In «{nome}» speichern',
    scegli: 'Etikett wählen',
    sulSito: 'Sie finden sie auch auf der Website, mit demselben Konto.',
  },
  appunti: { inEtichetta: 'In «{nome}»' },
};

const fr: Parziale<typeof it> = {
  titolo: 'Recherches',
  nuova: 'Nouvelle recherche',
  intro: 'Tout ce que vous avez demandé à Lex et enregistré : chats, notes, normes, arrêts et pratique.',
  copiaOffline: 'Hors ligne : vous lisez la copie enregistrée sur le téléphone.',
  cerca: 'Chercher dans vos recherches',
  cercaSegnaposto: 'Chercher dans vos recherches…',
  etichetta: 'Étiquette',
  nuovaEtichetta: 'Nouvelle étiquette',
  gestisci: 'Gérer les étiquettes',
  sceltaConfronto:
    "Choisissez de 2 à {max} éléments, même d'étiquettes différentes · {n} / {max} sélectionnés",
  didascalia: 'Étiquette « {nome} » · {elementi}',
  elementiUno: '1 élément',
  elementiMolti: '{n} éléments',
  offlineTitolo: "Les Recherches ne s'ouvrent qu'avec une connexion",
  offlineTesto:
    'Pour lire les chats, normes et notes enregistrés même hors ligne, activez « Recherches même hors ligne » dans le Profil.',
  vaiProfilo: 'Aller au Profil',
  vuotoTitolo: "Vous n'avez encore rien enregistré",
  vuotoTesto:
    'Quand une réponse de Lex vous est utile, enregistrez-la avec une étiquette : vous la retrouvez ici et sur le site.',
  chiedi: 'Demander à Lex',
  chiediSu: 'Demander à Lex sur « {nome} »',
  nessunRisultatoTitolo: 'Aucun élément avec ces mots',
  nessunRisultatoTesto: "Essayez avec d'autres mots.",
  etichettaVuotaTitolo: 'Cette étiquette est encore vide',
  etichettaVuotaTesto: 'Enregistrez ici chats, normes et arrêts, ou écrivez vos notes avec « + ».',
  confronta: 'Comparer',
  confrontaDueOTre: 'Comparer deux ou trois éléments',
  confrontaAffiancati: 'Comparer côte à côte',
  normaSalvata: 'Norme enregistrée',
  tornaRicerche: 'Retour aux Recherches',
  tipi: {
    'Chat con Lex': 'Chat avec Lex',
    Norma: 'Norme',
    Sentenza: 'Arrêt',
    Appunti: 'Notes',
  },
  confronto: {
    titolo: 'Comparaison',
    vuotoTitolo: 'Choisissez au moins deux éléments',
    vuotoTesto: 'Dans Recherches, touchez « Comparer » et choisissez de 2 à 3 éléments.',
    conteggio: 'Comparaison · {n} éléments',
    elementi: 'Éléments comparés',
    spiega: 'Lex lit les éléments choisis et les compare. Cela utilise des crédits, comme une question.',
    attesa: 'Lex compare les éléments',
    azioni: {
      sintesi_unificata: {
        titolo: 'Synthèse unifiée',
        descrizione: 'Fusionne les éléments en un tableau unitaire',
      },
      conflitti: {
        titolo: 'Conflits & tensions',
        descrizione: 'Met en évidence les divergences et les contradictions',
      },
      comuni: { titolo: 'Points communs', descrizione: 'Extrait le fil rouge partagé' },
      parere: { titolo: 'Avis complet', descrizione: 'Document structuré prêt à copier' },
    },
  },
  chatSalvata: {
    titolo: 'Chat enregistré',
    sparitaTitolo: "Ce chat n'existe plus",
    sparitaTesto: "Vous l'avez peut-être retiré de l'étiquette, ici ou sur le site.",
    salvataIn: 'Enregistré dans « {nome} » · {quando}',
    continua: 'Continuer le chat',
  },
  etichette: {
    nuovaTesto: 'Regroupe chats, normes et arrêts sur un même thème. Vous la retrouvez aussi sur le site.',
    nome: 'Nom',
    nomeSegnaposto: 'Ex. Logement, Travail, Amendes…',
    doppione: 'Une étiquette portant ce nom existe déjà.',
    colore: 'Couleur',
    coloreNome: 'Couleur {nome}',
    anteprima: 'Aperçu',
    crea: "Créer l'étiquette",
    gestisciTesto: 'Les modifications valent aussi sur le site.',
    nessuna: 'Aucune étiquette à gérer.',
    salva: 'Enregistrer',
    elimina: 'Supprimer',
    eliminaDomanda: 'Supprimer « {nome} » ?',
    vuota: "L'étiquette est vide.",
    restaUno:
      "L'élément reste : il perd seulement cette étiquette. Sur le site, les recherches sans étiquette sont limitées à 20 : au-delà, les plus anciennes sont supprimées automatiquement.",
    restanoMolti:
      'Les {n} éléments restent : ils perdent seulement cette étiquette. Sur le site, les recherches sans étiquette sont limitées à 20 : au-delà, les plus anciennes sont supprimées automatiquement.',
    modifica: 'Modifier « {nome} »',
    eliminaNome: 'Supprimer « {nome} »',
  },
  colori: {
    salvia: 'vert sauge',
    oro: 'or',
    azzurro: 'bleu clair',
    rosso: 'rouge',
    viola: 'violet',
    arancio: 'orange',
    verde: 'vert',
    lilla: 'lilas',
  },
  nuovaRicerca: {
    testo:
      'Écrivez vos notes et enregistrez-les dans une étiquette. Pour une question à Lex, utilisez « Demander à Lex ».',
    titolo: 'Titre (facultatif)',
    titoloSegnaposto: 'Ex. Questions pour le service technique',
    contenuto: 'Contenu',
    contenutoSegnaposto: 'Écrivez vos notes, votre raisonnement, vos citations…',
    senzaEtichette:
      "Vous n'avez pas encore d'étiquettes : créez-en une avec « + Étiquette » dans Recherches.",
    salvaIn: 'Enregistrer dans « {nome} »',
    scegli: 'Choisissez une étiquette',
    sulSito: 'Vous la retrouvez aussi sur le site, avec le même compte.',
  },
  appunti: { inEtichetta: 'Dans « {nome} »' },
};

export const ricerche = { it, de, fr };
