import type { Parziale } from '../tipi';

// Sezione «studio»: italiano di riferimento, poi tedesco svizzero («Sie», «ss») e francese («vous»).
// Pratiche e calendario dello Studio. Dove c'era, il tedesco e il francese vengono dal sito svizzero
// (avv_pratiche, avv_pratica_dettaglio, avv_calendar, comp_controparti, comp_udienza_modal…).
// I valori salvati nel database (tipi di causa, esiti, ruoli) restano in italiano: qui c'è solo come si mostrano.

const it = {
  // Valori salvati: la chiave è il valore del database.
  tipiCausa: {
    Civile: 'Civile',
    Penale: 'Penale',
    Commerciale: 'Commerciale',
    Amministrativo: 'Amministrativo',
    Lavoro: 'Lavoro',
    Famiglia: 'Famiglia',
  },
  esiti: { Vinta: 'Vinta', Persa: 'Persa', Transatta: 'Transatta', Archiviata: 'Archiviata' },
  statiPratica: { aperta: 'Aperta', chiusa: 'Chiusa' },
  ruoli: {
    convenuto: 'Convenuto',
    attore: 'Attore',
    resistente: 'Resistente',
    ricorrente: 'Ricorrente',
    opponente: 'Opponente',
    opposto: 'Opposto',
    imputato: 'Imputato',
    personaOffesa: 'Persona offesa',
    terzoChiamato: 'Terzo chiamato',
    altro: 'Altro',
  },
  tipiEvento: {
    presenza: 'In presenza',
    videocall: 'Videocall',
    telefonico: 'Telefonico',
    udienza: 'Udienza',
    scadenza: 'Scadenza',
  },
  statiEvento: { programmato: 'Programmato', concluso: 'Concluso', annullato: 'Annullato' },
  // Atti che Lex prepara in Svizzera (in Italia l'elenco resta in italiano, in src/studio/pratiche.ts).
  attiCH: {
    diffida: 'Diffida',
    parere: 'Parere',
    esecuzione: 'Esecuzione LEF',
    rigetto: "Rigetto dell'opposizione",
    conciliazione: 'Istanza di conciliazione',
    petizione: 'Petizione',
  },
  campi: { formatoData: 'gg.mm.aaaa', formatoOra: 'hh:mm' },

  pratiche: {
    titolo: 'Pratiche',
    nuova: 'Nuova pratica',
    cerca: 'Cerca pratica o cliente',
    cercaSegnaposto: 'Cerca pratica o cliente…',
    aperte: 'Aperte · {n}',
    chiuse: 'Chiuse · {n}',
    tutte: 'Tutte · {n}',
    vuotoCercaTitolo: 'Nessuna pratica con queste parole',
    vuotoCercaTesto: 'Prova con il nome del cliente o con altre parole.',
    vuotoTitolo: 'Nessuna pratica qui',
    vuotoTesto: 'Crea una pratica con «+» in alto.',
    udienza: 'Udienza {data}',
    termine: 'Termine: {quando}',
  },

  nuova: {
    titolo: 'Nuova pratica',
    titoloPratica: 'Titolo della pratica',
    titoloEsempio: 'Es. Causa civile Rossi c. Ferrari',
    cliente: 'Cliente',
    senzaClienti: 'Non hai ancora clienti: si aggiungono dal sito, nella sezione Clienti.',
    tipoCausa: 'Tipo di causa',
    ore: 'Ore dedicate (facoltative)',
    oreEsempio: 'Es. 2,5',
    udienza: 'Prossima udienza (facoltativa)',
    note: 'Note interne (facoltative)',
    noteSegnaposto: 'Le vedi solo tu: Lex non le legge',
    crea: 'Crea la pratica',
  },

  pratica: {
    titolo: 'Pratica',
    nonCe: "Questa pratica non c'è più",
    torna: 'Torna alle pratiche',
    altreAzioni: 'Altre azioni',
    schede: {
      panoramica: 'Panoramica',
      scadenze: 'Scadenze',
      controparti: 'Controparti',
      documenti: 'Documenti',
      ricerche: 'Ricerche',
      lex: 'Lex',
    },
    statiUdienza: {
      programmata: 'Programmata',
      svolta: 'Svolta',
      rinviata: 'Rinviata',
      annullata: 'Annullata',
    },
    azioni: {
      note: 'Note interne',
      noteTesto: 'Le vedi solo tu: Lex non le legge',
      fattura: 'Nuova fattura',
      fatturaTesto: 'Per {cliente}, collegata a questa pratica',
      chiudi: 'Chiudi la pratica',
      chiudiTesto: "Con l'esito: vinta, persa, transatta, archiviata",
      riapri: 'Riapri la pratica',
      elimina: 'Elimina la pratica',
    },
    panoramica: {
      cliente: 'Cliente',
      tipo: 'Tipo',
      creata: 'Creata il',
      esito: 'Esito',
      ore: 'Ore dedicate',
      prossimaUdienza: 'Prossima udienza',
      nessunaUdienza: 'Nessuna udienza in programma',
      primoTermine: 'Primo termine',
      nessunTermine: 'Nessun termine da rispettare',
      note: 'Note interne',
      modifica: 'Modifica',
      aggiungi: 'Aggiungi',
      nessunaNota: 'Nessuna nota. Le vedi solo tu: Lex non le legge.',
    },
    scadenze: {
      termini: 'Termini · {n}',
      termine: 'Termine',
      nessunTermine: 'Nessun termine in corso.',
      da: 'Da: {evento}',
      segnaCompiuto: 'Segna come compiuto: {titolo}',
      eliminaTermine: 'Elimina il termine: {titolo}',
      compiuti: 'Compiuti: {elenco}',
      udienze: 'Udienze · {n}',
      udienza: 'Udienza',
      nessunaUdienza: 'Nessuna udienza.',
      giudice: 'Giudice: {nome}',
    },
    controparti: {
      titolo: 'Controparti · {n}',
      aggiungi: 'Controparte',
      vuoto: 'Nessuna controparte. Aggiungile per generare correttamente gli atti.',
      fisica: 'Persona fisica',
      giuridica: 'Persona giuridica',
      legale: 'Legale: {nome}',
    },
    documenti: {
      titolo: 'Documenti · {n}',
      aggiungi: 'Aggiungi',
      vuoto: 'Nessun documento collegato a questa pratica.',
      archivio: 'Archivio',
    },
    ricerche: {
      titolo: 'Ricerche · {n}',
      bancaDati: 'Banca dati',
      vuoto: 'Nessuna ricerca. Le chat con Lex su questa pratica, salvate, finiscono qui.',
      // Tipi salvati: «Chat con Lex», «Ricerca AI», «Appunti».
      chat: 'Chat con Lex',
      ai: 'Ricerca AI',
      appunti: 'Appunti',
    },
    lex: {
      passo1: 'Leggo la pratica',
      passo2: 'Cerco tra norme e giurisprudenza',
      passo3: 'Scrivo la risposta',
      titolo: 'Lex conosce questa pratica',
      testo:
        "Cliente, controparti, udienze, documenti e ricerche. Non legge le note interne. Chiedi un'analisi, una strategia o un atto: ogni atto costa 1 credito.",
      atti: 'Atti che può preparare',
      prepara: 'Prepara: {atto}',
      nuovaDomanda: 'Nuova domanda',
      segnaposto: 'Chiedi a Lex su questa pratica…',
      inBreve: 'risposta di prova su «{titolo}».',
      cosaSo: 'Cosa so di questa pratica.',
      cosaSoTesto:
        ' Cliente {cliente}; {controparti} controparti, {udienze} udienze, {documenti} documenti e {ricerche} ricerche.',
      nota: 'Dalla tappa «Studio» qui risponde Lex sulla pratica, come sul sito. Un atto generato diventa un PDF da salvare nella pratica, e costa 1 credito.',
    },
  },

  calendario: {
    titolo: 'Calendario',
    nuovo: 'Nuovo appuntamento',
    agenda: 'Agenda',
    mese: 'Mese',
    prossimiUno: '1 impegno nei prossimi 7 giorni',
    prossimiMolti: '{n} impegni nei prossimi 7 giorni',
    passati: 'Mostra anche le ultime due settimane',
    niente: 'Niente in programma.',
    mesePrecedente: 'Mese precedente',
    meseSuccessivo: 'Mese successivo',
    oggi: 'Oggi',
    giornoEventi: '{giorno}, {n} eventi',
    evento: '{ora}, {tipo}: {titolo}',
  },

  fogli: {
    note: {
      titolo: 'Note interne',
      testo: 'Le vedi solo tu (e lo studio). Lex non le legge.',
      campo: 'Note',
      salva: 'Salva le note',
    },
    chiudi: {
      titolo: 'Chiudi la pratica',
      testo: "Scegli l'esito. Potrai riaprirla quando vuoi.",
      esito: 'Esito',
      conferma: 'Conferma la chiusura',
    },
    elimina: {
      titolo: 'Eliminare la pratica?',
      testo:
        "Si cancellano anche udienze, termini, controparti, ricerche e appuntamenti. I documenti dell'Archivio restano. Non si può annullare.",
      conferma: 'Per confermare, scrivi: {titolo}',
      fatture: 'Ci sono fatture collegate a questa pratica: scollegale prima, dalla fattura.',
      elimina: 'Elimina la pratica',
    },
    termine: {
      titolo: 'Nuovo termine',
      testo: 'Compare anche in calendario, il giorno della scadenza.',
      campo: 'Termine',
      esempio: 'Es. Deposito memoria di replica',
      evento: 'Da quale evento (facoltativo)',
      eventoEsempio: 'Es. Notifica della sentenza',
      scadenza: 'Scadenza',
      traGiorni: 'Tra {n} giorni',
      dataErrata: 'Scrivi la data come gg.mm.aaaa.',
      aggiungi: 'Aggiungi il termine',
    },
    udienza: {
      titolo: 'Nuova udienza',
      tipo: 'Tipo di udienza',
      tipoEsempio: 'Es. Prima comparizione',
      data: 'Data',
      ora: 'Ora',
      sede: 'Sede (facoltativa)',
      sedeEsempio: 'Tribunale, sezione, aula',
      aggiungi: "Aggiungi l'udienza",
    },
    controparte: {
      titolo: 'Nuova controparte',
      fisica: 'Persona fisica',
      giuridica: 'Persona giuridica',
      tipoPersona: 'Tipo di persona',
      ragioneSociale: 'Ragione sociale',
      nomeCognome: 'Nome e cognome',
      ruolo: 'Ruolo processuale',
      legale: 'Legale avversario (facoltativo)',
      legaleEsempio: 'Es. Avv. Paolo Neri, foro di Milano',
      aggiungi: 'Aggiungi la controparte',
    },
    evento: {
      quando: 'Quando',
      tipo: 'Tipo',
      cliente: 'Cliente',
      pratica: 'Pratica',
      sede: 'Sede',
      noteInterne: 'Note interne',
      noteCliente: 'Note per il cliente',
      daTermine: 'È la scadenza di un termine: si segna come compiuto nella pratica.',
      daUdienza: "L'udienza si gestisce nella pratica: esito, rinvio, sede.",
      daMandato: 'Scadenza del mandato del cliente: si gestisce sul sito.',
      videocall: 'Apri la videocall',
      apriPratica: 'Apri la pratica',
      modifica: 'Modifica',
      concluso: 'Concluso',
      annulla: 'Annulla',
    },
    nuovoEvento: {
      nuovo: 'Nuovo appuntamento',
      modifica: 'Modifica appuntamento',
      titolo: 'Titolo',
      titoloEsempio: 'Es. Incontro con il cliente',
      tipo: 'Tipo',
      giorno: 'Giorno',
      oggi: 'Oggi',
      domani: 'Domani',
      settimana: 'Tra una settimana',
      inizio: 'Inizio',
      fine: 'Fine',
      orari: "La fine deve venire dopo l'inizio.",
      cliente: 'Cliente',
      clienteFacoltativo: 'Cliente (facoltativo)',
      pratica: 'Pratica',
      praticaFacoltativa: 'Pratica (facoltativa)',
      link: 'Link della videocall',
      aula: 'Tribunale e aula',
      aulaEsempio: 'Es. Tribunale di Milano, aula 12',
      noteCliente: 'Note per il cliente (facoltative)',
      noteClienteSegnaposto: 'Le vede anche il cliente',
      salva: 'Salva le modifiche',
      aggiungi: 'Aggiungi al calendario',
    },
  },
};

const de: Parziale<typeof it> = {
  tipiCausa: {
    Civile: 'Zivilrecht',
    Penale: 'Strafrecht',
    Commerciale: 'Handelsrecht',
    Amministrativo: 'Verwaltungsrecht',
    Lavoro: 'Arbeitsrecht',
    Famiglia: 'Familienrecht',
  },
  esiti: { Vinta: 'Gewonnen', Persa: 'Verloren', Transatta: 'Vergleich', Archiviata: 'Archiviert' },
  statiPratica: { aperta: 'Offen', chiusa: 'Abgeschlossen' },
  ruoli: {
    convenuto: 'Beklagte Partei',
    attore: 'Klagende Partei',
    resistente: 'Beschwerdegegnerische Partei',
    ricorrente: 'Beschwerdeführende Partei',
    opponente: 'Einsprechende Partei',
    opposto: 'Einspruchsgegnerische Partei',
    imputato: 'Beschuldigte Person',
    personaOffesa: 'Geschädigte Person',
    terzoChiamato: 'Streitberufene Drittpartei',
    altro: 'Andere',
  },
  tipiEvento: {
    presenza: 'Vor Ort',
    videocall: 'Videocall',
    telefonico: 'Telefonisch',
    udienza: 'Verhandlung',
    scadenza: 'Frist',
  },
  statiEvento: { programmato: 'Geplant', concluso: 'Abgeschlossen', annullato: 'Abgesagt' },
  attiCH: {
    diffida: 'Mahnung',
    parere: 'Rechtsgutachten',
    esecuzione: 'Betreibung SchKG',
    rigetto: 'Rechtsöffnungsgesuch',
    conciliazione: 'Schlichtungsgesuch',
    petizione: 'Klage',
  },
  campi: { formatoData: 'TT.MM.JJJJ', formatoOra: 'hh:mm' },

  pratiche: {
    titolo: 'Dossiers',
    nuova: 'Neues Dossier',
    cerca: 'Dossier oder Mandant suchen',
    cercaSegnaposto: 'Dossier oder Mandant suchen…',
    aperte: 'Offen · {n}',
    chiuse: 'Abgeschlossen · {n}',
    tutte: 'Alle · {n}',
    vuotoCercaTitolo: 'Kein Dossier mit diesen Wörtern',
    vuotoCercaTesto: 'Versuchen Sie es mit dem Namen des Mandanten oder mit anderen Wörtern.',
    vuotoTitolo: 'Hier gibt es keine Dossiers',
    vuotoTesto: 'Erstellen Sie ein Dossier mit «+» oben.',
    udienza: 'Verhandlung {data}',
    termine: 'Frist: {quando}',
  },

  nuova: {
    titolo: 'Neues Dossier',
    titoloPratica: 'Titel des Dossiers',
    titoloEsempio: 'Z. B. Zivilverfahren Rossi gegen Ferrari',
    cliente: 'Mandant',
    senzaClienti: 'Sie haben noch keine Mandanten: Sie fügen sie auf der Website im Bereich Mandanten hinzu.',
    tipoCausa: 'Verfahrensart',
    ore: 'Aufgewendete Stunden (optional)',
    oreEsempio: 'Z. B. 2,5',
    udienza: 'Nächste Verhandlung (optional)',
    note: 'Interne Notizen (optional)',
    noteSegnaposto: 'Nur Sie sehen sie: Lex liest sie nicht',
    crea: 'Dossier erstellen',
  },

  pratica: {
    titolo: 'Dossier',
    nonCe: 'Dieses Dossier gibt es nicht mehr',
    torna: 'Zurück zu den Dossiers',
    altreAzioni: 'Weitere Aktionen',
    schede: {
      panoramica: 'Übersicht',
      scadenze: 'Fristen',
      controparti: 'Gegenparteien',
      documenti: 'Dokumente',
      ricerche: 'Recherchen',
      lex: 'Lex',
    },
    statiUdienza: {
      programmata: 'Geplant',
      svolta: 'Durchgeführt',
      rinviata: 'Verschoben',
      annullata: 'Annulliert',
    },
    azioni: {
      note: 'Interne Notizen',
      noteTesto: 'Nur Sie sehen sie: Lex liest sie nicht',
      fattura: 'Neue Rechnung',
      fatturaTesto: 'Für {cliente}, mit diesem Dossier verknüpft',
      chiudi: 'Dossier abschliessen',
      chiudiTesto: 'Mit dem Ergebnis: gewonnen, verloren, Vergleich, archiviert',
      riapri: 'Dossier wieder öffnen',
      elimina: 'Dossier löschen',
    },
    panoramica: {
      cliente: 'Mandant',
      tipo: 'Art',
      creata: 'Erstellt am',
      esito: 'Ergebnis',
      ore: 'Aufgewendete Stunden',
      prossimaUdienza: 'Nächste Verhandlung',
      nessunaUdienza: 'Keine Verhandlung geplant',
      primoTermine: 'Nächste Frist',
      nessunTermine: 'Keine Frist einzuhalten',
      note: 'Interne Notizen',
      modifica: 'Bearbeiten',
      aggiungi: 'Hinzufügen',
      nessunaNota: 'Keine Notizen. Nur Sie sehen sie: Lex liest sie nicht.',
    },
    scadenze: {
      termini: 'Fristen · {n}',
      termine: 'Frist',
      nessunTermine: 'Keine laufenden Fristen.',
      da: 'Ab: {evento}',
      segnaCompiuto: 'Als erledigt markieren: {titolo}',
      eliminaTermine: 'Frist löschen: {titolo}',
      compiuti: 'Erledigt: {elenco}',
      udienze: 'Verhandlungen · {n}',
      udienza: 'Verhandlung',
      nessunaUdienza: 'Keine Verhandlungen.',
      giudice: 'Richter: {nome}',
    },
    controparti: {
      titolo: 'Gegenparteien · {n}',
      aggiungi: 'Gegenpartei',
      vuoto: 'Keine Gegenpartei. Fügen Sie sie hinzu, um die Rechtsschriften korrekt zu erstellen.',
      fisica: 'Natürliche Person',
      giuridica: 'Juristische Person',
      legale: 'Gegenanwalt: {nome}',
    },
    documenti: {
      titolo: 'Dokumente · {n}',
      aggiungi: 'Hinzufügen',
      vuoto: 'Keine Dokumente mit diesem Dossier verknüpft.',
      archivio: 'Archiv',
    },
    ricerche: {
      titolo: 'Recherchen · {n}',
      bancaDati: 'Datenbank',
      vuoto: 'Keine Recherchen. Gespeicherte Chats mit Lex zu diesem Dossier erscheinen hier.',
      chat: 'Chat mit Lex',
      ai: 'KI-Recherche',
      appunti: 'Notizen',
    },
    lex: {
      passo1: 'Ich lese das Dossier',
      passo2: 'Ich suche in Gesetzen und Rechtsprechung',
      passo3: 'Ich schreibe die Antwort',
      titolo: 'Lex kennt dieses Dossier',
      testo:
        'Mandant, Gegenparteien, Verhandlungen, Dokumente und Recherchen. Die internen Notizen liest Lex nicht. Verlangen Sie eine Analyse, eine Strategie oder eine Rechtsschrift: Jede Rechtsschrift kostet 1 Credit.',
      atti: 'Rechtsschriften, die Lex erstellen kann',
      prepara: 'Erstellen: {atto}',
      nuovaDomanda: 'Neue Frage',
      segnaposto: 'Fragen Sie Lex zu diesem Dossier…',
      inBreve: 'Testantwort zu «{titolo}».',
      cosaSo: 'Was ich über dieses Dossier weiss.',
      cosaSoTesto:
        ' Mandant {cliente}; {controparti} Gegenparteien, {udienze} Verhandlungen, {documenti} Dokumente und {ricerche} Recherchen.',
      nota: 'Ab der Etappe «Studio» antwortet hier Lex zum Dossier, wie auf der Website. Eine erstellte Rechtsschrift wird zu einem PDF, das Sie im Dossier speichern, und kostet 1 Credit.',
    },
  },

  calendario: {
    titolo: 'Kalender',
    nuovo: 'Neuer Termin',
    agenda: 'Agenda',
    mese: 'Monat',
    prossimiUno: '1 Termin in den nächsten 7 Tagen',
    prossimiMolti: '{n} Termine in den nächsten 7 Tagen',
    passati: 'Auch die letzten zwei Wochen anzeigen',
    niente: 'Nichts geplant.',
    mesePrecedente: 'Vorheriger Monat',
    meseSuccessivo: 'Nächster Monat',
    oggi: 'Heute',
    giornoEventi: '{giorno}, {n} Einträge',
    evento: '{ora}, {tipo}: {titolo}',
  },

  fogli: {
    note: {
      titolo: 'Interne Notizen',
      testo: 'Nur Sie (und die Kanzlei) sehen sie. Lex liest sie nicht.',
      campo: 'Notizen',
      salva: 'Notizen speichern',
    },
    chiudi: {
      titolo: 'Dossier abschliessen',
      testo: 'Wählen Sie das Ergebnis. Sie können das Dossier jederzeit wieder öffnen.',
      esito: 'Ergebnis',
      conferma: 'Abschluss bestätigen',
    },
    elimina: {
      titolo: 'Dossier löschen?',
      testo:
        'Gelöscht werden auch Verhandlungen, Fristen, Gegenparteien, Recherchen und Termine. Die Dokumente im Archiv bleiben. Das kann nicht rückgängig gemacht werden.',
      conferma: 'Zur Bestätigung geben Sie ein: {titolo}',
      fatture:
        'Mit diesem Dossier sind Rechnungen verknüpft: Trennen Sie sie zuerst, in der Rechnung selbst.',
      elimina: 'Dossier löschen',
    },
    termine: {
      titolo: 'Neue Frist',
      testo: 'Sie erscheint auch im Kalender, am Tag des Ablaufs.',
      campo: 'Frist',
      esempio: 'Z. B. Einreichung der Replik',
      evento: 'Auslösendes Ereignis (optional)',
      eventoEsempio: 'Z. B. Zustellung des Urteils',
      scadenza: 'Ablauf',
      traGiorni: 'In {n} Tagen',
      dataErrata: 'Geben Sie das Datum als TT.MM.JJJJ ein.',
      aggiungi: 'Frist hinzufügen',
    },
    udienza: {
      titolo: 'Neue Verhandlung',
      tipo: 'Art der Verhandlung',
      tipoEsempio: 'Z. B. Schlichtungsverhandlung',
      data: 'Datum',
      ora: 'Uhrzeit',
      sede: 'Ort (optional)',
      sedeEsempio: 'Gericht, Abteilung, Saal',
      aggiungi: 'Verhandlung hinzufügen',
    },
    controparte: {
      titolo: 'Neue Gegenpartei',
      fisica: 'Natürliche Person',
      giuridica: 'Juristische Person',
      tipoPersona: 'Art der Person',
      ragioneSociale: 'Firma',
      nomeCognome: 'Vor- und Nachname',
      ruolo: 'Prozessuale Stellung',
      legale: 'Gegenanwalt (optional)',
      legaleEsempio: 'Z. B. RA Paolo Neri, Zürich',
      aggiungi: 'Gegenpartei hinzufügen',
    },
    evento: {
      quando: 'Wann',
      tipo: 'Art',
      cliente: 'Mandant',
      pratica: 'Dossier',
      sede: 'Ort',
      noteInterne: 'Interne Notizen',
      noteCliente: 'Notizen für den Mandanten',
      daTermine: 'Das ist der Ablauf einer Frist: Sie markieren sie im Dossier als erledigt.',
      daUdienza: 'Die Verhandlung verwalten Sie im Dossier: Ergebnis, Verschiebung, Ort.',
      daMandato: 'Ablauf des Mandats: Sie verwalten ihn auf der Website.',
      videocall: 'Videocall öffnen',
      apriPratica: 'Dossier öffnen',
      modifica: 'Bearbeiten',
      concluso: 'Abgeschlossen',
      annulla: 'Absagen',
    },
    nuovoEvento: {
      nuovo: 'Neuer Termin',
      modifica: 'Termin bearbeiten',
      titolo: 'Titel',
      titoloEsempio: 'Z. B. Besprechung mit dem Mandanten',
      tipo: 'Art',
      giorno: 'Tag',
      oggi: 'Heute',
      domani: 'Morgen',
      settimana: 'In einer Woche',
      inizio: 'Beginn',
      fine: 'Ende',
      orari: 'Das Ende muss nach dem Beginn liegen.',
      cliente: 'Mandant',
      clienteFacoltativo: 'Mandant (optional)',
      pratica: 'Dossier',
      praticaFacoltativa: 'Dossier (optional)',
      link: 'Videocall-Link',
      aula: 'Gericht und Saal',
      aulaEsempio: 'Z. B. Bezirksgericht Zürich, Saal 12',
      noteCliente: 'Notizen für den Mandanten (optional)',
      noteClienteSegnaposto: 'Auch der Mandant sieht sie',
      salva: 'Änderungen speichern',
      aggiungi: 'Zum Kalender hinzufügen',
    },
  },
};

const fr: Parziale<typeof it> = {
  tipiCausa: {
    Civile: 'Civil',
    Penale: 'Pénal',
    Commerciale: 'Commercial',
    Amministrativo: 'Administratif',
    Lavoro: 'Travail',
    Famiglia: 'Famille',
  },
  esiti: { Vinta: 'Gagné', Persa: 'Perdu', Transatta: 'Transigé', Archiviata: 'Archivé' },
  statiPratica: { aperta: 'Ouvert', chiusa: 'Clôturé' },
  ruoli: {
    convenuto: 'Partie défenderesse',
    attore: 'Partie demanderesse',
    resistente: 'Partie intimée',
    ricorrente: 'Partie recourante',
    opponente: 'Partie opposante',
    opposto: "Partie défenderesse à l'opposition",
    imputato: 'Prévenu',
    personaOffesa: 'Lésé',
    terzoChiamato: 'Tiers appelé en cause',
    altro: 'Autre',
  },
  tipiEvento: {
    presenza: 'En présentiel',
    videocall: 'Visioconférence',
    telefonico: 'Téléphonique',
    udienza: 'Audience',
    scadenza: 'Échéance',
  },
  statiEvento: { programmato: 'Planifié', concluso: 'Terminé', annullato: 'Annulé' },
  attiCH: {
    diffida: 'Mise en demeure',
    parere: 'Avis de droit',
    esecuzione: 'Poursuite LP',
    rigetto: "Mainlevée de l'opposition",
    conciliazione: 'Requête de conciliation',
    petizione: 'Demande',
  },
  campi: { formatoData: 'jj.mm.aaaa', formatoOra: 'hh:mm' },

  pratiche: {
    titolo: 'Dossiers',
    nuova: 'Nouveau dossier',
    cerca: 'Rechercher un dossier ou un client',
    cercaSegnaposto: 'Rechercher un dossier ou un client…',
    aperte: 'Ouverts · {n}',
    chiuse: 'Clôturés · {n}',
    tutte: 'Tous · {n}',
    vuotoCercaTitolo: 'Aucun dossier avec ces mots',
    vuotoCercaTesto: "Essayez avec le nom du client ou avec d'autres mots.",
    vuotoTitolo: 'Aucun dossier ici',
    vuotoTesto: 'Créez un dossier avec « + » en haut.',
    udienza: 'Audience {data}',
    termine: 'Délai : {quando}',
  },

  nuova: {
    titolo: 'Nouveau dossier',
    titoloPratica: 'Titre du dossier',
    titoloEsempio: 'Ex. Procès civil Rossi c. Ferrari',
    cliente: 'Client',
    senzaClienti: "Vous n'avez pas encore de clients : ajoutez-les sur le site, dans la section Clients.",
    tipoCausa: "Type d'affaire",
    ore: 'Heures consacrées (facultatif)',
    oreEsempio: 'Ex. 2,5',
    udienza: 'Prochaine audience (facultatif)',
    note: 'Notes internes (facultatif)',
    noteSegnaposto: 'Vous seul les voyez : Lex ne les lit pas',
    crea: 'Créer le dossier',
  },

  pratica: {
    titolo: 'Dossier',
    nonCe: "Ce dossier n'existe plus",
    torna: 'Retour aux dossiers',
    altreAzioni: 'Autres actions',
    schede: {
      panoramica: 'Aperçu',
      scadenze: 'Délais',
      controparti: 'Parties adverses',
      documenti: 'Documents',
      ricerche: 'Recherches',
      lex: 'Lex',
    },
    statiUdienza: {
      programmata: 'Planifiée',
      svolta: 'Tenue',
      rinviata: 'Renvoyée',
      annullata: 'Annulée',
    },
    azioni: {
      note: 'Notes internes',
      noteTesto: 'Vous seul les voyez : Lex ne les lit pas',
      fattura: 'Nouvelle facture',
      fatturaTesto: 'Pour {cliente}, liée à ce dossier',
      chiudi: 'Clôturer le dossier',
      chiudiTesto: 'Avec le résultat : gagné, perdu, transigé, archivé',
      riapri: 'Rouvrir le dossier',
      elimina: 'Supprimer le dossier',
    },
    panoramica: {
      cliente: 'Client',
      tipo: 'Type',
      creata: 'Créé le',
      esito: 'Résultat',
      ore: 'Heures consacrées',
      prossimaUdienza: 'Prochaine audience',
      nessunaUdienza: 'Aucune audience prévue',
      primoTermine: 'Prochain délai',
      nessunTermine: 'Aucun délai à respecter',
      note: 'Notes internes',
      modifica: 'Modifier',
      aggiungi: 'Ajouter',
      nessunaNota: 'Aucune note. Vous seul les voyez : Lex ne les lit pas.',
    },
    scadenze: {
      termini: 'Délais · {n}',
      termine: 'Délai',
      nessunTermine: 'Aucun délai en cours.',
      da: 'À partir de : {evento}',
      segnaCompiuto: 'Marquer comme accompli : {titolo}',
      eliminaTermine: 'Supprimer le délai : {titolo}',
      compiuti: 'Accomplis : {elenco}',
      udienze: 'Audiences · {n}',
      udienza: 'Audience',
      nessunaUdienza: 'Aucune audience.',
      giudice: 'Juge : {nome}',
    },
    controparti: {
      titolo: 'Parties adverses · {n}',
      aggiungi: 'Partie adverse',
      vuoto: 'Aucune partie adverse. Ajoutez-les pour générer correctement les actes.',
      fisica: 'Personne physique',
      giuridica: 'Personne morale',
      legale: 'Avocat : {nome}',
    },
    documenti: {
      titolo: 'Documents · {n}',
      aggiungi: 'Ajouter',
      vuoto: 'Aucun document lié à ce dossier.',
      archivio: 'Archives',
    },
    ricerche: {
      titolo: 'Recherches · {n}',
      bancaDati: 'Base de données',
      vuoto: 'Aucune recherche. Les chats avec Lex sur ce dossier, une fois enregistrés, apparaissent ici.',
      chat: 'Chat avec Lex',
      ai: 'Recherche IA',
      appunti: 'Notes',
    },
    lex: {
      passo1: 'Je lis le dossier',
      passo2: 'Je cherche dans les lois et la jurisprudence',
      passo3: 'Je rédige la réponse',
      titolo: 'Lex connaît ce dossier',
      testo:
        'Client, parties adverses, audiences, documents et recherches. Lex ne lit pas les notes internes. Demandez une analyse, une stratégie ou un acte : chaque acte coûte 1 crédit.',
      atti: 'Actes que Lex peut préparer',
      prepara: 'Préparer : {atto}',
      nuovaDomanda: 'Nouvelle question',
      segnaposto: 'Demandez à Lex sur ce dossier…',
      inBreve: 'réponse de test sur « {titolo} ».',
      cosaSo: 'Ce que je sais de ce dossier.',
      cosaSoTesto:
        ' Client {cliente} ; {controparti} parties adverses, {udienze} audiences, {documenti} documents et {ricerche} recherches.',
      nota: "À partir de l'étape « Studio », Lex répond ici sur le dossier, comme sur le site. Un acte généré devient un PDF à enregistrer dans le dossier et coûte 1 crédit.",
    },
  },

  calendario: {
    titolo: 'Calendrier',
    nuovo: 'Nouveau rendez-vous',
    agenda: 'Agenda',
    mese: 'Mois',
    prossimiUno: '1 événement dans les 7 prochains jours',
    prossimiMolti: '{n} événements dans les 7 prochains jours',
    passati: 'Afficher aussi les deux dernières semaines',
    niente: 'Rien de prévu.',
    mesePrecedente: 'Mois précédent',
    meseSuccessivo: 'Mois suivant',
    oggi: "Aujourd'hui",
    giornoEventi: '{giorno}, {n} événements',
    evento: '{ora}, {tipo} : {titolo}',
  },

  fogli: {
    note: {
      titolo: 'Notes internes',
      testo: "Seuls vous (et l'étude) les voyez. Lex ne les lit pas.",
      campo: 'Notes',
      salva: 'Enregistrer les notes',
    },
    chiudi: {
      titolo: 'Clôturer le dossier',
      testo: 'Choisissez le résultat. Vous pourrez rouvrir le dossier quand vous voulez.',
      esito: 'Résultat',
      conferma: 'Confirmer la clôture',
    },
    elimina: {
      titolo: 'Supprimer le dossier ?',
      testo:
        'Les audiences, délais, parties adverses, recherches et rendez-vous sont aussi supprimés. Les documents des Archives restent. Action irréversible.',
      conferma: 'Pour confirmer, écrivez : {titolo}',
      fatture: "Des factures sont liées à ce dossier : dissociez-les d'abord, depuis la facture.",
      elimina: 'Supprimer le dossier',
    },
    termine: {
      titolo: 'Nouveau délai',
      testo: "Il apparaît aussi dans le calendrier, le jour de l'échéance.",
      campo: 'Délai',
      esempio: 'Ex. Dépôt de la réplique',
      evento: 'Événement de départ (facultatif)',
      eventoEsempio: 'Ex. Notification du jugement',
      scadenza: 'Échéance',
      traGiorni: 'Dans {n} jours',
      dataErrata: 'Écrivez la date au format jj.mm.aaaa.',
      aggiungi: 'Ajouter le délai',
    },
    udienza: {
      titolo: 'Nouvelle audience',
      tipo: "Type d'audience",
      tipoEsempio: 'Ex. Audience de conciliation',
      data: 'Date',
      ora: 'Heure',
      sede: 'Lieu (facultatif)',
      sedeEsempio: 'Tribunal, section, salle',
      aggiungi: "Ajouter l'audience",
    },
    controparte: {
      titolo: 'Nouvelle partie adverse',
      fisica: 'Personne physique',
      giuridica: 'Personne morale',
      tipoPersona: 'Type de personne',
      ragioneSociale: 'Raison sociale',
      nomeCognome: 'Prénom et nom',
      ruolo: 'Position procédurale',
      legale: 'Avocat de la partie adverse (facultatif)',
      legaleEsempio: 'Ex. Me Paolo Neri, Genève',
      aggiungi: 'Ajouter la partie adverse',
    },
    evento: {
      quando: 'Quand',
      tipo: 'Type',
      cliente: 'Client',
      pratica: 'Dossier',
      sede: 'Lieu',
      noteInterne: 'Notes internes',
      noteCliente: 'Notes pour le client',
      daTermine: "C'est l'échéance d'un délai : marquez-le comme accompli dans le dossier.",
      daUdienza: "L'audience se gère dans le dossier : issue, renvoi, lieu.",
      daMandato: 'Échéance du mandat du client : elle se gère sur le site.',
      videocall: 'Ouvrir la visioconférence',
      apriPratica: 'Ouvrir le dossier',
      modifica: 'Modifier',
      concluso: 'Terminé',
      annulla: 'Annuler',
    },
    nuovoEvento: {
      nuovo: 'Nouveau rendez-vous',
      modifica: 'Modifier le rendez-vous',
      titolo: 'Titre',
      titoloEsempio: 'Ex. Rendez-vous avec le client',
      tipo: 'Type',
      giorno: 'Jour',
      oggi: "Aujourd'hui",
      domani: 'Demain',
      settimana: 'Dans une semaine',
      inizio: 'Début',
      fine: 'Fin',
      orari: 'La fin doit venir après le début.',
      cliente: 'Client',
      clienteFacoltativo: 'Client (facultatif)',
      pratica: 'Dossier',
      praticaFacoltativa: 'Dossier (facultatif)',
      link: 'Lien de la visioconférence',
      aula: 'Tribunal et salle',
      aulaEsempio: 'Ex. Tribunal de première instance, salle 12',
      noteCliente: 'Notes pour le client (facultatif)',
      noteClienteSegnaposto: 'Le client les voit aussi',
      salva: 'Enregistrer les modifications',
      aggiungi: 'Ajouter au calendrier',
    },
  },
};

export const studio = { it, de, fr };
